// Command obsgen writes the Kubernetes components that package
// deploy/observability, so the dashboards and rules have one source:
//
//   - components/alerts/prometheusrule.yaml: a PrometheusRule wrapping
//     deploy/observability/alerts/grounded.rules.yaml;
//   - components/dashboards/*.json: copies of deploy/observability/dashboards
//     (kustomize can't read files outside a component's directory).
//
// With -check it only reports whether the generated files are current
// (make obs-validate, CI).
//
//	go run ./tools/obsgen [-check]
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	rulesFile     = "deploy/observability/alerts/grounded.rules.yaml"
	dashboardsDir = "deploy/observability/dashboards"
	ruleCR        = "deploy/kubernetes/components/alerts/prometheusrule.yaml"
	dashboardsCM  = "deploy/kubernetes/components/dashboards"
)

const header = `# GENERATED by ` + "`go run ./tools/obsgen`" + ` from
# deploy/observability/alerts/grounded.rules.yaml: edit that file, not this one.
#
# Your Prometheus may select PrometheusRules by label (for example
# release: <name>); add that label in the overlay.
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: grounded
  labels:
    app.kubernetes.io/name: grounded
    app.kubernetes.io/part-of: grounded
spec:
`

func main() {
	check := flag.Bool("check", false, "fail if a generated file is stale instead of writing it")
	flag.Parse()
	files, err := outputs()
	if err != nil {
		fail(err)
	}
	stale := 0
	for path, want := range files {
		got, err := os.ReadFile(path)
		if err == nil && bytes.Equal(got, want) {
			continue
		}
		if *check {
			fmt.Fprintf(os.Stderr, "obsgen: %s is stale\n", path)
			stale++
			continue
		}
		if err := os.WriteFile(path, want, 0o644); err != nil {
			fail(err)
		}
	}
	if stale > 0 {
		fail(fmt.Errorf("run `go run ./tools/obsgen` and commit"))
	}
}

// outputs maps every generated file to its content.
func outputs() (map[string][]byte, error) {
	src, err := os.ReadFile(rulesFile)
	if err != nil {
		return nil, err
	}
	out := map[string][]byte{ruleCR: Render(src)}
	dashboards, err := filepath.Glob(filepath.Join(dashboardsDir, "*.json"))
	if err != nil {
		return nil, err
	}
	for _, d := range dashboards {
		raw, err := os.ReadFile(d)
		if err != nil {
			return nil, err
		}
		out[filepath.Join(dashboardsCM, filepath.Base(d))] = raw
	}
	return out, nil
}

// Render wraps a Prometheus rule file in a PrometheusRule: its leading
// comment block is dropped and the rest indented under spec.
func Render(rules []byte) []byte {
	var b strings.Builder
	b.WriteString(header)
	started := false
	for _, line := range strings.Split(strings.TrimRight(string(rules), "\n"), "\n") {
		if !started && (strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "") {
			continue
		}
		started = true
		if strings.TrimSpace(line) == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString("  " + line + "\n")
	}
	return []byte(b.String())
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "obsgen:", err)
	os.Exit(1)
}
