// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminListAgents = `-- name: AdminListAgents :many
SELECT a.id, a.team_id, a.slug, a.name, a.description, a.accent_color, a.welcome_message, a.starter_questions, a.status, a.disabled_reason, a.disabled_by, a.disabled_at, a.draft, a.draft_revision, a.published_version_id, a.revision, a.created_by, a.created_at, a.updated_at, a.deleted_at, t.slug AS team_slug, t.name AS team_name,
       v.version AS published_version, v.effective_rank AS published_rank, v.published_at,
       m.display_name AS chat_model_name, sn.short_name,
       coalesce(g.principal_type, 'team')::text AS audience
FROM agents a
JOIN teams t ON t.id = a.team_id
LEFT JOIN agent_versions v ON v.id = a.published_version_id
LEFT JOIN models m ON m.id = v.chat_model_id
LEFT JOIN agent_short_names sn ON sn.agent_id = a.id
LEFT JOIN agent_audience_grants g ON g.agent_id = a.id
WHERE a.deleted_at IS NULL
  AND ($1::text IS NULL OR t.slug = $1::text OR t.id::text = $1::text)
  AND ($2::text IS NULL OR a.status = $2::text)
ORDER BY t.slug, lower(a.name), a.id
LIMIT 1000
`

type AdminListAgentsParams struct {
	Team   *string
	Status *string
}

type AdminListAgentsRow struct {
	ID                 uuid.UUID
	TeamID             uuid.UUID
	Slug               string
	Name               string
	Description        string
	AccentColor        string
	WelcomeMessage     string
	StarterQuestions   []string
	Status             string
	DisabledReason     string
	DisabledBy         uuid.NullUUID
	DisabledAt         *time.Time
	Draft              json.RawMessage
	DraftRevision      int64
	PublishedVersionID uuid.NullUUID
	Revision           int64
	CreatedBy          uuid.NullUUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	TeamSlug           string
	TeamName           string
	PublishedVersion   *int32
	PublishedRank      *int32
	PublishedAt        *time.Time
	ChatModelName      *string
	ShortName          *string
	Audience           string
}

func (q *Queries) AdminListAgents(ctx context.Context, arg AdminListAgentsParams) ([]AdminListAgentsRow, error) {
	rows, err := q.db.Query(ctx, adminListAgents, arg.Team, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAgentsRow{}
	for rows.Next() {
		var i AdminListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AccentColor,
			&i.WelcomeMessage,
			&i.StarterQuestions,
			&i.Status,
			&i.DisabledReason,
			&i.DisabledBy,
			&i.DisabledAt,
			&i.Draft,
			&i.DraftRevision,
			&i.PublishedVersionID,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamSlug,
			&i.TeamName,
			&i.PublishedVersion,
			&i.PublishedRank,
			&i.PublishedAt,
			&i.ChatModelName,
			&i.ShortName,
			&i.Audience,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentsPublishingKB = `-- name: AgentsPublishingKB :many

SELECT a.id, a.name, a.slug
FROM agents a JOIN agent_version_kbs vk ON vk.version_id = a.published_version_id
WHERE vk.kb_id = $1 AND a.deleted_at IS NULL
ORDER BY lower(a.name)
`

type AgentsPublishingKBRow struct {
	ID   uuid.UUID
	Name string
	Slug string
}

// ---- KB usage (kb_in_use) -------------------------------------------------------
// Live agents whose published version searches a KB.
func (q *Queries) AgentsPublishingKB(ctx context.Context, kbID uuid.UUID) ([]AgentsPublishingKBRow, error) {
	rows, err := q.db.Query(ctx, agentsPublishingKB, kbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentsPublishingKBRow{}
	for rows.Next() {
		var i AgentsPublishingKBRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const agentsWithDraftKB = `-- name: AgentsWithDraftKB :many
SELECT id, team_id, slug, name, description, accent_color, welcome_message, starter_questions, status, disabled_reason, disabled_by, disabled_at, draft, draft_revision, published_version_id, revision, created_by, created_at, updated_at, deleted_at FROM agents
WHERE team_id = $1 AND deleted_at IS NULL
  AND draft -> 'kbs' @> jsonb_build_array(jsonb_build_object('kbId', $2::text))
FOR UPDATE
`

type AgentsWithDraftKBParams struct {
	TeamID uuid.UUID
	KBID   string
}

func (q *Queries) AgentsWithDraftKB(ctx context.Context, arg AgentsWithDraftKBParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, agentsWithDraftKB, arg.TeamID, arg.KBID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AccentColor,
			&i.WelcomeMessage,
			&i.StarterQuestions,
			&i.Status,
			&i.DisabledReason,
			&i.DisabledBy,
			&i.DisabledAt,
			&i.Draft,
			&i.DraftRevision,
			&i.PublishedVersionID,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const classificationByRank = `-- name: ClassificationByRank :one
SELECT key, name, description, rank, max_audience, revision, created_at, updated_at, anonymous_retention_hours, conversation_retention_days, allowed_source_types, direct_retrieve FROM classification_levels WHERE rank <= $1 ORDER BY rank DESC LIMIT 1
`

func (q *Queries) ClassificationByRank(ctx context.Context, rank int32) (ClassificationLevel, error) {
	row := q.db.QueryRow(ctx, classificationByRank, rank)
	var i ClassificationLevel
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Rank,
		&i.MaxAudience,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnonymousRetentionHours,
		&i.ConversationRetentionDays,
		&i.AllowedSourceTypes,
		&i.DirectRetrieve,
	)
	return i, err
}

const countTeamAgents = `-- name: CountTeamAgents :one

SELECT count(*) FROM agents WHERE team_id = $1 AND deleted_at IS NULL
`

// ---- agents ----------------------------------------------------------------
func (q *Queries) CountTeamAgents(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamAgents, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUnservedVersionKB = `-- name: DeleteUnservedVersionKB :exec
DELETE FROM agent_version_kbs vk
WHERE vk.kb_id = $1
  AND NOT EXISTS (SELECT 1 FROM agents a WHERE a.published_version_id = vk.version_id AND a.deleted_at IS NULL)
`

// Rows of versions that are no longer served (older versions, deleted agents).
func (q *Queries) DeleteUnservedVersionKB(ctx context.Context, kbID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnservedVersionKB, kbID)
	return err
}

const directoryForTeam = `-- name: DirectoryForTeam :many
SELECT a.id, a.team_id, a.slug, a.name, a.description, a.accent_color, a.welcome_message, a.starter_questions, a.status, a.disabled_reason, a.disabled_by, a.disabled_at, a.draft, a.draft_revision, a.published_version_id, a.revision, a.created_by, a.created_at, a.updated_at, a.deleted_at, t.slug AS team_slug, t.name AS team_name
FROM agents a JOIN teams t ON t.id = a.team_id
WHERE a.team_id = $1 AND a.deleted_at IS NULL AND a.published_version_id IS NOT NULL
  AND a.status = 'active' AND t.status = 'active'
ORDER BY lower(a.name), a.id
`

type DirectoryForTeamRow struct {
	ID                 uuid.UUID
	TeamID             uuid.UUID
	Slug               string
	Name               string
	Description        string
	AccentColor        string
	WelcomeMessage     string
	StarterQuestions   []string
	Status             string
	DisabledReason     string
	DisabledBy         uuid.NullUUID
	DisabledAt         *time.Time
	Draft              json.RawMessage
	DraftRevision      int64
	PublishedVersionID uuid.NullUUID
	Revision           int64
	CreatedBy          uuid.NullUUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	TeamSlug           string
	TeamName           string
}

func (q *Queries) DirectoryForTeam(ctx context.Context, teamID uuid.UUID) ([]DirectoryForTeamRow, error) {
	rows, err := q.db.Query(ctx, directoryForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectoryForTeamRow{}
	for rows.Next() {
		var i DirectoryForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AccentColor,
			&i.WelcomeMessage,
			&i.StarterQuestions,
			&i.Status,
			&i.DisabledReason,
			&i.DisabledBy,
			&i.DisabledAt,
			&i.Draft,
			&i.DraftRevision,
			&i.PublishedVersionID,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamSlug,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const directoryForUser = `-- name: DirectoryForUser :many

SELECT a.id, a.team_id, a.slug, a.name, a.description, a.accent_color, a.welcome_message, a.starter_questions, a.status, a.disabled_reason, a.disabled_by, a.disabled_at, a.draft, a.draft_revision, a.published_version_id, a.revision, a.created_by, a.created_at, a.updated_at, a.deleted_at, t.slug AS team_slug, t.name AS team_name
FROM agents a
JOIN teams t ON t.id = a.team_id
JOIN team_members tm ON tm.team_id = a.team_id AND tm.user_id = $1
WHERE a.deleted_at IS NULL AND a.published_version_id IS NOT NULL AND a.status = 'active' AND t.status = 'active'
ORDER BY lower(a.name), a.id
`

type DirectoryForUserRow struct {
	ID                 uuid.UUID
	TeamID             uuid.UUID
	Slug               string
	Name               string
	Description        string
	AccentColor        string
	WelcomeMessage     string
	StarterQuestions   []string
	Status             string
	DisabledReason     string
	DisabledBy         uuid.NullUUID
	DisabledAt         *time.Time
	Draft              json.RawMessage
	DraftRevision      int64
	PublishedVersionID uuid.NullUUID
	Revision           int64
	CreatedBy          uuid.NullUUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	TeamSlug           string
	TeamName           string
}

// ---- directory -------------------------------------------------------------------
// Published, active agents of the teams a user belongs to.
func (q *Queries) DirectoryForUser(ctx context.Context, userID uuid.UUID) ([]DirectoryForUserRow, error) {
	rows, err := q.db.Query(ctx, directoryForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DirectoryForUserRow{}
	for rows.Next() {
		var i DirectoryForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AccentColor,
			&i.WelcomeMessage,
			&i.StarterQuestions,
			&i.Status,
			&i.DisabledReason,
			&i.DisabledBy,
			&i.DisabledAt,
			&i.Draft,
			&i.DraftRevision,
			&i.PublishedVersionID,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TeamSlug,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const documentTitles = `-- name: DocumentTitles :many
SELECT id, CASE WHEN title <> '' THEN title WHEN filename <> '' THEN filename ELSE url END::text AS title
FROM documents WHERE id = ANY($1::uuid[])
`

type DocumentTitlesRow struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) DocumentTitles(ctx context.Context, ids []uuid.UUID) ([]DocumentTitlesRow, error) {
	rows, err := q.db.Query(ctx, documentTitles, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentTitlesRow{}
	for rows.Next() {
		var i DocumentTitlesRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgent = `-- name: GetAgent :one
SELECT id, team_id, slug, name, description, accent_color, welcome_message, starter_questions, status, disabled_reason, disabled_by, disabled_at, draft, draft_revision, published_version_id, revision, created_by, created_at, updated_at, deleted_at FROM agents WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AccentColor,
		&i.WelcomeMessage,
		&i.StarterQuestions,
		&i.Status,
		&i.DisabledReason,
		&i.DisabledBy,
		&i.DisabledAt,
		&i.Draft,
		&i.DraftRevision,
		&i.PublishedVersionID,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAgentBySlug = `-- name: GetAgentBySlug :one
SELECT id, team_id, slug, name, description, accent_color, welcome_message, starter_questions, status, disabled_reason, disabled_by, disabled_at, draft, draft_revision, published_version_id, revision, created_by, created_at, updated_at, deleted_at FROM agents WHERE team_id = $1 AND slug = $2 AND deleted_at IS NULL
`

type GetAgentBySlugParams struct {
	TeamID uuid.UUID
	Slug   string
}

func (q *Queries) GetAgentBySlug(ctx context.Context, arg GetAgentBySlugParams) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentBySlug, arg.TeamID, arg.Slug)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AccentColor,
		&i.WelcomeMessage,
		&i.StarterQuestions,
		&i.Status,
		&i.DisabledReason,
		&i.DisabledBy,
		&i.DisabledAt,
		&i.Draft,
		&i.DraftRevision,
		&i.PublishedVersionID,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAgentVersion = `-- name: GetAgentVersion :one
SELECT id, agent_id, version, config, chat_model_id, effective_rank, note, published_by, published_at FROM agent_versions WHERE id = $1
`

func (q *Queries) GetAgentVersion(ctx context.Context, id uuid.UUID) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, getAgentVersion, id)
	var i AgentVersion
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Version,
		&i.Config,
		&i.ChatModelID,
		&i.EffectiveRank,
		&i.Note,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const getAgentVersionByNumber = `-- name: GetAgentVersionByNumber :one
SELECT id, agent_id, version, config, chat_model_id, effective_rank, note, published_by, published_at FROM agent_versions WHERE agent_id = $1 AND version = $2
`

type GetAgentVersionByNumberParams struct {
	AgentID uuid.UUID
	Version int32
}

func (q *Queries) GetAgentVersionByNumber(ctx context.Context, arg GetAgentVersionByNumberParams) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, getAgentVersionByNumber, arg.AgentID, arg.Version)
	var i AgentVersion
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Version,
		&i.Config,
		&i.ChatModelID,
		&i.EffectiveRank,
		&i.Note,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const getAudienceGrant = `-- name: GetAudienceGrant :one
SELECT agent_id, principal_type, principal_id, created_by, created_at FROM agent_audience_grants WHERE agent_id = $1
`

func (q *Queries) GetAudienceGrant(ctx context.Context, agentID uuid.UUID) (AgentAudienceGrant, error) {
	row := q.db.QueryRow(ctx, getAudienceGrant, agentID)
	var i AgentAudienceGrant
	err := row.Scan(
		&i.AgentID,
		&i.PrincipalType,
		&i.PrincipalID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, agent_id, user_id, title, last_version_id, created_at, updated_at, deleted_at, anonymous, anon_session_id FROM conversations WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.Title,
		&i.LastVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Anonymous,
		&i.AnonSessionID,
	)
	return i, err
}

const getMessageOwner = `-- name: GetMessageOwner :one
SELECT m.id, m.role, c.user_id, c.agent_id
FROM messages m JOIN conversations c ON c.id = m.conversation_id
WHERE m.id = $1 AND c.deleted_at IS NULL
`

type GetMessageOwnerRow struct {
	ID      uuid.UUID
	Role    string
	UserID  uuid.NullUUID
	AgentID uuid.UUID
}

func (q *Queries) GetMessageOwner(ctx context.Context, id uuid.UUID) (GetMessageOwnerRow, error) {
	row := q.db.QueryRow(ctx, getMessageOwner, id)
	var i GetMessageOwnerRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.UserID,
		&i.AgentID,
	)
	return i, err
}

const insertAccessLog = `-- name: InsertAccessLog :exec
INSERT INTO access_log (user_id, api_key_id, agent_id, agent_version_id, rank, channel)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAccessLogParams struct {
	UserID         uuid.NullUUID
	APIKeyID       uuid.NullUUID
	AgentID        uuid.UUID
	AgentVersionID uuid.NullUUID
	Rank           int32
	Channel        string
}

func (q *Queries) InsertAccessLog(ctx context.Context, arg InsertAccessLogParams) error {
	_, err := q.db.Exec(ctx, insertAccessLog,
		arg.UserID,
		arg.APIKeyID,
		arg.AgentID,
		arg.AgentVersionID,
		arg.Rank,
		arg.Channel,
	)
	return err
}

const insertAgent = `-- name: InsertAgent :one
INSERT INTO agents (team_id, slug, name, description, accent_color, welcome_message, starter_questions, draft, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, team_id, slug, name, description, accent_color, welcome_message, starter_questions, status, disabled_reason, disabled_by, disabled_at, draft, draft_revision, published_version_id, revision, created_by, created_at, updated_at, deleted_at
`

type InsertAgentParams struct {
	TeamID           uuid.UUID
	Slug             string
	Name             string
	Description      string
	AccentColor      string
	WelcomeMessage   string
	StarterQuestions []string
	Draft            json.RawMessage
	CreatedBy        uuid.NullUUID
}

func (q *Queries) InsertAgent(ctx context.Context, arg InsertAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, insertAgent,
		arg.TeamID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.AccentColor,
		arg.WelcomeMessage,
		arg.StarterQuestions,
		arg.Draft,
		arg.CreatedBy,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AccentColor,
		&i.WelcomeMessage,
		&i.StarterQuestions,
		&i.Status,
		&i.DisabledReason,
		&i.DisabledBy,
		&i.DisabledAt,
		&i.Draft,
		&i.DraftRevision,
		&i.PublishedVersionID,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertAgentVersion = `-- name: InsertAgentVersion :one
INSERT INTO agent_versions (agent_id, version, config, chat_model_id, effective_rank, note, published_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, agent_id, version, config, chat_model_id, effective_rank, note, published_by, published_at
`

type InsertAgentVersionParams struct {
	AgentID       uuid.UUID
	Version       int32
	Config        json.RawMessage
	ChatModelID   uuid.UUID
	EffectiveRank int32
	Note          string
	PublishedBy   uuid.NullUUID
}

func (q *Queries) InsertAgentVersion(ctx context.Context, arg InsertAgentVersionParams) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, insertAgentVersion,
		arg.AgentID,
		arg.Version,
		arg.Config,
		arg.ChatModelID,
		arg.EffectiveRank,
		arg.Note,
		arg.PublishedBy,
	)
	var i AgentVersion
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Version,
		&i.Config,
		&i.ChatModelID,
		&i.EffectiveRank,
		&i.Note,
		&i.PublishedBy,
		&i.PublishedAt,
	)
	return i, err
}

const insertAgentVersionKB = `-- name: InsertAgentVersionKB :exec
INSERT INTO agent_version_kbs (version_id, kb_id) VALUES ($1, $2)
`

type InsertAgentVersionKBParams struct {
	VersionID uuid.UUID
	KBID      uuid.UUID
}

func (q *Queries) InsertAgentVersionKB(ctx context.Context, arg InsertAgentVersionKBParams) error {
	_, err := q.db.Exec(ctx, insertAgentVersionKB, arg.VersionID, arg.KBID)
	return err
}

const insertAudienceGrant = `-- name: InsertAudienceGrant :exec
INSERT INTO agent_audience_grants (agent_id, principal_type, principal_id, created_by)
VALUES ($1, $2, $3, $4)
`

type InsertAudienceGrantParams struct {
	AgentID       uuid.UUID
	PrincipalType string
	PrincipalID   uuid.NullUUID
	CreatedBy     uuid.NullUUID
}

func (q *Queries) InsertAudienceGrant(ctx context.Context, arg InsertAudienceGrantParams) error {
	_, err := q.db.Exec(ctx, insertAudienceGrant,
		arg.AgentID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.CreatedBy,
	)
	return err
}

const insertConversation = `-- name: InsertConversation :one

INSERT INTO conversations (agent_id, user_id, title, last_version_id)
VALUES ($1, $2::uuid, $3, $4)
RETURNING id, agent_id, user_id, title, last_version_id, created_at, updated_at, deleted_at, anonymous, anon_session_id
`

type InsertConversationParams struct {
	AgentID       uuid.UUID
	UserID        uuid.UUID
	Title         string
	LastVersionID uuid.NullUUID
}

// ---- conversations ---------------------------------------------------------------
func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, insertConversation,
		arg.AgentID,
		arg.UserID,
		arg.Title,
		arg.LastVersionID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.Title,
		&i.LastVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Anonymous,
		&i.AnonSessionID,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (id, conversation_id, seq, role, content, citations, agent_version_id, model_id, usage,
                      stop_reason, error_code, latency_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12)
RETURNING id, conversation_id, seq, role, content, citations, agent_version_id, model_id, usage, stop_reason, error_code, latency_ms, created_at
`

type InsertMessageParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Seq            int32
	Role           string
	Content        json.RawMessage
	Citations      json.RawMessage
	AgentVersionID uuid.NullUUID
	ModelID        uuid.NullUUID
	Usage          json.RawMessage
	StopReason     string
	ErrorCode      string
	LatencyMs      *int32
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.Seq,
		arg.Role,
		arg.Content,
		arg.Citations,
		arg.AgentVersionID,
		arg.ModelID,
		arg.Usage,
		arg.StopReason,
		arg.ErrorCode,
		arg.LatencyMs,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Seq,
		&i.Role,
		&i.Content,
		&i.Citations,
		&i.AgentVersionID,
		&i.ModelID,
		&i.Usage,
		&i.StopReason,
		&i.ErrorCode,
		&i.LatencyMs,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessageEvent = `-- name: InsertMessageEvent :exec

INSERT INTO message_events (team_id, agent_id, agent_version_id, message_id, channel, audience_type, model_id,
                            latency_ms, first_token_ms, input_tokens, output_tokens, reasoning_tokens,
                            hit_count, top_similarity, no_context, refused, tool_calls, cited_document_ids,
                            stop_reason, error_code, pseudonymous_user, moderation_input, moderation_output, judging,
                            citations, scope)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12,
        $13, $14, $15, $16, $17, $18,
        $19, $20, $21, $22, $23, $24,
        $25, $26)
`

type InsertMessageEventParams struct {
	TeamID           uuid.UUID
	AgentID          uuid.UUID
	AgentVersionID   uuid.NullUUID
	MessageID        uuid.NullUUID
	Channel          string
	AudienceType     string
	ModelID          uuid.NullUUID
	LatencyMs        int32
	FirstTokenMs     *int32
	InputTokens      int32
	OutputTokens     int32
	ReasoningTokens  int32
	HitCount         int32
	TopSimilarity    pgtype.Float4
	NoContext        bool
	Refused          bool
	ToolCalls        int32
	CitedDocumentIds []uuid.UUID
	StopReason       string
	ErrorCode        string
	PseudonymousUser *string
	ModerationInput  json.RawMessage
	ModerationOutput json.RawMessage
	Judging          json.RawMessage
	Citations        json.RawMessage
	Scope            json.RawMessage
}

// ---- analytics events and access log ------------------------------------------------
func (q *Queries) InsertMessageEvent(ctx context.Context, arg InsertMessageEventParams) error {
	_, err := q.db.Exec(ctx, insertMessageEvent,
		arg.TeamID,
		arg.AgentID,
		arg.AgentVersionID,
		arg.MessageID,
		arg.Channel,
		arg.AudienceType,
		arg.ModelID,
		arg.LatencyMs,
		arg.FirstTokenMs,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.HitCount,
		arg.TopSimilarity,
		arg.NoContext,
		arg.Refused,
		arg.ToolCalls,
		arg.CitedDocumentIds,
		arg.StopReason,
		arg.ErrorCode,
		arg.PseudonymousUser,
		arg.ModerationInput,
		arg.ModerationOutput,
		arg.Judging,
		arg.Citations,
		arg.Scope,
	)
	return err
}

const kBPolicyRows = `-- name: KBPolicyRows :many

SELECT kb.id, kb.team_id, kb.name, kb.embedding_profile_id,
       coalesce((SELECT max(cl.rank) FROM kb_sources ks
                 JOIN data_sources s ON s.id = ks.source_id
                 JOIN classification_levels cl ON cl.key = s.classification
                 WHERE ks.kb_id = kb.id), 0)::int AS rank,
       m.enabled AS embed_model_enabled, ml.rank::int AS embed_model_rank, m.display_name AS embed_model_name
FROM knowledge_bases kb
JOIN embedding_profiles p ON p.id = kb.embedding_profile_id
JOIN models m ON m.id = p.model_id
JOIN classification_levels ml ON ml.key = m.max_classification
WHERE kb.id = ANY($1::uuid[])
`

type KBPolicyRowsRow struct {
	ID                 uuid.UUID
	TeamID             uuid.UUID
	Name               string
	EmbeddingProfileID uuid.UUID
	Rank               int32
	EmbedModelEnabled  bool
	EmbedModelRank     int32
	EmbedModelName     string
}

// ---- ranks and policy -------------------------------------------------------------
// Current rank of each KB (max over its sources; 0 without sources) with
// the embedding model's ceiling.
func (q *Queries) KBPolicyRows(ctx context.Context, ids []uuid.UUID) ([]KBPolicyRowsRow, error) {
	rows, err := q.db.Query(ctx, kBPolicyRows, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KBPolicyRowsRow{}
	for rows.Next() {
		var i KBPolicyRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.EmbeddingProfileID,
			&i.Rank,
			&i.EmbedModelEnabled,
			&i.EmbedModelRank,
			&i.EmbedModelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessLog = `-- name: ListAccessLog :many
SELECT l.id, l.user_id, l.api_key_id, l.agent_id, l.agent_version_id, l.rank, l.channel, l.at, coalesce(u.email, '')::text AS user_email, coalesce(u.display_name, '')::text AS user_name,
       coalesce(a.name, '')::text AS agent_name, coalesce(a.slug, '')::text AS agent_slug,
       coalesce(t.slug, '')::text AS team_slug, v.version AS agent_version,
       coalesce(cl.key, '')::text AS classification
FROM access_log l
LEFT JOIN users u ON u.id = l.user_id
LEFT JOIN agents a ON a.id = l.agent_id
LEFT JOIN teams t ON t.id = a.team_id
LEFT JOIN agent_versions v ON v.id = l.agent_version_id
LEFT JOIN classification_levels cl ON cl.rank = l.rank
WHERE ($1::timestamptz IS NULL OR l.at >= $1::timestamptz)
  AND ($2::timestamptz IS NULL OR l.at < $2::timestamptz)
  AND ($3::uuid IS NULL OR l.agent_id = $3::uuid)
  AND ($4::uuid IS NULL OR l.user_id = $4::uuid)
  AND ($5::text IS NULL OR l.channel = $5::text)
  AND ($6::timestamptz IS NULL
       OR (l.at, l.id) < ($6::timestamptz, $7::bigint))
ORDER BY l.at DESC, l.id DESC
LIMIT $8
`

type ListAccessLogParams struct {
	FromAt   *time.Time
	ToAt     *time.Time
	AgentID  uuid.NullUUID
	UserID   uuid.NullUUID
	Channel  *string
	BeforeAt *time.Time
	BeforeID *int64
	PageSize int32
}

type ListAccessLogRow struct {
	ID             int64
	UserID         uuid.NullUUID
	APIKeyID       uuid.NullUUID
	AgentID        uuid.UUID
	AgentVersionID uuid.NullUUID
	Rank           int32
	Channel        string
	At             time.Time
	UserEmail      string
	UserName       string
	AgentName      string
	AgentSlug      string
	TeamSlug       string
	AgentVersion   *int32
	Classification string
}

func (q *Queries) ListAccessLog(ctx context.Context, arg ListAccessLogParams) ([]ListAccessLogRow, error) {
	rows, err := q.db.Query(ctx, listAccessLog,
		arg.FromAt,
		arg.ToAt,
		arg.AgentID,
		arg.UserID,
		arg.Channel,
		arg.BeforeAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessLogRow{}
	for rows.Next() {
		var i ListAccessLogRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.APIKeyID,
			&i.AgentID,
			&i.AgentVersionID,
			&i.Rank,
			&i.Channel,
			&i.At,
			&i.UserEmail,
			&i.UserName,
			&i.AgentName,
			&i.AgentSlug,
			&i.TeamSlug,
			&i.AgentVersion,
			&i.Classification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentVersions = `-- name: ListAgentVersions :many
SELECT v.id, v.agent_id, v.version, v.config, v.chat_model_id, v.effective_rank, v.note, v.published_by, v.published_at, coalesce(u.display_name, '')::text AS published_by_name
FROM agent_versions v LEFT JOIN users u ON u.id = v.published_by
WHERE v.agent_id = $1 ORDER BY v.version DESC
`

type ListAgentVersionsRow struct {
	ID              uuid.UUID
	AgentID         uuid.UUID
	Version         int32
	Config          json.RawMessage
	ChatModelID     uuid.UUID
	EffectiveRank   int32
	Note            string
	PublishedBy     uuid.NullUUID
	PublishedAt     time.Time
	PublishedByName string
}

func (q *Queries) ListAgentVersions(ctx context.Context, agentID uuid.UUID) ([]ListAgentVersionsRow, error) {
	rows, err := q.db.Query(ctx, listAgentVersions, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentVersionsRow{}
	for rows.Next() {
		var i ListAgentVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Version,
			&i.Config,
			&i.ChatModelID,
			&i.EffectiveRank,
			&i.Note,
			&i.PublishedBy,
			&i.PublishedAt,
			&i.PublishedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassificationLevels = `-- name: ListClassificationLevels :many
SELECT key, name, description, rank, max_audience, revision, created_at, updated_at, anonymous_retention_hours, conversation_retention_days, allowed_source_types, direct_retrieve FROM classification_levels ORDER BY rank
`

func (q *Queries) ListClassificationLevels(ctx context.Context) ([]ClassificationLevel, error) {
	rows, err := q.db.Query(ctx, listClassificationLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassificationLevel{}
	for rows.Next() {
		var i ClassificationLevel
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Rank,
			&i.MaxAudience,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnonymousRetentionHours,
			&i.ConversationRetentionDays,
			&i.AllowedSourceTypes,
			&i.DirectRetrieve,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT c.id, c.agent_id, c.user_id, c.title, c.last_version_id, c.created_at, c.updated_at, c.deleted_at, c.anonymous, c.anon_session_id, a.name AS agent_name, a.slug AS agent_slug, t.slug AS team_slug,
       (a.deleted_at IS NOT NULL)::bool AS agent_deleted
FROM conversations c
JOIN agents a ON a.id = c.agent_id
JOIN teams t ON t.id = a.team_id
WHERE c.user_id = $1::uuid AND c.deleted_at IS NULL
  AND ($2::uuid IS NULL OR c.agent_id = $2::uuid)
  -- A personal API key reaches its team's agents only, or the ones it names.
  AND ($3::uuid IS NULL OR a.team_id = $3::uuid)
  AND ($4::uuid[] IS NULL OR c.agent_id = ANY($4::uuid[]))
  AND ($5::text IS NULL
       OR (c.title || ' ' || a.name) ILIKE '%' || $5::text || '%' ESCAPE '\')
  AND ($6::timestamptz IS NULL OR c.updated_at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR c.updated_at < $7::timestamptz)
  AND ($8::timestamptz IS NULL
       OR (c.updated_at, c.id) < ($8::timestamptz, $9::uuid))
ORDER BY c.updated_at DESC, c.id DESC
LIMIT $10
`

type ListConversationsParams struct {
	UserID        uuid.UUID
	AgentID       uuid.NullUUID
	TeamID        uuid.NullUUID
	AgentIDs      []uuid.UUID
	Search        *string
	UpdatedFrom   *time.Time
	UpdatedTo     *time.Time
	BeforeUpdated *time.Time
	BeforeID      uuid.NullUUID
	PageSize      int32
}

type ListConversationsRow struct {
	ID            uuid.UUID
	AgentID       uuid.UUID
	UserID        uuid.NullUUID
	Title         string
	LastVersionID uuid.NullUUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	Anonymous     bool
	AnonSessionID uuid.NullUUID
	AgentName     string
	AgentSlug     string
	TeamSlug      string
	AgentDeleted  bool
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations,
		arg.UserID,
		arg.AgentID,
		arg.TeamID,
		arg.AgentIDs,
		arg.Search,
		arg.UpdatedFrom,
		arg.UpdatedTo,
		arg.BeforeUpdated,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsRow{}
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.UserID,
			&i.Title,
			&i.LastVersionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Anonymous,
			&i.AnonSessionID,
			&i.AgentName,
			&i.AgentSlug,
			&i.TeamSlug,
			&i.AgentDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.conversation_id, m.seq, m.role, m.content, m.citations, m.agent_version_id, m.model_id, m.usage, m.stop_reason, m.error_code, m.latency_ms, m.created_at, e.feedback, e.feedback_reason, e.citations AS citation_check,
       coalesce(e.refused, false)::bool AS answer_refused, coalesce(e.no_context, false)::bool AS answer_no_context
FROM messages m LEFT JOIN message_events e ON e.message_id = m.id
WHERE m.conversation_id = $1
ORDER BY m.seq
`

type ListMessagesRow struct {
	ID              uuid.UUID
	ConversationID  uuid.UUID
	Seq             int32
	Role            string
	Content         json.RawMessage
	Citations       json.RawMessage
	AgentVersionID  uuid.NullUUID
	ModelID         uuid.NullUUID
	Usage           json.RawMessage
	StopReason      string
	ErrorCode       string
	LatencyMs       *int32
	CreatedAt       time.Time
	Feedback        *string
	FeedbackReason  *string
	CitationCheck   json.RawMessage
	AnswerRefused   bool
	AnswerNoContext bool
}

// citation_check is the answer's content-free citation check record (NULL:
// not checked), and answer_refused and answer_no_context its analytics flags.
func (q *Queries) ListMessages(ctx context.Context, conversationID uuid.UUID) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.Citations,
			&i.AgentVersionID,
			&i.ModelID,
			&i.Usage,
			&i.StopReason,
			&i.ErrorCode,
			&i.LatencyMs,
			&i.CreatedAt,
			&i.Feedback,
			&i.FeedbackReason,
			&i.CitationCheck,
			&i.AnswerRefused,
			&i.AnswerNoContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamAgents = `-- name: ListTeamAgents :many
SELECT id, team_id, slug, name, description, accent_color, welcome_message, starter_questions, status, disabled_reason, disabled_by, disabled_at, draft, draft_revision, published_version_id, revision, created_by, created_at, updated_at, deleted_at FROM agents WHERE team_id = $1 AND deleted_at IS NULL ORDER BY lower(name), id
`

func (q *Queries) ListTeamAgents(ctx context.Context, teamID uuid.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listTeamAgents, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AccentColor,
			&i.WelcomeMessage,
			&i.StarterQuestions,
			&i.Status,
			&i.DisabledReason,
			&i.DisabledBy,
			&i.DisabledAt,
			&i.Draft,
			&i.DraftRevision,
			&i.PublishedVersionID,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgent = `-- name: LockAgent :one
SELECT id, team_id, slug, name, description, accent_color, welcome_message, starter_questions, status, disabled_reason, disabled_by, disabled_at, draft, draft_revision, published_version_id, revision, created_by, created_at, updated_at, deleted_at FROM agents WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) LockAgent(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, lockAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AccentColor,
		&i.WelcomeMessage,
		&i.StarterQuestions,
		&i.Status,
		&i.DisabledReason,
		&i.DisabledBy,
		&i.DisabledAt,
		&i.Draft,
		&i.DraftRevision,
		&i.PublishedVersionID,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const lockConversation = `-- name: LockConversation :one
SELECT id, agent_id, user_id, title, last_version_id, created_at, updated_at, deleted_at, anonymous, anon_session_id FROM conversations WHERE id = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) LockConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, lockConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.Title,
		&i.LastVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Anonymous,
		&i.AnonSessionID,
	)
	return i, err
}

const modelWithRank = `-- name: ModelWithRank :one
SELECT m.id, m.connection_id, m.key, m.upstream_model, m.display_name, m.description, m.kind, m.max_classification, m.enabled, m.context_window, m.max_output_tokens, m.supports_tools, m.supports_vision, m.dimensions, m.max_input_tokens, m.compat, m.revision, m.created_by, m.created_at, m.updated_at, m.moderation_provider, m.moderation_family, m.moderation_timeout_seconds, cl.rank::int AS max_rank, c.enabled AS connection_enabled
FROM models m
JOIN classification_levels cl ON cl.key = m.max_classification
JOIN model_connections c ON c.id = m.connection_id
WHERE m.id = $1
`

type ModelWithRankRow struct {
	ID                       uuid.UUID
	ConnectionID             uuid.UUID
	Key                      string
	UpstreamModel            string
	DisplayName              string
	Description              string
	Kind                     string
	MaxClassification        string
	Enabled                  bool
	ContextWindow            *int32
	MaxOutputTokens          *int32
	SupportsTools            bool
	SupportsVision           bool
	Dimensions               *int32
	MaxInputTokens           *int32
	Compat                   json.RawMessage
	Revision                 int64
	CreatedBy                uuid.NullUUID
	CreatedAt                time.Time
	UpdatedAt                time.Time
	ModerationProvider       *string
	ModerationFamily         *string
	ModerationTimeoutSeconds *int32
	MaxRank                  int32
	ConnectionEnabled        bool
}

func (q *Queries) ModelWithRank(ctx context.Context, id uuid.UUID) (ModelWithRankRow, error) {
	row := q.db.QueryRow(ctx, modelWithRank, id)
	var i ModelWithRankRow
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Key,
		&i.UpstreamModel,
		&i.DisplayName,
		&i.Description,
		&i.Kind,
		&i.MaxClassification,
		&i.Enabled,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.SupportsTools,
		&i.SupportsVision,
		&i.Dimensions,
		&i.MaxInputTokens,
		&i.Compat,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationProvider,
		&i.ModerationFamily,
		&i.ModerationTimeoutSeconds,
		&i.MaxRank,
		&i.ConnectionEnabled,
	)
	return i, err
}

const nextAgentVersion = `-- name: NextAgentVersion :one

SELECT coalesce(max(version), 0)::int + 1 FROM agent_versions WHERE agent_id = $1
`

// ---- versions --------------------------------------------------------------
func (q *Queries) NextAgentVersion(ctx context.Context, agentID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextAgentVersion, agentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nextMessageSeq = `-- name: NextMessageSeq :one
SELECT coalesce(max(seq), 0)::int + 1 FROM messages WHERE conversation_id = $1
`

func (q *Queries) NextMessageSeq(ctx context.Context, conversationID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextMessageSeq, conversationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const renameConversation = `-- name: RenameConversation :one
UPDATE conversations SET title = $1, updated_at = now() WHERE id = $2 RETURNING id, agent_id, user_id, title, last_version_id, created_at, updated_at, deleted_at, anonymous, anon_session_id
`

type RenameConversationParams struct {
	Title string
	ID    uuid.UUID
}

func (q *Queries) RenameConversation(ctx context.Context, arg RenameConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, renameConversation, arg.Title, arg.ID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.Title,
		&i.LastVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Anonymous,
		&i.AnonSessionID,
	)
	return i, err
}

const setAgentDraft = `-- name: SetAgentDraft :one
UPDATE agents SET draft = $1, draft_revision = draft_revision + 1, revision = revision + 1, updated_at = now()
WHERE id = $2
RETURNING id, team_id, slug, name, description, accent_color, welcome_message, starter_questions, status, disabled_reason, disabled_by, disabled_at, draft, draft_revision, published_version_id, revision, created_by, created_at, updated_at, deleted_at
`

type SetAgentDraftParams struct {
	Draft json.RawMessage
	ID    uuid.UUID
}

func (q *Queries) SetAgentDraft(ctx context.Context, arg SetAgentDraftParams) (Agent, error) {
	row := q.db.QueryRow(ctx, setAgentDraft, arg.Draft, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AccentColor,
		&i.WelcomeMessage,
		&i.StarterQuestions,
		&i.Status,
		&i.DisabledReason,
		&i.DisabledBy,
		&i.DisabledAt,
		&i.Draft,
		&i.DraftRevision,
		&i.PublishedVersionID,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setAgentPublished = `-- name: SetAgentPublished :one
UPDATE agents SET published_version_id = $1, revision = revision + 1, updated_at = now()
WHERE id = $2
RETURNING id, team_id, slug, name, description, accent_color, welcome_message, starter_questions, status, disabled_reason, disabled_by, disabled_at, draft, draft_revision, published_version_id, revision, created_by, created_at, updated_at, deleted_at
`

type SetAgentPublishedParams struct {
	VersionID uuid.NullUUID
	ID        uuid.UUID
}

func (q *Queries) SetAgentPublished(ctx context.Context, arg SetAgentPublishedParams) (Agent, error) {
	row := q.db.QueryRow(ctx, setAgentPublished, arg.VersionID, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AccentColor,
		&i.WelcomeMessage,
		&i.StarterQuestions,
		&i.Status,
		&i.DisabledReason,
		&i.DisabledBy,
		&i.DisabledAt,
		&i.Draft,
		&i.DraftRevision,
		&i.PublishedVersionID,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setAgentStatus = `-- name: SetAgentStatus :one
UPDATE agents
SET status = $1, disabled_reason = $2, disabled_by = $3, disabled_at = $4,
    revision = revision + 1, updated_at = now()
WHERE id = $5
RETURNING id, team_id, slug, name, description, accent_color, welcome_message, starter_questions, status, disabled_reason, disabled_by, disabled_at, draft, draft_revision, published_version_id, revision, created_by, created_at, updated_at, deleted_at
`

type SetAgentStatusParams struct {
	Status         string
	DisabledReason string
	DisabledBy     uuid.NullUUID
	DisabledAt     *time.Time
	ID             uuid.UUID
}

func (q *Queries) SetAgentStatus(ctx context.Context, arg SetAgentStatusParams) (Agent, error) {
	row := q.db.QueryRow(ctx, setAgentStatus,
		arg.Status,
		arg.DisabledReason,
		arg.DisabledBy,
		arg.DisabledAt,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AccentColor,
		&i.WelcomeMessage,
		&i.StarterQuestions,
		&i.Status,
		&i.DisabledReason,
		&i.DisabledBy,
		&i.DisabledAt,
		&i.Draft,
		&i.DraftRevision,
		&i.PublishedVersionID,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setMessageFeedback = `-- name: SetMessageFeedback :execrows
UPDATE message_events SET feedback = $1, feedback_reason = $2, feedback_at = now()
WHERE message_id = $3
`

type SetMessageFeedbackParams struct {
	Feedback       *string
	FeedbackReason *string
	MessageID      uuid.NullUUID
}

func (q *Queries) SetMessageFeedback(ctx context.Context, arg SetMessageFeedbackParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMessageFeedback, arg.Feedback, arg.FeedbackReason, arg.MessageID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteAgent = `-- name: SoftDeleteAgent :exec
UPDATE agents SET deleted_at = now(), revision = revision + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAgent, id)
	return err
}

const softDeleteConversation = `-- name: SoftDeleteConversation :exec
UPDATE conversations SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteConversation, id)
	return err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations SET updated_at = now(), last_version_id = $1 WHERE id = $2
`

type TouchConversationParams struct {
	LastVersionID uuid.NullUUID
	ID            uuid.UUID
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.Exec(ctx, touchConversation, arg.LastVersionID, arg.ID)
	return err
}

const updateAgentProfile = `-- name: UpdateAgentProfile :one
UPDATE agents
SET slug = $1, name = $2, description = $3, accent_color = $4,
    welcome_message = $5, starter_questions = $6,
    draft = $7, draft_revision = draft_revision + CASE WHEN $8::bool THEN 1 ELSE 0 END,
    revision = revision + 1, updated_at = now()
WHERE id = $9
RETURNING id, team_id, slug, name, description, accent_color, welcome_message, starter_questions, status, disabled_reason, disabled_by, disabled_at, draft, draft_revision, published_version_id, revision, created_by, created_at, updated_at, deleted_at
`

type UpdateAgentProfileParams struct {
	Slug             string
	Name             string
	Description      string
	AccentColor      string
	WelcomeMessage   string
	StarterQuestions []string
	Draft            json.RawMessage
	DraftChanged     bool
	ID               uuid.UUID
}

func (q *Queries) UpdateAgentProfile(ctx context.Context, arg UpdateAgentProfileParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentProfile,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.AccentColor,
		arg.WelcomeMessage,
		arg.StarterQuestions,
		arg.Draft,
		arg.DraftChanged,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AccentColor,
		&i.WelcomeMessage,
		&i.StarterQuestions,
		&i.Status,
		&i.DisabledReason,
		&i.DisabledBy,
		&i.DisabledAt,
		&i.Draft,
		&i.DraftRevision,
		&i.PublishedVersionID,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const versionsByIDs = `-- name: VersionsByIDs :many
SELECT id, agent_id, version, config, chat_model_id, effective_rank, note, published_by, published_at FROM agent_versions WHERE id = ANY($1::uuid[])
`

func (q *Queries) VersionsByIDs(ctx context.Context, ids []uuid.UUID) ([]AgentVersion, error) {
	rows, err := q.db.Query(ctx, versionsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentVersion{}
	for rows.Next() {
		var i AgentVersion
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Version,
			&i.Config,
			&i.ChatModelID,
			&i.EffectiveRank,
			&i.Note,
			&i.PublishedBy,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
