// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, team_id, kind, user_id, name, prefix, secret_hash, scopes, kb_ids, expires_at, last_used_at, revoked_at, created_by, created_at, agent_ids, pepper_id FROM api_keys WHERE id = $1
`

func (q *Queries) GetAPIKey(ctx context.Context, id uuid.UUID) (APIKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Kind,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scopes,
		&i.KBIDs,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.AgentIDs,
		&i.PepperID,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT k.id, k.team_id, k.kind, k.user_id, k.name, k.prefix, k.secret_hash, k.scopes, k.kb_ids, k.expires_at, k.last_used_at, k.revoked_at, k.created_by, k.created_at, k.agent_ids, k.pepper_id, t.status AS team_status
FROM api_keys k JOIN teams t ON t.id = k.team_id
WHERE k.prefix = $1
`

type GetAPIKeyByPrefixRow struct {
	APIKey     APIKey
	TeamStatus string
}

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (GetAPIKeyByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i GetAPIKeyByPrefixRow
	err := row.Scan(
		&i.APIKey.ID,
		&i.APIKey.TeamID,
		&i.APIKey.Kind,
		&i.APIKey.UserID,
		&i.APIKey.Name,
		&i.APIKey.Prefix,
		&i.APIKey.SecretHash,
		&i.APIKey.Scopes,
		&i.APIKey.KBIDs,
		&i.APIKey.ExpiresAt,
		&i.APIKey.LastUsedAt,
		&i.APIKey.RevokedAt,
		&i.APIKey.CreatedBy,
		&i.APIKey.CreatedAt,
		&i.APIKey.AgentIDs,
		&i.APIKey.PepperID,
		&i.TeamStatus,
	)
	return i, err
}

const getTeamAPIKey = `-- name: GetTeamAPIKey :one
SELECT k.id, k.team_id, k.kind, k.user_id, k.name, k.prefix, k.secret_hash, k.scopes, k.kb_ids, k.expires_at, k.last_used_at, k.revoked_at, k.created_by, k.created_at, k.agent_ids, k.pepper_id, coalesce(u.email::text, '')::text AS user_email, coalesce(u.display_name, '')::text AS user_name
FROM api_keys k LEFT JOIN users u ON u.id = k.user_id
WHERE k.id = $1 AND k.team_id = $2
`

type GetTeamAPIKeyParams struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

type GetTeamAPIKeyRow struct {
	APIKey    APIKey
	UserEmail string
	UserName  string
}

// One of a team's keys by ID, revoked or not, named like ListTeamAPIKeys.
func (q *Queries) GetTeamAPIKey(ctx context.Context, arg GetTeamAPIKeyParams) (GetTeamAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getTeamAPIKey, arg.ID, arg.TeamID)
	var i GetTeamAPIKeyRow
	err := row.Scan(
		&i.APIKey.ID,
		&i.APIKey.TeamID,
		&i.APIKey.Kind,
		&i.APIKey.UserID,
		&i.APIKey.Name,
		&i.APIKey.Prefix,
		&i.APIKey.SecretHash,
		&i.APIKey.Scopes,
		&i.APIKey.KBIDs,
		&i.APIKey.ExpiresAt,
		&i.APIKey.LastUsedAt,
		&i.APIKey.RevokedAt,
		&i.APIKey.CreatedBy,
		&i.APIKey.CreatedAt,
		&i.APIKey.AgentIDs,
		&i.APIKey.PepperID,
		&i.UserEmail,
		&i.UserName,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (team_id, kind, user_id, name, prefix, secret_hash, pepper_id, scopes, kb_ids, agent_ids, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, team_id, kind, user_id, name, prefix, secret_hash, scopes, kb_ids, expires_at, last_used_at, revoked_at, created_by, created_at, agent_ids, pepper_id
`

type InsertAPIKeyParams struct {
	TeamID     uuid.UUID
	Kind       string
	UserID     uuid.NullUUID
	Name       string
	Prefix     string
	SecretHash []byte
	PepperID   []byte
	Scopes     []string
	KBIDs      []uuid.UUID
	AgentIDs   []uuid.UUID
	ExpiresAt  *time.Time
	CreatedBy  uuid.NullUUID
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (APIKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.TeamID,
		arg.Kind,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.SecretHash,
		arg.PepperID,
		arg.Scopes,
		arg.KBIDs,
		arg.AgentIDs,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Kind,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scopes,
		&i.KBIDs,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.AgentIDs,
		&i.PepperID,
	)
	return i, err
}

const isTeamMember = `-- name: IsTeamMember :one
SELECT EXISTS (SELECT 1 FROM team_members m JOIN users u ON u.id = m.user_id
               WHERE m.team_id = $1 AND m.user_id = $2 AND u.status = 'active')
`

type IsTeamMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) IsTeamMember(ctx context.Context, arg IsTeamMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeamMember, arg.TeamID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listTeamAPIKeys = `-- name: ListTeamAPIKeys :many
SELECT k.id, k.team_id, k.kind, k.user_id, k.name, k.prefix, k.secret_hash, k.scopes, k.kb_ids, k.expires_at, k.last_used_at, k.revoked_at, k.created_by, k.created_at, k.agent_ids, k.pepper_id, coalesce(u.email::text, '')::text AS user_email, coalesce(u.display_name, '')::text AS user_name
FROM api_keys k LEFT JOIN users u ON u.id = k.user_id
WHERE k.team_id = $1 AND k.revoked_at IS NULL
  AND ($2::uuid IS NULL OR (k.kind = 'personal' AND k.user_id = $2::uuid))
ORDER BY k.created_at DESC
`

type ListTeamAPIKeysParams struct {
	TeamID uuid.UUID
	UserID uuid.NullUUID
}

type ListTeamAPIKeysRow struct {
	APIKey    APIKey
	UserEmail string
	UserName  string
}

// With the owner (personal) or responsible contact (service) named.
func (q *Queries) ListTeamAPIKeys(ctx context.Context, arg ListTeamAPIKeysParams) ([]ListTeamAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listTeamAPIKeys, arg.TeamID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamAPIKeysRow{}
	for rows.Next() {
		var i ListTeamAPIKeysRow
		if err := rows.Scan(
			&i.APIKey.ID,
			&i.APIKey.TeamID,
			&i.APIKey.Kind,
			&i.APIKey.UserID,
			&i.APIKey.Name,
			&i.APIKey.Prefix,
			&i.APIKey.SecretHash,
			&i.APIKey.Scopes,
			&i.APIKey.KBIDs,
			&i.APIKey.ExpiresAt,
			&i.APIKey.LastUsedAt,
			&i.APIKey.RevokedAt,
			&i.APIKey.CreatedBy,
			&i.APIKey.CreatedAt,
			&i.APIKey.AgentIDs,
			&i.APIKey.PepperID,
			&i.UserEmail,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const revokePersonalKeys = `-- name: RevokePersonalKeys :execrows
UPDATE api_keys SET revoked_at = now()
WHERE team_id = $1 AND user_id = $2 AND kind = 'personal' AND revoked_at IS NULL
`

type RevokePersonalKeysParams struct {
	TeamID uuid.UUID
	UserID uuid.NullUUID
}

func (q *Queries) RevokePersonalKeys(ctx context.Context, arg RevokePersonalKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePersonalKeys, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAPIKeyContact = `-- name: SetAPIKeyContact :one
UPDATE api_keys SET user_id = $1 WHERE id = $2 AND kind = 'service' AND revoked_at IS NULL
RETURNING id, team_id, kind, user_id, name, prefix, secret_hash, scopes, kb_ids, expires_at, last_used_at, revoked_at, created_by, created_at, agent_ids, pepper_id
`

type SetAPIKeyContactParams struct {
	UserID uuid.NullUUID
	ID     uuid.UUID
}

func (q *Queries) SetAPIKeyContact(ctx context.Context, arg SetAPIKeyContactParams) (APIKey, error) {
	row := q.db.QueryRow(ctx, setAPIKeyContact, arg.UserID, arg.ID)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Kind,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scopes,
		&i.KBIDs,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.AgentIDs,
		&i.PepperID,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
