// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (
    actor_kind, actor_user_id, team_id, action, target_type, target_id,
    before_state, after_state, metadata, request_id, client_ip
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
`

type InsertAuditParams struct {
	ActorKind   string
	ActorUserID uuid.NullUUID
	TeamID      uuid.NullUUID
	Action      string
	TargetType  string
	TargetID    string
	BeforeState json.RawMessage
	AfterState  json.RawMessage
	Metadata    json.RawMessage
	RequestID   string
	ClientIP    string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorKind,
		arg.ActorUserID,
		arg.TeamID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.BeforeState,
		arg.AfterState,
		arg.Metadata,
		arg.RequestID,
		arg.ClientIP,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT a.id, a.occurred_at, a.actor_kind, a.actor_user_id, a.team_id, a.action,
       a.target_type, a.target_id, a.before_state, a.after_state, a.metadata,
       a.request_id, a.client_ip,
       COALESCE(u.email::text, '')::text AS actor_email,
       u.display_name AS actor_display_name,
       k.name AS actor_api_key_name,
       COALESCE(live.label, '')::text AS live_label,
       COALESCE(CASE WHEN live.label IS NULL THEN (
           SELECT COALESCE(h.metadata->>'name', h.after_state->>'name', h.after_state->>'displayName',
                           h.after_state->>'pattern', h.before_state->>'name',
                           h.before_state->>'displayName', h.before_state->>'pattern',
                           CASE WHEN h.target_type = 'data_source' THEN h.metadata->>'sourceName' END)
           FROM audit_log h
           WHERE h.target_type = a.target_type AND h.target_id = a.target_id AND a.target_id <> ''
             AND COALESCE(h.metadata->>'name', h.after_state->>'name', h.after_state->>'displayName',
                          h.after_state->>'pattern', h.before_state->>'name',
                          h.before_state->>'displayName', h.before_state->>'pattern',
                          CASE WHEN h.target_type = 'data_source' THEN h.metadata->>'sourceName' END) IS NOT NULL
           ORDER BY h.id DESC
           LIMIT 1
       ) END, '')::text AS recorded_label,
       (CASE a.target_type WHEN 'publishable_key' THEN 'agent' WHEN 'document' THEN 'data_source' ELSE '' END)::text AS parent_type,
       COALESCE(ids.parent_uuid::text, '')::text AS parent_id,
       COALESCE(CASE a.target_type
           WHEN 'publishable_key' THEN (SELECT pa.name FROM agents pa WHERE pa.id = ids.parent_uuid AND pa.deleted_at IS NULL)
           WHEN 'document' THEN (SELECT ps.name FROM data_sources ps WHERE ps.id = ids.parent_uuid)
       END, '')::text AS parent_label
FROM audit_log a
CROSS JOIN LATERAL (
    SELECT CASE WHEN a.target_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
                THEN a.target_id::uuid END AS target_uuid,
           CASE WHEN a.metadata->>'apiKeyId' ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
                THEN (a.metadata->>'apiKeyId')::uuid END AS key_uuid,
           CASE WHEN p.raw ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN p.raw::uuid END AS parent_uuid
    FROM (SELECT CASE a.target_type WHEN 'publishable_key' THEN a.metadata->>'agentId'
                                    WHEN 'document' THEN a.metadata->>'sourceId' END AS raw) p
) ids
LEFT JOIN users u ON u.id = a.actor_user_id
LEFT JOIN api_keys k ON a.actor_kind = 'api_key' AND k.id = ids.key_uuid
CROSS JOIN LATERAL (
    SELECT (CASE a.target_type
        WHEN 'team' THEN (SELECT t.name FROM teams t WHERE t.id = ids.target_uuid)
        WHEN 'user' THEN (SELECT COALESCE(NULLIF(x.display_name, ''), x.email::text) FROM users x WHERE x.id = ids.target_uuid)
        WHEN 'data_source' THEN (SELECT s.name FROM data_sources s WHERE s.id = ids.target_uuid)
        WHEN 'document' THEN (SELECT COALESCE(NULLIF(d.title, ''), NULLIF(d.filename, ''), d.url) FROM documents d WHERE d.id = ids.target_uuid)
        WHEN 'knowledge_base' THEN (SELECT kb.name FROM knowledge_bases kb WHERE kb.id = ids.target_uuid)
        WHEN 'agent' THEN (SELECT ag.name FROM agents ag WHERE ag.id = ids.target_uuid AND ag.deleted_at IS NULL)
        WHEN 'api_key' THEN (SELECT ak.name FROM api_keys ak WHERE ak.id = ids.target_uuid)
        WHEN 'model_connection' THEN (SELECT c.name FROM model_connections c WHERE c.id = ids.target_uuid)
        WHEN 'model' THEN (SELECT m.display_name FROM models m WHERE m.id = ids.target_uuid)
        WHEN 'embedding_profile' THEN (SELECT p.name FROM embedding_profiles p WHERE p.id = ids.target_uuid)
        WHEN 'crawl_domain_request' THEN (SELECT r.pattern FROM crawl_domain_requests r WHERE r.id = ids.target_uuid)
        WHEN 'crawl_allowlist' THEN (SELECT w.pattern FROM crawl_allowlist w WHERE w.id = ids.target_uuid)
        WHEN 'team_invite' THEN (SELECT i.email::text FROM team_invites i WHERE i.id = ids.target_uuid)
        WHEN 'classification' THEN (SELECT cl.name FROM classification_levels cl WHERE cl.key = a.target_id)
        WHEN 'publishable_key' THEN (SELECT pk.name FROM publishable_keys pk WHERE pk.id = ids.target_uuid)
        WHEN 'moderation_policy' THEN (CASE a.target_id WHEN 'team' THEN 'Team moderation policy'
                                                        WHEN 'all_authenticated' THEN 'Signed-in users moderation policy'
                                                        WHEN 'public' THEN 'Public moderation policy' END)
        WHEN 'platform_settings' THEN (CASE a.target_id WHEN 'public_agents_enabled' THEN 'Public access' ELSE 'Platform settings' END)
        WHEN 'platform_limits' THEN 'Platform limits'
        WHEN 'platform_keys' THEN 'Key rotation'
        WHEN 'systemone_settings' THEN 'SystemOne settings'
        WHEN 'parsing_settings' THEN 'Parsing settings'
        WHEN 'retention_settings' THEN 'Retention settings'
        WHEN 'retention' THEN 'Retention run'
        WHEN 'legal_hold' THEN (SELECT 'Legal hold on ' || lh.scope_type || ' ' || lh.scope_label FROM legal_holds lh WHERE lh.id = ids.target_uuid)
        -- Break-glass (ADR-0024): a conversation is never named (its title is content).
        WHEN 'break_glass_session' THEN (SELECT 'Break-glass: ' || bt.name FROM break_glass_sessions bg JOIN teams bt ON bt.id = bg.team_id WHERE bg.id = ids.target_uuid)
        WHEN 'break_glass_settings' THEN 'Break-glass settings'
        WHEN 'sso_group_rule' THEN (SELECT 'Group ' || gr.group_name || ' → ' || grt.name FROM sso_group_rules gr JOIN teams grt ON grt.id = gr.team_id WHERE gr.id = ids.target_uuid)
        WHEN 'conversation' THEN (SELECT 'Conversation' FROM conversations cv WHERE cv.id = ids.target_uuid)
    END)::text AS label
) live
WHERE ($1::uuid IS NULL OR a.team_id = $1::uuid)
  AND ($2::bigint IS NULL OR a.id < $2::bigint)
  AND ($3::text IS NULL OR a.action = $3::text)
  AND ($4::text IS NULL OR a.action LIKE $4::text || '%' ESCAPE '\')
  AND ($5::text IS NULL OR a.action NOT LIKE $5::text || '%' ESCAPE '\')
  AND ($6::uuid IS NULL OR a.actor_user_id = $6::uuid)
  AND ($7::text IS NULL OR a.target_type = $7::text)
  AND ($8::timestamptz IS NULL OR a.occurred_at >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR a.occurred_at < $9::timestamptz)
ORDER BY a.id DESC
LIMIT $10
`

type ListAuditParams struct {
	TeamID        uuid.NullUUID
	BeforeID      *int64
	Action        *string
	ActionPrefix  *string
	ExcludePrefix *string
	ActorUserID   uuid.NullUUID
	TargetType    *string
	OccurredFrom  *time.Time
	OccurredTo    *time.Time
	PageSize      int32
}

type ListAuditRow struct {
	ID               int64
	OccurredAt       time.Time
	ActorKind        string
	ActorUserID      uuid.NullUUID
	TeamID           uuid.NullUUID
	Action           string
	TargetType       string
	TargetID         string
	BeforeState      json.RawMessage
	AfterState       json.RawMessage
	Metadata         json.RawMessage
	RequestID        string
	ClientIP         string
	ActorEmail       string
	ActorDisplayName *string
	ActorApiKeyName  *string
	LiveLabel        string
	RecordedLabel    string
	ParentType       string
	ParentID         string
	ParentLabel      string
}

// One page of the audit log, newest first, with the actor and the target's
// name resolved at read time (DESIGN.md §13). live_label is the target's
// current name (” when it no longer exists); recorded_label is the last
// name the log recorded for the same target, used for deleted targets (” when
// none). Names are never empty, so ” means unknown.
// Every target type the code audits is covered here (a test enumerates them);
// singletons (platform settings, limits, SystemOne settings, moderation
// policies) always have a live label. parent_* names the object a target
// belongs to, for linking: a publishable key's agent, a document's source
// (parent_label ” when the parent no longer exists).
// action_prefix and exclude_prefix are LIKE-escaped by the caller.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.TeamID,
		arg.BeforeID,
		arg.Action,
		arg.ActionPrefix,
		arg.ExcludePrefix,
		arg.ActorUserID,
		arg.TargetType,
		arg.OccurredFrom,
		arg.OccurredTo,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditRow{}
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorKind,
			&i.ActorUserID,
			&i.TeamID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.BeforeState,
			&i.AfterState,
			&i.Metadata,
			&i.RequestID,
			&i.ClientIP,
			&i.ActorEmail,
			&i.ActorDisplayName,
			&i.ActorApiKeyName,
			&i.LiveLabel,
			&i.RecordedLabel,
			&i.ParentType,
			&i.ParentID,
			&i.ParentLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
