// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: breakglass.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeBreakGlassGrant = `-- name: ActiveBreakGlassGrant :one
SELECT id, team_id, requested_by, scopes, status, started_at, expires_at
FROM break_glass_sessions
WHERE requested_by = $1 AND team_id = $2 AND status = 'active'
`

type ActiveBreakGlassGrantParams struct {
	AdminID uuid.UUID
	TeamID  uuid.UUID
}

type ActiveBreakGlassGrantRow struct {
	ID          uuid.UUID
	TeamID      uuid.UUID
	RequestedBy uuid.UUID
	Scopes      []string
	Status      string
	StartedAt   *time.Time
	ExpiresAt   *time.Time
}

// The admin's active session for a team, checked on every content read.
func (q *Queries) ActiveBreakGlassGrant(ctx context.Context, arg ActiveBreakGlassGrantParams) (ActiveBreakGlassGrantRow, error) {
	row := q.db.QueryRow(ctx, activeBreakGlassGrant, arg.AdminID, arg.TeamID)
	var i ActiveBreakGlassGrantRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RequestedBy,
		&i.Scopes,
		&i.Status,
		&i.StartedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const approveBreakGlassSession = `-- name: ApproveBreakGlassSession :one
UPDATE break_glass_sessions
SET status = 'active', decided_by = $1, decided_at = $2, started_at = $2, expires_at = $3,
    approval_deadline = NULL
WHERE id = $4 AND status = 'pending'
RETURNING id, team_id, requested_by, reason, scopes, duration_minutes, status, requested_at, approval_deadline, decided_by, decided_at, decision_note, started_at, expires_at, ended_at, ended_by
`

type ApproveBreakGlassSessionParams struct {
	DecidedBy uuid.NullUUID
	Now       *time.Time
	ExpiresAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) ApproveBreakGlassSession(ctx context.Context, arg ApproveBreakGlassSessionParams) (BreakGlassSession, error) {
	row := q.db.QueryRow(ctx, approveBreakGlassSession,
		arg.DecidedBy,
		arg.Now,
		arg.ExpiresAt,
		arg.ID,
	)
	var i BreakGlassSession
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RequestedBy,
		&i.Reason,
		&i.Scopes,
		&i.DurationMinutes,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovalDeadline,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndedBy,
	)
	return i, err
}

const breakGlassReadCounts = `-- name: BreakGlassReadCounts :many
SELECT (metadata->>'kind')::text AS kind, count(*)::bigint AS reads, count(DISTINCT target_id)::bigint AS targets
FROM audit_log
WHERE action = 'breakglass.read' AND metadata->>'sessionId' = $1::text
GROUP BY 1
ORDER BY 1
`

type BreakGlassReadCountsRow struct {
	Kind    string
	Reads   int64
	Targets int64
}

// What a session read, by kind: every read and the distinct targets.
func (q *Queries) BreakGlassReadCounts(ctx context.Context, sessionID string) ([]BreakGlassReadCountsRow, error) {
	rows, err := q.db.Query(ctx, breakGlassReadCounts, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakGlassReadCountsRow{}
	for rows.Next() {
		var i BreakGlassReadCountsRow
		if err := rows.Scan(&i.Kind, &i.Reads, &i.Targets); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeBreakGlassSession = `-- name: CloseBreakGlassSession :one
UPDATE break_glass_sessions
SET status = $1,
    decided_by = coalesce($2::uuid, decided_by),
    decided_at = CASE WHEN $2::uuid IS NULL THEN decided_at ELSE $3 END,
    decision_note = coalesce($4::text, decision_note),
    ended_by = $5::uuid,
    ended_at = $3,
    approval_deadline = NULL
WHERE id = $6 AND status IN ('pending', 'active')
RETURNING id, team_id, requested_by, reason, scopes, duration_minutes, status, requested_at, approval_deadline, decided_by, decided_at, decision_note, started_at, expires_at, ended_at, ended_by
`

type CloseBreakGlassSessionParams struct {
	Status       string
	DecidedBy    uuid.NullUUID
	Now          *time.Time
	DecisionNote *string
	EndedBy      uuid.NullUUID
	ID           uuid.UUID
}

// Denies, cancels, ends or expires a session (the caller checked the move).
func (q *Queries) CloseBreakGlassSession(ctx context.Context, arg CloseBreakGlassSessionParams) (BreakGlassSession, error) {
	row := q.db.QueryRow(ctx, closeBreakGlassSession,
		arg.Status,
		arg.DecidedBy,
		arg.Now,
		arg.DecisionNote,
		arg.EndedBy,
		arg.ID,
	)
	var i BreakGlassSession
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RequestedBy,
		&i.Reason,
		&i.Scopes,
		&i.DurationMinutes,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovalDeadline,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndedBy,
	)
	return i, err
}

const conversationTeam = `-- name: ConversationTeam :one
SELECT a.team_id FROM conversations c JOIN agents a ON a.id = c.agent_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

// The team whose agent a (not deleted) conversation is with.
func (q *Queries) ConversationTeam(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, conversationTeam, id)
	var team_id uuid.UUID
	err := row.Scan(&team_id)
	return team_id, err
}

const dueBreakGlassSessions = `-- name: DueBreakGlassSessions :many
SELECT id, team_id, requested_by, reason, scopes, duration_minutes, status, requested_at, approval_deadline, decided_by, decided_at, decision_note, started_at, expires_at, ended_at, ended_by FROM break_glass_sessions
WHERE (status = 'active' AND expires_at <= $1) OR (status = 'pending' AND approval_deadline <= $1)
ORDER BY requested_at
LIMIT 100
FOR UPDATE SKIP LOCKED
`

// Open sessions past their end or approval deadline, locked for the sweep
// (another process sweeping at the same time skips them).
func (q *Queries) DueBreakGlassSessions(ctx context.Context, now *time.Time) ([]BreakGlassSession, error) {
	rows, err := q.db.Query(ctx, dueBreakGlassSessions, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakGlassSession{}
	for rows.Next() {
		var i BreakGlassSession
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.RequestedBy,
			&i.Reason,
			&i.Scopes,
			&i.DurationMinutes,
			&i.Status,
			&i.RequestedAt,
			&i.ApprovalDeadline,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.EndedAt,
			&i.EndedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBreakGlassSession = `-- name: GetBreakGlassSession :one
SELECT b.id, b.team_id, b.requested_by, b.reason, b.scopes, b.duration_minutes, b.status, b.requested_at, b.approval_deadline, b.decided_by, b.decided_at, b.decision_note, b.started_at, b.expires_at, b.ended_at, b.ended_by, t.slug AS team_slug, t.name AS team_name,
       coalesce(ru.display_name, '')::text AS requested_by_name, coalesce(ru.email, '')::text AS requested_by_email,
       coalesce(du.display_name, '')::text AS decided_by_name, coalesce(du.email, '')::text AS decided_by_email,
       coalesce(eu.display_name, '')::text AS ended_by_name, coalesce(eu.email, '')::text AS ended_by_email
FROM break_glass_sessions b
JOIN teams t ON t.id = b.team_id
JOIN users ru ON ru.id = b.requested_by
LEFT JOIN users du ON du.id = b.decided_by
LEFT JOIN users eu ON eu.id = b.ended_by
WHERE b.id = $1
`

type GetBreakGlassSessionRow struct {
	BreakGlassSession BreakGlassSession
	TeamSlug          string
	TeamName          string
	RequestedByName   string
	RequestedByEmail  string
	DecidedByName     string
	DecidedByEmail    string
	EndedByName       string
	EndedByEmail      string
}

func (q *Queries) GetBreakGlassSession(ctx context.Context, id uuid.UUID) (GetBreakGlassSessionRow, error) {
	row := q.db.QueryRow(ctx, getBreakGlassSession, id)
	var i GetBreakGlassSessionRow
	err := row.Scan(
		&i.BreakGlassSession.ID,
		&i.BreakGlassSession.TeamID,
		&i.BreakGlassSession.RequestedBy,
		&i.BreakGlassSession.Reason,
		&i.BreakGlassSession.Scopes,
		&i.BreakGlassSession.DurationMinutes,
		&i.BreakGlassSession.Status,
		&i.BreakGlassSession.RequestedAt,
		&i.BreakGlassSession.ApprovalDeadline,
		&i.BreakGlassSession.DecidedBy,
		&i.BreakGlassSession.DecidedAt,
		&i.BreakGlassSession.DecisionNote,
		&i.BreakGlassSession.StartedAt,
		&i.BreakGlassSession.ExpiresAt,
		&i.BreakGlassSession.EndedAt,
		&i.BreakGlassSession.EndedBy,
		&i.TeamSlug,
		&i.TeamName,
		&i.RequestedByName,
		&i.RequestedByEmail,
		&i.DecidedByName,
		&i.DecidedByEmail,
		&i.EndedByName,
		&i.EndedByEmail,
	)
	return i, err
}

const getBreakGlassSettings = `-- name: GetBreakGlassSettings :one

SELECT s.singleton, s.approval_required, s.max_duration_minutes, s.approval_timeout_minutes, s.revision, s.updated_by, s.updated_at, coalesce(u.display_name, '')::text AS updated_by_name, coalesce(u.email, '')::text AS updated_by_email
FROM break_glass_settings s
LEFT JOIN users u ON u.id = s.updated_by
`

type GetBreakGlassSettingsRow struct {
	Singleton              bool
	ApprovalRequired       bool
	MaxDurationMinutes     int32
	ApprovalTimeoutMinutes int32
	Revision               int64
	UpdatedBy              uuid.NullUUID
	UpdatedAt              time.Time
	UpdatedByName          string
	UpdatedByEmail         string
}

// Break-glass (docs/phase5-deploy.md §5 P4, ADR-0024).
func (q *Queries) GetBreakGlassSettings(ctx context.Context) (GetBreakGlassSettingsRow, error) {
	row := q.db.QueryRow(ctx, getBreakGlassSettings)
	var i GetBreakGlassSettingsRow
	err := row.Scan(
		&i.Singleton,
		&i.ApprovalRequired,
		&i.MaxDurationMinutes,
		&i.ApprovalTimeoutMinutes,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.UpdatedByName,
		&i.UpdatedByEmail,
	)
	return i, err
}

const insertBreakGlassSession = `-- name: InsertBreakGlassSession :one
INSERT INTO break_glass_sessions (
    team_id, requested_by, reason, scopes, duration_minutes, status, requested_at,
    approval_deadline, started_at, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10
)
RETURNING id, team_id, requested_by, reason, scopes, duration_minutes, status, requested_at, approval_deadline, decided_by, decided_at, decision_note, started_at, expires_at, ended_at, ended_by
`

type InsertBreakGlassSessionParams struct {
	TeamID           uuid.UUID
	RequestedBy      uuid.UUID
	Reason           string
	Scopes           []string
	DurationMinutes  int32
	Status           string
	RequestedAt      time.Time
	ApprovalDeadline *time.Time
	StartedAt        *time.Time
	ExpiresAt        *time.Time
}

func (q *Queries) InsertBreakGlassSession(ctx context.Context, arg InsertBreakGlassSessionParams) (BreakGlassSession, error) {
	row := q.db.QueryRow(ctx, insertBreakGlassSession,
		arg.TeamID,
		arg.RequestedBy,
		arg.Reason,
		arg.Scopes,
		arg.DurationMinutes,
		arg.Status,
		arg.RequestedAt,
		arg.ApprovalDeadline,
		arg.StartedAt,
		arg.ExpiresAt,
	)
	var i BreakGlassSession
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RequestedBy,
		&i.Reason,
		&i.Scopes,
		&i.DurationMinutes,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovalDeadline,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndedBy,
	)
	return i, err
}

const listBreakGlassReads = `-- name: ListBreakGlassReads :many
SELECT a.id, a.occurred_at, a.target_type, a.target_id, (a.metadata->>'kind')::text AS kind,
       coalesce(CASE a.target_type
           WHEN 'document' THEN (SELECT coalesce(nullif(d.title, ''), nullif(d.filename, ''), d.url) FROM documents d
                                 WHERE a.target_id ~* '^[0-9a-f-]{36}$' AND d.id = a.target_id::uuid)
           WHEN 'data_source' THEN (SELECT s.name FROM data_sources s WHERE a.target_id ~* '^[0-9a-f-]{36}$' AND s.id = a.target_id::uuid)
           WHEN 'team' THEN (SELECT t.name FROM teams t WHERE a.target_id ~* '^[0-9a-f-]{36}$' AND t.id = a.target_id::uuid)
       END, '')::text AS target_label
FROM audit_log a
WHERE a.action = 'breakglass.read' AND a.metadata->>'sessionId' = $1::text
  AND ($2::bigint IS NULL OR a.id < $2::bigint)
ORDER BY a.id DESC
LIMIT $3
`

type ListBreakGlassReadsParams struct {
	SessionID string
	BeforeID  *int64
	PageSize  int32
}

type ListBreakGlassReadsRow struct {
	ID          int64
	OccurredAt  time.Time
	TargetType  string
	TargetID    string
	Kind        string
	TargetLabel string
}

// A session's read log, newest first. Documents and sources are named (their
// names are what the team shows its members); conversations never are.
func (q *Queries) ListBreakGlassReads(ctx context.Context, arg ListBreakGlassReadsParams) ([]ListBreakGlassReadsRow, error) {
	rows, err := q.db.Query(ctx, listBreakGlassReads, arg.SessionID, arg.BeforeID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBreakGlassReadsRow{}
	for rows.Next() {
		var i ListBreakGlassReadsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.TargetType,
			&i.TargetID,
			&i.Kind,
			&i.TargetLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBreakGlassSessions = `-- name: ListBreakGlassSessions :many
SELECT b.id, b.team_id, b.requested_by, b.reason, b.scopes, b.duration_minutes, b.status, b.requested_at, b.approval_deadline, b.decided_by, b.decided_at, b.decision_note, b.started_at, b.expires_at, b.ended_at, b.ended_by, t.slug AS team_slug, t.name AS team_name,
       coalesce(ru.display_name, '')::text AS requested_by_name, coalesce(ru.email, '')::text AS requested_by_email,
       coalesce(du.display_name, '')::text AS decided_by_name, coalesce(du.email, '')::text AS decided_by_email,
       coalesce(eu.display_name, '')::text AS ended_by_name, coalesce(eu.email, '')::text AS ended_by_email
FROM break_glass_sessions b
JOIN teams t ON t.id = b.team_id
JOIN users ru ON ru.id = b.requested_by
LEFT JOIN users du ON du.id = b.decided_by
LEFT JOIN users eu ON eu.id = b.ended_by
WHERE ($1::boolean IS NULL OR (b.status IN ('pending', 'active')) = $1::boolean)
  AND ($2::uuid IS NULL OR b.requested_by = $2::uuid)
  AND ($3::uuid IS NULL OR b.team_id = $3::uuid)
  AND ($4::timestamptz IS NULL
       OR (b.requested_at, b.id) < ($4::timestamptz, $5::uuid))
ORDER BY b.requested_at DESC, b.id DESC
LIMIT $6
`

type ListBreakGlassSessionsParams struct {
	Open            pgtype.Bool
	RequestedBy     uuid.NullUUID
	TeamID          uuid.NullUUID
	BeforeRequested *time.Time
	BeforeID        uuid.NullUUID
	PageSize        int32
}

type ListBreakGlassSessionsRow struct {
	BreakGlassSession BreakGlassSession
	TeamSlug          string
	TeamName          string
	RequestedByName   string
	RequestedByEmail  string
	DecidedByName     string
	DecidedByEmail    string
	EndedByName       string
	EndedByEmail      string
}

// Sessions newest first. open: pending and active only; closed: the rest.
// requested_by and team_id narrow the list.
func (q *Queries) ListBreakGlassSessions(ctx context.Context, arg ListBreakGlassSessionsParams) ([]ListBreakGlassSessionsRow, error) {
	rows, err := q.db.Query(ctx, listBreakGlassSessions,
		arg.Open,
		arg.RequestedBy,
		arg.TeamID,
		arg.BeforeRequested,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBreakGlassSessionsRow{}
	for rows.Next() {
		var i ListBreakGlassSessionsRow
		if err := rows.Scan(
			&i.BreakGlassSession.ID,
			&i.BreakGlassSession.TeamID,
			&i.BreakGlassSession.RequestedBy,
			&i.BreakGlassSession.Reason,
			&i.BreakGlassSession.Scopes,
			&i.BreakGlassSession.DurationMinutes,
			&i.BreakGlassSession.Status,
			&i.BreakGlassSession.RequestedAt,
			&i.BreakGlassSession.ApprovalDeadline,
			&i.BreakGlassSession.DecidedBy,
			&i.BreakGlassSession.DecidedAt,
			&i.BreakGlassSession.DecisionNote,
			&i.BreakGlassSession.StartedAt,
			&i.BreakGlassSession.ExpiresAt,
			&i.BreakGlassSession.EndedAt,
			&i.BreakGlassSession.EndedBy,
			&i.TeamSlug,
			&i.TeamName,
			&i.RequestedByName,
			&i.RequestedByEmail,
			&i.DecidedByName,
			&i.DecidedByEmail,
			&i.EndedByName,
			&i.EndedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamConversations = `-- name: ListTeamConversations :many
SELECT c.id, c.agent_id, a.name AS agent_name, a.slug AS agent_slug, t.slug AS team_slug,
       (a.deleted_at IS NOT NULL)::bool AS agent_deleted, c.title, c.anonymous, c.created_at, c.updated_at,
       (SELECT count(*) FROM messages m WHERE m.conversation_id = c.id AND m.role = 'user')::bigint AS questions
FROM conversations c
JOIN agents a ON a.id = c.agent_id
JOIN teams t ON t.id = a.team_id
WHERE a.team_id = $1 AND c.deleted_at IS NULL
  AND ($2::uuid IS NULL OR c.agent_id = $2::uuid)
  AND ($3::timestamptz IS NULL
       OR (c.updated_at, c.id) < ($3::timestamptz, $4::uuid))
ORDER BY c.updated_at DESC, c.id DESC
LIMIT $5
`

type ListTeamConversationsParams struct {
	TeamID        uuid.UUID
	AgentID       uuid.NullUUID
	BeforeUpdated *time.Time
	BeforeID      uuid.NullUUID
	PageSize      int32
}

type ListTeamConversationsRow struct {
	ID           uuid.UUID
	AgentID      uuid.UUID
	AgentName    string
	AgentSlug    string
	TeamSlug     string
	AgentDeleted bool
	Title        string
	Anonymous    bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Questions    int64
}

// A team's conversations (with its agents, by anyone), most recent first:
// read under a break-glass session only. No user identity.
func (q *Queries) ListTeamConversations(ctx context.Context, arg ListTeamConversationsParams) ([]ListTeamConversationsRow, error) {
	rows, err := q.db.Query(ctx, listTeamConversations,
		arg.TeamID,
		arg.AgentID,
		arg.BeforeUpdated,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamConversationsRow{}
	for rows.Next() {
		var i ListTeamConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.AgentName,
			&i.AgentSlug,
			&i.TeamSlug,
			&i.AgentDeleted,
			&i.Title,
			&i.Anonymous,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Questions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBreakGlassSession = `-- name: LockBreakGlassSession :one
SELECT id, team_id, requested_by, reason, scopes, duration_minutes, status, requested_at, approval_deadline, decided_by, decided_at, decision_note, started_at, expires_at, ended_at, ended_by FROM break_glass_sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockBreakGlassSession(ctx context.Context, id uuid.UUID) (BreakGlassSession, error) {
	row := q.db.QueryRow(ctx, lockBreakGlassSession, id)
	var i BreakGlassSession
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.RequestedBy,
		&i.Reason,
		&i.Scopes,
		&i.DurationMinutes,
		&i.Status,
		&i.RequestedAt,
		&i.ApprovalDeadline,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.EndedAt,
		&i.EndedBy,
	)
	return i, err
}

const lockBreakGlassSettings = `-- name: LockBreakGlassSettings :one
SELECT singleton, approval_required, max_duration_minutes, approval_timeout_minutes, revision, updated_by, updated_at FROM break_glass_settings FOR UPDATE
`

func (q *Queries) LockBreakGlassSettings(ctx context.Context) (BreakGlassSetting, error) {
	row := q.db.QueryRow(ctx, lockBreakGlassSettings)
	var i BreakGlassSetting
	err := row.Scan(
		&i.Singleton,
		&i.ApprovalRequired,
		&i.MaxDurationMinutes,
		&i.ApprovalTimeoutMinutes,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const setBreakGlassSettings = `-- name: SetBreakGlassSettings :exec
UPDATE break_glass_settings
SET approval_required = $1, max_duration_minutes = $2,
    approval_timeout_minutes = $3,
    updated_by = $4, revision = revision + 1, updated_at = now()
`

type SetBreakGlassSettingsParams struct {
	ApprovalRequired       bool
	MaxDurationMinutes     int32
	ApprovalTimeoutMinutes int32
	UpdatedBy              uuid.NullUUID
}

func (q *Queries) SetBreakGlassSettings(ctx context.Context, arg SetBreakGlassSettingsParams) error {
	_, err := q.db.Exec(ctx, setBreakGlassSettings,
		arg.ApprovalRequired,
		arg.MaxDurationMinutes,
		arg.ApprovalTimeoutMinutes,
		arg.UpdatedBy,
	)
	return err
}
