// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classifications.sql

package dbgen

import (
	"context"
)

const getClassification = `-- name: GetClassification :one
SELECT key, name, description, rank, max_audience, revision, created_at, updated_at, anonymous_retention_hours, conversation_retention_days, allowed_source_types, direct_retrieve FROM classification_levels WHERE key = $1
`

func (q *Queries) GetClassification(ctx context.Context, key string) (ClassificationLevel, error) {
	row := q.db.QueryRow(ctx, getClassification, key)
	var i ClassificationLevel
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Rank,
		&i.MaxAudience,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnonymousRetentionHours,
		&i.ConversationRetentionDays,
		&i.AllowedSourceTypes,
		&i.DirectRetrieve,
	)
	return i, err
}

const insertClassification = `-- name: InsertClassification :one
INSERT INTO classification_levels (key, name, description, rank, max_audience)
VALUES ($1, $2, $3, $4, $5)
RETURNING key, name, description, rank, max_audience, revision, created_at, updated_at, anonymous_retention_hours, conversation_retention_days, allowed_source_types, direct_retrieve
`

type InsertClassificationParams struct {
	Key         string
	Name        string
	Description string
	Rank        int32
	MaxAudience string
}

func (q *Queries) InsertClassification(ctx context.Context, arg InsertClassificationParams) (ClassificationLevel, error) {
	row := q.db.QueryRow(ctx, insertClassification,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.Rank,
		arg.MaxAudience,
	)
	var i ClassificationLevel
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Rank,
		&i.MaxAudience,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnonymousRetentionHours,
		&i.ConversationRetentionDays,
		&i.AllowedSourceTypes,
		&i.DirectRetrieve,
	)
	return i, err
}

const listClassifications = `-- name: ListClassifications :many
SELECT key, name, description, rank, max_audience, revision, created_at, updated_at, anonymous_retention_hours, conversation_retention_days, allowed_source_types, direct_retrieve FROM classification_levels ORDER BY rank
`

func (q *Queries) ListClassifications(ctx context.Context) ([]ClassificationLevel, error) {
	rows, err := q.db.Query(ctx, listClassifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassificationLevel{}
	for rows.Next() {
		var i ClassificationLevel
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Description,
			&i.Rank,
			&i.MaxAudience,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnonymousRetentionHours,
			&i.ConversationRetentionDays,
			&i.AllowedSourceTypes,
			&i.DirectRetrieve,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClassificationConfig = `-- name: LockClassificationConfig :exec
SELECT pg_advisory_xact_lock(7378431001)
`

func (q *Queries) LockClassificationConfig(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockClassificationConfig)
	return err
}

const updateClassification = `-- name: UpdateClassification :one
UPDATE classification_levels
SET name         = $1,
    description  = $2,
    max_audience = $3,
    anonymous_retention_hours = $4::int,
    conversation_retention_days = $5::int,
    allowed_source_types = $6::text[],
    direct_retrieve = $7,
    revision     = revision + 1,
    updated_at   = now()
WHERE key = $8
RETURNING key, name, description, rank, max_audience, revision, created_at, updated_at, anonymous_retention_hours, conversation_retention_days, allowed_source_types, direct_retrieve
`

type UpdateClassificationParams struct {
	Name                      string
	Description               string
	MaxAudience               string
	RetentionHours            int32
	ConversationRetentionDays *int32
	AllowedSourceTypes        []string
	DirectRetrieve            bool
	Key                       string
}

func (q *Queries) UpdateClassification(ctx context.Context, arg UpdateClassificationParams) (ClassificationLevel, error) {
	row := q.db.QueryRow(ctx, updateClassification,
		arg.Name,
		arg.Description,
		arg.MaxAudience,
		arg.RetentionHours,
		arg.ConversationRetentionDays,
		arg.AllowedSourceTypes,
		arg.DirectRetrieve,
		arg.Key,
	)
	var i ClassificationLevel
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Description,
		&i.Rank,
		&i.MaxAudience,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnonymousRetentionHours,
		&i.ConversationRetentionDays,
		&i.AllowedSourceTypes,
		&i.DirectRetrieve,
	)
	return i, err
}
