// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_problems.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDocumentProblems = `-- name: CountDocumentProblems :one
SELECT count(*)::bigint AS documents, coalesce(min(d.updated_at), now())::timestamptz AS oldest
FROM documents d
WHERE d.source_id = $1 AND d.status IN ('failed', 'skipped')
  AND (d.status = 'failed' OR d.error_code = 'needs_ocr')
  AND CASE
          WHEN d.error_code = 'needs_ocr' THEN 'needs_ocr'
          WHEN d.error_code LIKE 'ocr\_%' ESCAPE '\' THEN 'ocr_error'
          WHEN d.error_code IN ('corrupt', 'encrypted', 'unsupported_format', 'too_large') THEN 'damaged'
          ELSE 'other'
      END = $2::text
`

type CountDocumentProblemsParams struct {
	SourceID uuid.UUID
	Reason   string
}

type CountDocumentProblemsRow struct {
	Documents int64
	Oldest    time.Time
}

// One source's documents of one reason class, for a notification.
func (q *Queries) CountDocumentProblems(ctx context.Context, arg CountDocumentProblemsParams) (CountDocumentProblemsRow, error) {
	row := q.db.QueryRow(ctx, countDocumentProblems, arg.SourceID, arg.Reason)
	var i CountDocumentProblemsRow
	err := row.Scan(&i.Documents, &i.Oldest)
	return i, err
}

const listDocumentProblems = `-- name: ListDocumentProblems :many

SELECT s.id AS source_id, s.name AS source_name, s.team_id,
       coalesce(t.slug::text, '')::text AS team_slug, coalesce(t.name, '')::text AS team_name,
       p.reason::text AS reason, p.documents::bigint AS documents, p.oldest::timestamptz AS oldest
FROM data_sources s
LEFT JOIN teams t ON t.id = s.team_id
CROSS JOIN LATERAL (
    SELECT CASE
               WHEN d.error_code = 'needs_ocr' THEN 'needs_ocr'
               WHEN d.error_code LIKE 'ocr\_%' ESCAPE '\' THEN 'ocr_error'
               WHEN d.error_code IN ('corrupt', 'encrypted', 'unsupported_format', 'too_large') THEN 'damaged'
               ELSE 'other'
           END AS reason,
           count(*) AS documents, min(d.updated_at) AS oldest
    FROM documents d
    WHERE d.source_id = s.id AND d.status IN ('failed', 'skipped')
      AND (d.status = 'failed' OR d.error_code = 'needs_ocr')
    GROUP BY 1
) p
ORDER BY t.name NULLS LAST, t.slug, s.name, p.reason
`

type ListDocumentProblemsRow struct {
	SourceID   uuid.UUID
	SourceName string
	TeamID     uuid.NullUUID
	TeamSlug   string
	TeamName   string
	Reason     string
	Documents  int64
	Oldest     time.Time
}

// Documents that failed or need OCR, for platform admins (Admin -> Parsing &
// OCR, owner decision 3 of docs/v0.2.0.md §7): counts per source and reason
// class, never names or text. A document counts when it failed, or was
// skipped as scanned (needs_ocr). Each source's documents are read through
// documents_source_status_idx (source_id, status), so no full scan.
// The reason classes (sources.ProblemReason) must match in both queries:
// needs_ocr; ocr_error (error codes ocr_*); damaged (corrupt, encrypted,
// unsupported_format, too_large); other.
func (q *Queries) ListDocumentProblems(ctx context.Context) ([]ListDocumentProblemsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentProblemsRow{}
	for rows.Next() {
		var i ListDocumentProblemsRow
		if err := rows.Scan(
			&i.SourceID,
			&i.SourceName,
			&i.TeamID,
			&i.TeamSlug,
			&i.TeamName,
			&i.Reason,
			&i.Documents,
			&i.Oldest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryDocumentProblems = `-- name: RetryDocumentProblems :many
UPDATE documents d
SET status = 'pending', error_code = '', error_message = '', attempts = 0, waiting_until = NULL, updated_at = now()
WHERE d.source_id = $1 AND d.status IN ('failed', 'skipped')
  AND (d.status = 'failed' OR d.error_code = 'needs_ocr')
  AND CASE
          WHEN d.error_code = 'needs_ocr' THEN 'needs_ocr'
          WHEN d.error_code LIKE 'ocr\_%' ESCAPE '\' THEN 'ocr_error'
          WHEN d.error_code IN ('corrupt', 'encrypted', 'unsupported_format', 'too_large') THEN 'damaged'
          ELSE 'other'
      END = $2::text
RETURNING d.id
`

type RetryDocumentProblemsParams struct {
	SourceID uuid.UUID
	Reason   string
}

// Queues one source's documents of one reason class again ("Retry these").
func (q *Queries) RetryDocumentProblems(ctx context.Context, arg RetryDocumentProblemsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, retryDocumentProblems, arg.SourceID, arg.Reason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
