// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evaluations.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const activeEvalRun = `-- name: ActiveEvalRun :one
SELECT id, set_id, team_id, kind, trigger, status, started_by, config, summary, total, done, error, created_at, started_at, finished_at FROM eval_runs WHERE set_id = $1 AND status IN ('queued', 'running') ORDER BY created_at LIMIT 1
`

func (q *Queries) ActiveEvalRun(ctx context.Context, setID uuid.UUID) (EvalRun, error) {
	row := q.db.QueryRow(ctx, activeEvalRun, setID)
	var i EvalRun
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.TeamID,
		&i.Kind,
		&i.Trigger,
		&i.Status,
		&i.StartedBy,
		&i.Config,
		&i.Summary,
		&i.Total,
		&i.Done,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const autoRunSetsForAgent = `-- name: AutoRunSetsForAgent :many
SELECT id, team_id, kb_id, agent_id, name, description, auto_run, created_by, revision, created_at, updated_at FROM eval_sets WHERE agent_id = $1 AND auto_run ORDER BY created_at, id
`

// Sets with automatic runs of an agent (after a publish).
func (q *Queries) AutoRunSetsForAgent(ctx context.Context, agentID uuid.NullUUID) ([]EvalSet, error) {
	rows, err := q.db.Query(ctx, autoRunSetsForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvalSet{}
	for rows.Next() {
		var i EvalSet
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.KBID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.AutoRun,
			&i.CreatedBy,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const autoRunSetsForKB = `-- name: AutoRunSetsForKB :many
SELECT id, team_id, kb_id, agent_id, name, description, auto_run, created_by, revision, created_at, updated_at FROM eval_sets WHERE kb_id = $1 AND auto_run ORDER BY created_at, id
`

// Sets with automatic runs of a knowledge base (after a profile switch).
func (q *Queries) AutoRunSetsForKB(ctx context.Context, kbID uuid.NullUUID) ([]EvalSet, error) {
	rows, err := q.db.Query(ctx, autoRunSetsForKB, kbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvalSet{}
	for rows.Next() {
		var i EvalSet
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.KBID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.AutoRun,
			&i.CreatedBy,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEvalCases = `-- name: CountEvalCases :one
SELECT count(*) FROM eval_cases WHERE set_id = $1
`

func (q *Queries) CountEvalCases(ctx context.Context, setID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEvalCases, setID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEvalCasesBefore = `-- name: CountEvalCasesBefore :one
SELECT count(*) FROM eval_cases WHERE set_id = $1 AND created_at <= $2::timestamptz
`

type CountEvalCasesBeforeParams struct {
	SetID  uuid.UUID
	Before time.Time
}

func (q *Queries) CountEvalCasesBefore(ctx context.Context, arg CountEvalCasesBeforeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEvalCasesBefore, arg.SetID, arg.Before)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamEvalSets = `-- name: CountTeamEvalSets :one
SELECT count(*) FROM eval_sets WHERE team_id = $1
`

func (q *Queries) CountTeamEvalSets(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamEvalSets, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAgentEvalSets = `-- name: DeleteAgentEvalSets :exec
DELETE FROM eval_sets WHERE agent_id = $1
`

// A soft-deleted agent's sets go with it (hard deletes cascade).
func (q *Queries) DeleteAgentEvalSets(ctx context.Context, agentID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteAgentEvalSets, agentID)
	return err
}

const deleteEvalCase = `-- name: DeleteEvalCase :exec
DELETE FROM eval_cases WHERE id = $1
`

func (q *Queries) DeleteEvalCase(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvalCase, id)
	return err
}

const deleteEvalSet = `-- name: DeleteEvalSet :exec
DELETE FROM eval_sets WHERE id = $1
`

func (q *Queries) DeleteEvalSet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvalSet, id)
	return err
}

const evalDocumentsByID = `-- name: EvalDocumentsByID :many
SELECT d.id, d.title, d.filename, d.url FROM documents d WHERE d.id = ANY($1::uuid[])
`

type EvalDocumentsByIDRow struct {
	ID       uuid.UUID
	Title    string
	Filename string
	URL      string
}

func (q *Queries) EvalDocumentsByID(ctx context.Context, ids []uuid.UUID) ([]EvalDocumentsByIDRow, error) {
	rows, err := q.db.Query(ctx, evalDocumentsByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvalDocumentsByIDRow{}
	for rows.Next() {
		var i EvalDocumentsByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.URL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const evalKBSourceIDs = `-- name: EvalKBSourceIDs :many

SELECT DISTINCT source_id FROM kb_sources WHERE kb_id = ANY($1::uuid[])
`

// ---- documents ------------------------------------------------------------------------
func (q *Queries) EvalKBSourceIDs(ctx context.Context, kbIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, evalKBSourceIDs, kbIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var source_id uuid.UUID
		if err := rows.Scan(&source_id); err != nil {
			return nil, err
		}
		items = append(items, source_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expectedDocumentExists = `-- name: ExpectedDocumentExists :one
SELECT EXISTS (
    SELECT 1 FROM documents d
    WHERE d.source_id = ANY($1::uuid[])
      AND (d.id = ANY($2::uuid[])
           OR (d.url <> '' AND rtrim(d.url, '/') = ANY($3::text[]))
           OR (d.url <> '' AND EXISTS (SELECT 1 FROM unnest($4::text[]) p WHERE starts_with(d.url, p)))
           OR (d.filename <> '' AND lower(d.filename) = ANY($5::text[])))
)::boolean
`

type ExpectedDocumentExistsParams struct {
	SourceIds   []uuid.UUID
	DocumentIds []uuid.UUID
	Urls        []string
	UrlPrefixes []string
	Filenames   []string
}

// Whether any expected document of a question still exists in the sources.
// urls are compared without trailing slashes; prefixes with starts_with;
// filenames lower-cased.
func (q *Queries) ExpectedDocumentExists(ctx context.Context, arg ExpectedDocumentExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, expectedDocumentExists,
		arg.SourceIds,
		arg.DocumentIds,
		arg.Urls,
		arg.UrlPrefixes,
		arg.Filenames,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const finishEvalRun = `-- name: FinishEvalRun :one
UPDATE eval_runs
SET status = $1, summary = $2, error = $3, finished_at = now(),
    done = (SELECT count(*) FROM eval_results r WHERE r.run_id = $4)
WHERE id = $4 AND status IN ('queued', 'running')
RETURNING id, set_id, team_id, kind, trigger, status, started_by, config, summary, total, done, error, created_at, started_at, finished_at
`

type FinishEvalRunParams struct {
	Status  string
	Summary json.RawMessage
	Error   string
	ID      uuid.UUID
}

// Ends a queued or running run (a run already ended, for example
// cancelled, is left as it is: no row).
func (q *Queries) FinishEvalRun(ctx context.Context, arg FinishEvalRunParams) (EvalRun, error) {
	row := q.db.QueryRow(ctx, finishEvalRun,
		arg.Status,
		arg.Summary,
		arg.Error,
		arg.ID,
	)
	var i EvalRun
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.TeamID,
		&i.Kind,
		&i.Trigger,
		&i.Status,
		&i.StartedBy,
		&i.Config,
		&i.Summary,
		&i.Total,
		&i.Done,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getEvalCase = `-- name: GetEvalCase :one
SELECT id, set_id, question, expected, must_mention, note, created_by, revision, created_at, updated_at FROM eval_cases WHERE id = $1 AND set_id = $2
`

type GetEvalCaseParams struct {
	ID    uuid.UUID
	SetID uuid.UUID
}

func (q *Queries) GetEvalCase(ctx context.Context, arg GetEvalCaseParams) (EvalCase, error) {
	row := q.db.QueryRow(ctx, getEvalCase, arg.ID, arg.SetID)
	var i EvalCase
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Question,
		&i.Expected,
		&i.MustMention,
		&i.Note,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEvalRun = `-- name: GetEvalRun :one
SELECT id, set_id, team_id, kind, trigger, status, started_by, config, summary, total, done, error, created_at, started_at, finished_at FROM eval_runs WHERE id = $1 AND set_id = $2
`

type GetEvalRunParams struct {
	ID    uuid.UUID
	SetID uuid.UUID
}

func (q *Queries) GetEvalRun(ctx context.Context, arg GetEvalRunParams) (EvalRun, error) {
	row := q.db.QueryRow(ctx, getEvalRun, arg.ID, arg.SetID)
	var i EvalRun
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.TeamID,
		&i.Kind,
		&i.Trigger,
		&i.Status,
		&i.StartedBy,
		&i.Config,
		&i.Summary,
		&i.Total,
		&i.Done,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getEvalRunByID = `-- name: GetEvalRunByID :one
SELECT id, set_id, team_id, kind, trigger, status, started_by, config, summary, total, done, error, created_at, started_at, finished_at FROM eval_runs WHERE id = $1
`

func (q *Queries) GetEvalRunByID(ctx context.Context, id uuid.UUID) (EvalRun, error) {
	row := q.db.QueryRow(ctx, getEvalRunByID, id)
	var i EvalRun
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.TeamID,
		&i.Kind,
		&i.Trigger,
		&i.Status,
		&i.StartedBy,
		&i.Config,
		&i.Summary,
		&i.Total,
		&i.Done,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getEvalSet = `-- name: GetEvalSet :one
SELECT id, team_id, kb_id, agent_id, name, description, auto_run, created_by, revision, created_at, updated_at FROM eval_sets WHERE id = $1 AND team_id = $2
`

type GetEvalSetParams struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

func (q *Queries) GetEvalSet(ctx context.Context, arg GetEvalSetParams) (EvalSet, error) {
	row := q.db.QueryRow(ctx, getEvalSet, arg.ID, arg.TeamID)
	var i EvalSet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.KBID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.AutoRun,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEvalSetByID = `-- name: GetEvalSetByID :one
SELECT id, team_id, kb_id, agent_id, name, description, auto_run, created_by, revision, created_at, updated_at FROM eval_sets WHERE id = $1
`

func (q *Queries) GetEvalSetByID(ctx context.Context, id uuid.UUID) (EvalSet, error) {
	row := q.db.QueryRow(ctx, getEvalSetByID, id)
	var i EvalSet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.KBID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.AutoRun,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEvalSetView = `-- name: GetEvalSetView :one
SELECT s.id, s.team_id, s.kb_id, s.agent_id, s.name, s.description, s.auto_run, s.created_by, s.revision, s.created_at, s.updated_at, coalesce(kb.name, ag.name, '')::text AS target_name,
       (SELECT count(*) FROM eval_cases c WHERE c.set_id = s.id)::bigint AS question_count,
       lr.id AS last_run_id, lr.kind AS last_run_kind, lr.status AS last_run_status, lr.summary AS last_run_summary,
       lr.created_at AS last_run_at
FROM eval_sets s
LEFT JOIN knowledge_bases kb ON kb.id = s.kb_id
LEFT JOIN agents ag ON ag.id = s.agent_id
LEFT JOIN eval_runs lr ON lr.id = (
    SELECT r.id FROM eval_runs r WHERE r.set_id = s.id ORDER BY r.created_at DESC, r.id DESC LIMIT 1
)
WHERE s.id = $1 AND s.team_id = $2
`

type GetEvalSetViewParams struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

type GetEvalSetViewRow struct {
	EvalSet        EvalSet
	TargetName     string
	QuestionCount  int64
	LastRunID      uuid.NullUUID
	LastRunKind    *string
	LastRunStatus  *string
	LastRunSummary json.RawMessage
	LastRunAt      *time.Time
}

func (q *Queries) GetEvalSetView(ctx context.Context, arg GetEvalSetViewParams) (GetEvalSetViewRow, error) {
	row := q.db.QueryRow(ctx, getEvalSetView, arg.ID, arg.TeamID)
	var i GetEvalSetViewRow
	err := row.Scan(
		&i.EvalSet.ID,
		&i.EvalSet.TeamID,
		&i.EvalSet.KBID,
		&i.EvalSet.AgentID,
		&i.EvalSet.Name,
		&i.EvalSet.Description,
		&i.EvalSet.AutoRun,
		&i.EvalSet.CreatedBy,
		&i.EvalSet.Revision,
		&i.EvalSet.CreatedAt,
		&i.EvalSet.UpdatedAt,
		&i.TargetName,
		&i.QuestionCount,
		&i.LastRunID,
		&i.LastRunKind,
		&i.LastRunStatus,
		&i.LastRunSummary,
		&i.LastRunAt,
	)
	return i, err
}

const getEvaluationSettings = `-- name: GetEvaluationSettings :one


SELECT singleton, enabled, revision, updated_by, updated_at FROM evaluation_settings
`

// Evaluation sets, questions, runs and results (migrations/00034_evaluations.sql,
// docs/evaluations.md).
// ---- the platform switch ------------------------------------------------------
func (q *Queries) GetEvaluationSettings(ctx context.Context) (EvaluationSetting, error) {
	row := q.db.QueryRow(ctx, getEvaluationSettings)
	var i EvaluationSetting
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvalCase = `-- name: InsertEvalCase :one

INSERT INTO eval_cases (set_id, question, expected, must_mention, note, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, clock_timestamp(), clock_timestamp())
RETURNING id, set_id, question, expected, must_mention, note, created_by, revision, created_at, updated_at
`

type InsertEvalCaseParams struct {
	SetID       uuid.UUID
	Question    string
	Expected    json.RawMessage
	MustMention []string
	Note        string
	CreatedBy   uuid.NullUUID
}

// ---- questions ----------------------------------------------------------------------
// The clock time keeps an import's questions in file order.
func (q *Queries) InsertEvalCase(ctx context.Context, arg InsertEvalCaseParams) (EvalCase, error) {
	row := q.db.QueryRow(ctx, insertEvalCase,
		arg.SetID,
		arg.Question,
		arg.Expected,
		arg.MustMention,
		arg.Note,
		arg.CreatedBy,
	)
	var i EvalCase
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Question,
		&i.Expected,
		&i.MustMention,
		&i.Note,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEvalResult = `-- name: InsertEvalResult :exec

INSERT INTO eval_results (run_id, case_id, question, status, rank, hits, answer, scores, error, latency_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT ON CONSTRAINT eval_results_run_case_key DO NOTHING
`

type InsertEvalResultParams struct {
	RunID     uuid.UUID
	CaseID    uuid.NullUUID
	Question  string
	Status    string
	Rank      *int32
	Hits      json.RawMessage
	Answer    *string
	Scores    json.RawMessage
	Error     string
	LatencyMs int32
}

// ---- results ------------------------------------------------------------------------------
func (q *Queries) InsertEvalResult(ctx context.Context, arg InsertEvalResultParams) error {
	_, err := q.db.Exec(ctx, insertEvalResult,
		arg.RunID,
		arg.CaseID,
		arg.Question,
		arg.Status,
		arg.Rank,
		arg.Hits,
		arg.Answer,
		arg.Scores,
		arg.Error,
		arg.LatencyMs,
	)
	return err
}

const insertEvalRun = `-- name: InsertEvalRun :one

INSERT INTO eval_runs (set_id, team_id, kind, trigger, started_by, config, total)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, set_id, team_id, kind, trigger, status, started_by, config, summary, total, done, error, created_at, started_at, finished_at
`

type InsertEvalRunParams struct {
	SetID     uuid.UUID
	TeamID    uuid.UUID
	Kind      string
	Trigger   string
	StartedBy uuid.NullUUID
	Config    json.RawMessage
	Total     int32
}

// ---- runs ---------------------------------------------------------------------------------
func (q *Queries) InsertEvalRun(ctx context.Context, arg InsertEvalRunParams) (EvalRun, error) {
	row := q.db.QueryRow(ctx, insertEvalRun,
		arg.SetID,
		arg.TeamID,
		arg.Kind,
		arg.Trigger,
		arg.StartedBy,
		arg.Config,
		arg.Total,
	)
	var i EvalRun
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.TeamID,
		&i.Kind,
		&i.Trigger,
		&i.Status,
		&i.StartedBy,
		&i.Config,
		&i.Summary,
		&i.Total,
		&i.Done,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertEvalSet = `-- name: InsertEvalSet :one

INSERT INTO eval_sets (team_id, kb_id, agent_id, name, description, auto_run, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, team_id, kb_id, agent_id, name, description, auto_run, created_by, revision, created_at, updated_at
`

type InsertEvalSetParams struct {
	TeamID      uuid.UUID
	KBID        uuid.NullUUID
	AgentID     uuid.NullUUID
	Name        string
	Description string
	AutoRun     bool
	CreatedBy   uuid.NullUUID
}

// ---- sets -------------------------------------------------------------------------
func (q *Queries) InsertEvalSet(ctx context.Context, arg InsertEvalSetParams) (EvalSet, error) {
	row := q.db.QueryRow(ctx, insertEvalSet,
		arg.TeamID,
		arg.KBID,
		arg.AgentID,
		arg.Name,
		arg.Description,
		arg.AutoRun,
		arg.CreatedBy,
	)
	var i EvalSet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.KBID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.AutoRun,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCaseResults = `-- name: ListCaseResults :many
SELECT r.id, r.run_id, r.case_id, r.question, r.status, r.rank, r.hits, r.answer, r.scores, r.error, r.latency_ms, r.created_at, run.kind AS run_kind, run.trigger AS run_trigger, run.created_at AS run_created_at, run.config AS run_config
FROM eval_results r
JOIN eval_runs run ON run.id = r.run_id
WHERE r.case_id = $1
ORDER BY run.created_at DESC, run.id DESC
LIMIT $2
`

type ListCaseResultsParams struct {
	CaseID uuid.NullUUID
	Lim    int32
}

type ListCaseResultsRow struct {
	EvalResult   EvalResult
	RunKind      string
	RunTrigger   string
	RunCreatedAt time.Time
	RunConfig    json.RawMessage
}

// A question's results in the latest runs, newest first.
func (q *Queries) ListCaseResults(ctx context.Context, arg ListCaseResultsParams) ([]ListCaseResultsRow, error) {
	rows, err := q.db.Query(ctx, listCaseResults, arg.CaseID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCaseResultsRow{}
	for rows.Next() {
		var i ListCaseResultsRow
		if err := rows.Scan(
			&i.EvalResult.ID,
			&i.EvalResult.RunID,
			&i.EvalResult.CaseID,
			&i.EvalResult.Question,
			&i.EvalResult.Status,
			&i.EvalResult.Rank,
			&i.EvalResult.Hits,
			&i.EvalResult.Answer,
			&i.EvalResult.Scores,
			&i.EvalResult.Error,
			&i.EvalResult.LatencyMs,
			&i.EvalResult.CreatedAt,
			&i.RunKind,
			&i.RunTrigger,
			&i.RunCreatedAt,
			&i.RunConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvalCases = `-- name: ListEvalCases :many
SELECT id, set_id, question, expected, must_mention, note, created_by, revision, created_at, updated_at FROM eval_cases WHERE set_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListEvalCases(ctx context.Context, setID uuid.UUID) ([]EvalCase, error) {
	rows, err := q.db.Query(ctx, listEvalCases, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvalCase{}
	for rows.Next() {
		var i EvalCase
		if err := rows.Scan(
			&i.ID,
			&i.SetID,
			&i.Question,
			&i.Expected,
			&i.MustMention,
			&i.Note,
			&i.CreatedBy,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvalResults = `-- name: ListEvalResults :many
SELECT r.id, r.run_id, r.case_id, r.question, r.status, r.rank, r.hits, r.answer, r.scores, r.error, r.latency_ms, r.created_at FROM eval_results r
LEFT JOIN eval_cases c ON c.id = r.case_id
WHERE r.run_id = $1
ORDER BY c.created_at NULLS LAST, r.created_at, r.id
`

func (q *Queries) ListEvalResults(ctx context.Context, runID uuid.UUID) ([]EvalResult, error) {
	rows, err := q.db.Query(ctx, listEvalResults, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvalResult{}
	for rows.Next() {
		var i EvalResult
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.CaseID,
			&i.Question,
			&i.Status,
			&i.Rank,
			&i.Hits,
			&i.Answer,
			&i.Scores,
			&i.Error,
			&i.LatencyMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvalRuns = `-- name: ListEvalRuns :many
SELECT id, set_id, team_id, kind, trigger, status, started_by, config, summary, total, done, error, created_at, started_at, finished_at FROM eval_runs WHERE set_id = $1 ORDER BY created_at DESC, id DESC LIMIT $2
`

type ListEvalRunsParams struct {
	SetID uuid.UUID
	Lim   int32
}

func (q *Queries) ListEvalRuns(ctx context.Context, arg ListEvalRunsParams) ([]EvalRun, error) {
	rows, err := q.db.Query(ctx, listEvalRuns, arg.SetID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvalRun{}
	for rows.Next() {
		var i EvalRun
		if err := rows.Scan(
			&i.ID,
			&i.SetID,
			&i.TeamID,
			&i.Kind,
			&i.Trigger,
			&i.Status,
			&i.StartedBy,
			&i.Config,
			&i.Summary,
			&i.Total,
			&i.Done,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvalSetViews = `-- name: ListEvalSetViews :many
SELECT s.id, s.team_id, s.kb_id, s.agent_id, s.name, s.description, s.auto_run, s.created_by, s.revision, s.created_at, s.updated_at, coalesce(kb.name, ag.name, '')::text AS target_name,
       (SELECT count(*) FROM eval_cases c WHERE c.set_id = s.id)::bigint AS question_count,
       lr.id AS last_run_id, lr.kind AS last_run_kind, lr.status AS last_run_status, lr.summary AS last_run_summary,
       lr.created_at AS last_run_at
FROM eval_sets s
LEFT JOIN knowledge_bases kb ON kb.id = s.kb_id
LEFT JOIN agents ag ON ag.id = s.agent_id
LEFT JOIN eval_runs lr ON lr.id = (
    SELECT r.id FROM eval_runs r WHERE r.set_id = s.id ORDER BY r.created_at DESC, r.id DESC LIMIT 1
)
WHERE s.team_id = $1
  AND ($2::uuid IS NULL OR s.kb_id = $2::uuid)
  AND ($3::uuid IS NULL OR s.agent_id = $3::uuid)
ORDER BY lower(s.name), s.id
`

type ListEvalSetViewsParams struct {
	TeamID  uuid.UUID
	KBID    uuid.NullUUID
	AgentID uuid.NullUUID
}

type ListEvalSetViewsRow struct {
	EvalSet        EvalSet
	TargetName     string
	QuestionCount  int64
	LastRunID      uuid.NullUUID
	LastRunKind    *string
	LastRunStatus  *string
	LastRunSummary json.RawMessage
	LastRunAt      *time.Time
}

// A team's sets with their target's name, question count and latest
// finished run (optionally one knowledge base's or agent's).
func (q *Queries) ListEvalSetViews(ctx context.Context, arg ListEvalSetViewsParams) ([]ListEvalSetViewsRow, error) {
	rows, err := q.db.Query(ctx, listEvalSetViews, arg.TeamID, arg.KBID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEvalSetViewsRow{}
	for rows.Next() {
		var i ListEvalSetViewsRow
		if err := rows.Scan(
			&i.EvalSet.ID,
			&i.EvalSet.TeamID,
			&i.EvalSet.KBID,
			&i.EvalSet.AgentID,
			&i.EvalSet.Name,
			&i.EvalSet.Description,
			&i.EvalSet.AutoRun,
			&i.EvalSet.CreatedBy,
			&i.EvalSet.Revision,
			&i.EvalSet.CreatedAt,
			&i.EvalSet.UpdatedAt,
			&i.TargetName,
			&i.QuestionCount,
			&i.LastRunID,
			&i.LastRunKind,
			&i.LastRunStatus,
			&i.LastRunSummary,
			&i.LastRunAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEvalCase = `-- name: LockEvalCase :one
SELECT id, set_id, question, expected, must_mention, note, created_by, revision, created_at, updated_at FROM eval_cases WHERE id = $1 AND set_id = $2 FOR UPDATE
`

type LockEvalCaseParams struct {
	ID    uuid.UUID
	SetID uuid.UUID
}

func (q *Queries) LockEvalCase(ctx context.Context, arg LockEvalCaseParams) (EvalCase, error) {
	row := q.db.QueryRow(ctx, lockEvalCase, arg.ID, arg.SetID)
	var i EvalCase
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Question,
		&i.Expected,
		&i.MustMention,
		&i.Note,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockEvalRun = `-- name: LockEvalRun :one
SELECT id, set_id, team_id, kind, trigger, status, started_by, config, summary, total, done, error, created_at, started_at, finished_at FROM eval_runs WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockEvalRun(ctx context.Context, id uuid.UUID) (EvalRun, error) {
	row := q.db.QueryRow(ctx, lockEvalRun, id)
	var i EvalRun
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.TeamID,
		&i.Kind,
		&i.Trigger,
		&i.Status,
		&i.StartedBy,
		&i.Config,
		&i.Summary,
		&i.Total,
		&i.Done,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const lockEvalSet = `-- name: LockEvalSet :one
SELECT id, team_id, kb_id, agent_id, name, description, auto_run, created_by, revision, created_at, updated_at FROM eval_sets WHERE id = $1 AND team_id = $2 FOR UPDATE
`

type LockEvalSetParams struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

func (q *Queries) LockEvalSet(ctx context.Context, arg LockEvalSetParams) (EvalSet, error) {
	row := q.db.QueryRow(ctx, lockEvalSet, arg.ID, arg.TeamID)
	var i EvalSet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.KBID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.AutoRun,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockEvaluationSettings = `-- name: LockEvaluationSettings :one
SELECT singleton, enabled, revision, updated_by, updated_at FROM evaluation_settings FOR UPDATE
`

func (q *Queries) LockEvaluationSettings(ctx context.Context) (EvaluationSetting, error) {
	row := q.db.QueryRow(ctx, lockEvaluationSettings)
	var i EvaluationSetting
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const markEvalRunRunning = `-- name: MarkEvalRunRunning :exec
UPDATE eval_runs SET status = 'running', started_at = coalesce(started_at, now()) WHERE id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) MarkEvalRunRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEvalRunRunning, id)
	return err
}

const matchExpectedDocument = `-- name: MatchExpectedDocument :many
SELECT d.id, d.source_id, d.title, d.filename, d.url FROM documents d
WHERE d.source_id = ANY($1::uuid[])
  AND (d.id = ANY($2::uuid[])
       OR (d.url <> '' AND rtrim(d.url, '/') = ANY($3::text[]))
       OR (d.url <> '' AND EXISTS (SELECT 1 FROM unnest($4::text[]) p WHERE starts_with(d.url, p)))
       OR (d.filename <> '' AND lower(d.filename) = ANY($5::text[])))
ORDER BY d.created_at, d.id
LIMIT 1
`

type MatchExpectedDocumentParams struct {
	SourceIds   []uuid.UUID
	DocumentIds []uuid.UUID
	Urls        []string
	UrlPrefixes []string
	Filenames   []string
}

type MatchExpectedDocumentRow struct {
	ID       uuid.UUID
	SourceID uuid.UUID
	Title    string
	Filename string
	URL      string
}

// The first document of the sources that matches expected documents (the
// conditions of ExpectedDocumentExists), for a question's diagnosis: one
// row or none.
func (q *Queries) MatchExpectedDocument(ctx context.Context, arg MatchExpectedDocumentParams) ([]MatchExpectedDocumentRow, error) {
	rows, err := q.db.Query(ctx, matchExpectedDocument,
		arg.SourceIds,
		arg.DocumentIds,
		arg.Urls,
		arg.UrlPrefixes,
		arg.Filenames,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchExpectedDocumentRow{}
	for rows.Next() {
		var i MatchExpectedDocumentRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Filename,
			&i.URL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nightlyEvalSets = `-- name: NightlyEvalSets :many
SELECT s.id, s.team_id, s.kb_id, s.agent_id, s.name, s.description, s.auto_run, s.created_by, s.revision, s.created_at, s.updated_at FROM eval_sets s
JOIN teams t ON t.id = s.team_id AND t.status = 'active'
LEFT JOIN agents a ON a.id = s.agent_id
WHERE s.auto_run
  AND (s.agent_id IS NULL OR a.deleted_at IS NULL)
  AND NOT EXISTS (SELECT 1 FROM eval_runs r WHERE r.set_id = s.id AND r.trigger = 'nightly' AND r.created_at >= $1::timestamptz)
  AND EXISTS (
      SELECT 1 FROM kb_sources ks
      WHERE (ks.kb_id = s.kb_id
             OR ks.kb_id IN (SELECT vk.kb_id FROM agent_version_kbs vk WHERE vk.version_id = a.published_version_id))
        AND (EXISTS (SELECT 1 FROM documents d WHERE d.source_id = ks.source_id AND d.updated_at >= $2::timestamptz)
             OR EXISTS (SELECT 1 FROM deleted_files f WHERE f.source_id = ks.source_id AND f.deleted_at >= $2::timestamptz)))
ORDER BY s.created_at, s.id
`

type NightlyEvalSetsParams struct {
	RanSince     time.Time
	ChangedSince time.Time
}

// Sets with automatic runs whose knowledge bases (the set's, or the
// published agent's) had documents added, changed or deleted since
// @changed_since, and no nightly run since @ran_since. Archived teams and
// deleted agents are left out.
func (q *Queries) NightlyEvalSets(ctx context.Context, arg NightlyEvalSetsParams) ([]EvalSet, error) {
	rows, err := q.db.Query(ctx, nightlyEvalSets, arg.RanSince, arg.ChangedSince)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvalSet{}
	for rows.Next() {
		var i EvalSet
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.KBID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.AutoRun,
			&i.CreatedBy,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingEvalCases = `-- name: PendingEvalCases :many
SELECT c.id, c.set_id, c.question, c.expected, c.must_mention, c.note, c.created_by, c.revision, c.created_at, c.updated_at FROM eval_cases c
WHERE c.set_id = $1 AND c.created_at <= $2::timestamptz
  AND NOT EXISTS (SELECT 1 FROM eval_results r WHERE r.run_id = $3 AND r.case_id = c.id)
ORDER BY c.created_at, c.id
LIMIT $4
`

type PendingEvalCasesParams struct {
	SetID  uuid.UUID
	Before time.Time
	RunID  uuid.UUID
	Lim    int32
}

// The questions a run still has to check: those that existed when it was
// started and have no result yet (a resumed job skips the rest).
func (q *Queries) PendingEvalCases(ctx context.Context, arg PendingEvalCasesParams) ([]EvalCase, error) {
	rows, err := q.db.Query(ctx, pendingEvalCases,
		arg.SetID,
		arg.Before,
		arg.RunID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EvalCase{}
	for rows.Next() {
		var i EvalCase
		if err := rows.Scan(
			&i.ID,
			&i.SetID,
			&i.Question,
			&i.Expected,
			&i.MustMention,
			&i.Note,
			&i.CreatedBy,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const phraseInSources = `-- name: PhraseInSources :one
WITH q AS (SELECT phraseto_tsquery('english', $2::text) AS query)
SELECT (numnode(q.query) = 0 OR EXISTS (
    SELECT 1 FROM chunks c WHERE c.source_id = ANY($1::uuid[]) AND c.content_tsv @@ q.query
))::boolean AS found
FROM q
`

type PhraseInSourcesParams struct {
	SourceIds []uuid.UUID
	Phrase    string
}

// Whether a must-mention phrase's words (stemmed, in order, as
// phraseto_tsquery reads them) appear in a passage of the sources, for the
// question form's warning. A phrase of stopwords only has no words to look
// for and counts as found.
func (q *Queries) PhraseInSources(ctx context.Context, arg PhraseInSourcesParams) (bool, error) {
	row := q.db.QueryRow(ctx, phraseInSources, arg.SourceIds, arg.Phrase)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const previousCompletedRun = `-- name: PreviousCompletedRun :one
SELECT id, set_id, team_id, kind, trigger, status, started_by, config, summary, total, done, error, created_at, started_at, finished_at FROM eval_runs
WHERE set_id = $1 AND kind = $2 AND status = 'completed' AND created_at < $3::timestamptz
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type PreviousCompletedRunParams struct {
	SetID  uuid.UUID
	Kind   string
	Before time.Time
}

// The latest completed run of a kind before @before, for regression checks.
func (q *Queries) PreviousCompletedRun(ctx context.Context, arg PreviousCompletedRunParams) (EvalRun, error) {
	row := q.db.QueryRow(ctx, previousCompletedRun, arg.SetID, arg.Kind, arg.Before)
	var i EvalRun
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.TeamID,
		&i.Kind,
		&i.Trigger,
		&i.Status,
		&i.StartedBy,
		&i.Config,
		&i.Summary,
		&i.Total,
		&i.Done,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const searchEvalDocuments = `-- name: SearchEvalDocuments :many
SELECT d.id, d.title, d.filename, d.url, s.name AS source_name
FROM documents d
JOIN data_sources s ON s.id = d.source_id
WHERE d.source_id = ANY($1::uuid[])
  AND ($2::text = '' OR d.title ILIKE $2::text OR d.filename ILIKE $2::text OR d.url ILIKE $2::text)
ORDER BY lower(coalesce(nullif(d.title, ''), nullif(d.filename, ''), d.url)), d.id
LIMIT $3
`

type SearchEvalDocumentsParams struct {
	SourceIds []uuid.UUID
	Pattern   string
	Lim       int32
}

type SearchEvalDocumentsRow struct {
	ID         uuid.UUID
	Title      string
	Filename   string
	URL        string
	SourceName string
}

// Documents of the sources whose title, filename or URL matches, for the
// expected-documents picker.
func (q *Queries) SearchEvalDocuments(ctx context.Context, arg SearchEvalDocumentsParams) ([]SearchEvalDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchEvalDocuments, arg.SourceIds, arg.Pattern, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEvalDocumentsRow{}
	for rows.Next() {
		var i SearchEvalDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.URL,
			&i.SourceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEvalSets = `-- name: SearchEvalSets :many

SELECT s.id, s.name, s.kb_id, s.agent_id, t.slug AS team_slug, t.name AS team_name,
       (CASE WHEN s.name ILIKE $1::text THEN 0 WHEN s.name ~* $2::text THEN 1 ELSE 2 END)::int AS rank
FROM eval_sets s
JOIN team_members tm ON tm.team_id = s.team_id AND tm.user_id = $3::uuid AND tm.role IN ('owner', 'admin', 'editor')
JOIN teams t ON t.id = s.team_id
WHERE s.name ILIKE $4::text
ORDER BY rank, length(s.name), lower(s.name), s.id
LIMIT $5
`

type SearchEvalSetsParams struct {
	Prefix   string
	Word     string
	UserID   uuid.UUID
	Contains string
	Lim      int32
}

type SearchEvalSetsRow struct {
	ID       uuid.UUID
	Name     string
	KBID     uuid.NullUUID
	AgentID  uuid.NullUUID
	TeamSlug string
	TeamName string
	Rank     int32
}

// ---- search (⌘K) --------------------------------------------------------------------------
// Evaluation sets of the teams where the user is an editor or above.
func (q *Queries) SearchEvalSets(ctx context.Context, arg SearchEvalSetsParams) ([]SearchEvalSetsRow, error) {
	rows, err := q.db.Query(ctx, searchEvalSets,
		arg.Prefix,
		arg.Word,
		arg.UserID,
		arg.Contains,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEvalSetsRow{}
	for rows.Next() {
		var i SearchEvalSetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KBID,
			&i.AgentID,
			&i.TeamSlug,
			&i.TeamName,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEvalRunConfig = `-- name: SetEvalRunConfig :exec
UPDATE eval_runs SET config = $1 WHERE id = $2
`

type SetEvalRunConfigParams struct {
	Config json.RawMessage
	ID     uuid.UUID
}

func (q *Queries) SetEvalRunConfig(ctx context.Context, arg SetEvalRunConfigParams) error {
	_, err := q.db.Exec(ctx, setEvalRunConfig, arg.Config, arg.ID)
	return err
}

const setEvalRunProgress = `-- name: SetEvalRunProgress :exec
UPDATE eval_runs SET done = (SELECT count(*) FROM eval_results r WHERE r.run_id = $1) WHERE id = $1
`

func (q *Queries) SetEvalRunProgress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setEvalRunProgress, id)
	return err
}

const setEvaluationsEnabled = `-- name: SetEvaluationsEnabled :one
UPDATE evaluation_settings
SET enabled = $1, revision = revision + 1, updated_by = $2, updated_at = now()
RETURNING singleton, enabled, revision, updated_by, updated_at
`

type SetEvaluationsEnabledParams struct {
	Enabled   bool
	UpdatedBy uuid.NullUUID
}

func (q *Queries) SetEvaluationsEnabled(ctx context.Context, arg SetEvaluationsEnabledParams) (EvaluationSetting, error) {
	row := q.db.QueryRow(ctx, setEvaluationsEnabled, arg.Enabled, arg.UpdatedBy)
	var i EvaluationSetting
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEvalCase = `-- name: UpdateEvalCase :one
UPDATE eval_cases
SET question = $1, expected = $2, must_mention = $3, note = $4,
    revision = revision + 1, updated_at = now()
WHERE id = $5
RETURNING id, set_id, question, expected, must_mention, note, created_by, revision, created_at, updated_at
`

type UpdateEvalCaseParams struct {
	Question    string
	Expected    json.RawMessage
	MustMention []string
	Note        string
	ID          uuid.UUID
}

func (q *Queries) UpdateEvalCase(ctx context.Context, arg UpdateEvalCaseParams) (EvalCase, error) {
	row := q.db.QueryRow(ctx, updateEvalCase,
		arg.Question,
		arg.Expected,
		arg.MustMention,
		arg.Note,
		arg.ID,
	)
	var i EvalCase
	err := row.Scan(
		&i.ID,
		&i.SetID,
		&i.Question,
		&i.Expected,
		&i.MustMention,
		&i.Note,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEvalSet = `-- name: UpdateEvalSet :one
UPDATE eval_sets
SET name = $1, description = $2, auto_run = $3, revision = revision + 1, updated_at = now()
WHERE id = $4
RETURNING id, team_id, kb_id, agent_id, name, description, auto_run, created_by, revision, created_at, updated_at
`

type UpdateEvalSetParams struct {
	Name        string
	Description string
	AutoRun     bool
	ID          uuid.UUID
}

func (q *Queries) UpdateEvalSet(ctx context.Context, arg UpdateEvalSetParams) (EvalSet, error) {
	row := q.db.QueryRow(ctx, updateEvalSet,
		arg.Name,
		arg.Description,
		arg.AutoRun,
		arg.ID,
	)
	var i EvalSet
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.KBID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.AutoRun,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
