// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const healthCheckHistory = `-- name: HealthCheckHistory :many
SELECT id, subject_kind, subject_id, status, latency_ms, error_class, http_status, message, trigger, triggered_by, checked_at, status_since FROM health_checks
WHERE subject_kind = $1 AND subject_id = $2
ORDER BY checked_at DESC, id DESC
LIMIT $3
`

type HealthCheckHistoryParams struct {
	SubjectKind string
	SubjectID   uuid.UUID
	MaxRows     int32
}

// A subject's checks, newest first.
func (q *Queries) HealthCheckHistory(ctx context.Context, arg HealthCheckHistoryParams) ([]HealthCheck, error) {
	rows, err := q.db.Query(ctx, healthCheckHistory, arg.SubjectKind, arg.SubjectID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthCheck{}
	for rows.Next() {
		var i HealthCheck
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Status,
			&i.LatencyMs,
			&i.ErrorClass,
			&i.HttpStatus,
			&i.Message,
			&i.Trigger,
			&i.TriggeredBy,
			&i.CheckedAt,
			&i.StatusSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const healthSubjectExists = `-- name: HealthSubjectExists :one
SELECT EXISTS (SELECT 1 FROM health_subjects WHERE subject_kind = $1 AND subject_id = $2)
`

type HealthSubjectExistsParams struct {
	SubjectKind string
	SubjectID   uuid.UUID
}

func (q *Queries) HealthSubjectExists(ctx context.Context, arg HealthSubjectExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, healthSubjectExists, arg.SubjectKind, arg.SubjectID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertHealthCheck = `-- name: InsertHealthCheck :one
INSERT INTO health_checks (subject_kind, subject_id, status, latency_ms, error_class, http_status, message, trigger, triggered_by, checked_at, status_since)
SELECT $1, $2, $3, $4, $5, $6::integer, $7, $8, $9, $10::timestamptz,
       COALESCE((SELECT CASE WHEN p.status = $3 THEN p.status_since END
                 FROM health_checks p
                 WHERE p.subject_kind = $1 AND p.subject_id = $2
                 ORDER BY p.checked_at DESC, p.id DESC
                 LIMIT 1), $10::timestamptz)
RETURNING id, subject_kind, subject_id, status, latency_ms, error_class, http_status, message, trigger, triggered_by, checked_at, status_since
`

type InsertHealthCheckParams struct {
	SubjectKind string
	SubjectID   uuid.UUID
	Status      string
	LatencyMs   int32
	ErrorClass  *string
	HttpStatus  *int32
	Message     string
	Trigger     string
	TriggeredBy uuid.NullUUID
	CheckedAt   time.Time
}

// status_since carries the current streak forward: the previous check's
// status_since when the status is unchanged, otherwise this check's time.
func (q *Queries) InsertHealthCheck(ctx context.Context, arg InsertHealthCheckParams) (HealthCheck, error) {
	row := q.db.QueryRow(ctx, insertHealthCheck,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Status,
		arg.LatencyMs,
		arg.ErrorClass,
		arg.HttpStatus,
		arg.Message,
		arg.Trigger,
		arg.TriggeredBy,
		arg.CheckedAt,
	)
	var i HealthCheck
	err := row.Scan(
		&i.ID,
		&i.SubjectKind,
		&i.SubjectID,
		&i.Status,
		&i.LatencyMs,
		&i.ErrorClass,
		&i.HttpStatus,
		&i.Message,
		&i.Trigger,
		&i.TriggeredBy,
		&i.CheckedAt,
		&i.StatusSince,
	)
	return i, err
}

const latestHealthChecks = `-- name: LatestHealthChecks :many
SELECT s.name AS subject_name, s.enabled AS subject_enabled, h.id, h.subject_kind, h.subject_id, h.status, h.latency_ms, h.error_class, h.http_status, h.message, h.trigger, h.triggered_by, h.checked_at, h.status_since
FROM health_subjects s
CROSS JOIN LATERAL (
    SELECT id, subject_kind, subject_id, status, latency_ms, error_class, http_status, message, trigger, triggered_by, checked_at, status_since FROM health_checks c
    WHERE c.subject_kind = s.subject_kind AND c.subject_id = s.subject_id
    ORDER BY c.checked_at DESC, c.id DESC
    LIMIT 1
) h
WHERE $1::text IS NULL OR s.subject_kind = $1::text
ORDER BY s.subject_kind, s.name, s.subject_id
`

type LatestHealthChecksRow struct {
	SubjectName    string
	SubjectEnabled bool
	ID             int64
	SubjectKind    string
	SubjectID      uuid.UUID
	Status         string
	LatencyMs      int32
	ErrorClass     *string
	HttpStatus     *int32
	Message        string
	Trigger        string
	TriggeredBy    uuid.NullUUID
	CheckedAt      time.Time
	StatusSince    time.Time
}

// The latest check of every existing subject (subjects never checked are
// absent), with the subject's name and whether it is enabled.
func (q *Queries) LatestHealthChecks(ctx context.Context, kind *string) ([]LatestHealthChecksRow, error) {
	rows, err := q.db.Query(ctx, latestHealthChecks, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestHealthChecksRow{}
	for rows.Next() {
		var i LatestHealthChecksRow
		if err := rows.Scan(
			&i.SubjectName,
			&i.SubjectEnabled,
			&i.ID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.Status,
			&i.LatencyMs,
			&i.ErrorClass,
			&i.HttpStatus,
			&i.Message,
			&i.Trigger,
			&i.TriggeredBy,
			&i.CheckedAt,
			&i.StatusSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneHealthChecks = `-- name: PruneHealthChecks :execrows
DELETE FROM health_checks h
WHERE NOT EXISTS (SELECT 1 FROM health_subjects s WHERE s.subject_kind = h.subject_kind AND s.subject_id = h.subject_id)
   OR (h.checked_at < $1::timestamptz
       AND EXISTS (SELECT 1 FROM health_checks n
                   WHERE n.subject_kind = h.subject_kind AND n.subject_id = h.subject_id
                     AND (n.checked_at, n.id) > (h.checked_at, h.id)))
`

// Removes checks older than the cutoff, except each subject's latest, and
// every check of a subject that no longer exists.
func (q *Queries) PruneHealthChecks(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneHealthChecks, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
