// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_digest, csrf_token, user_agent, client_ip, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateSessionParams struct {
	UserID      uuid.UUID
	TokenDigest string
	CSRFToken   string
	UserAgent   string
	ClientIP    string
	ExpiresAt   time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenDigest,
		arg.CSRFToken,
		arg.UserAgent,
		arg.ClientIP,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionByDigest = `-- name: DeleteSessionByDigest :exec
DELETE FROM sessions WHERE token_digest = $1
`

func (q *Queries) DeleteSessionByDigest(ctx context.Context, tokenDigest string) error {
	_, err := q.db.Exec(ctx, deleteSessionByDigest, tokenDigest)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT sessions.id, sessions.user_id, sessions.token_digest, sessions.csrf_token, sessions.user_agent, sessions.client_ip, sessions.created_at, sessions.expires_at, users.id, users.oidc_issuer, users.oidc_subject, users.email, users.display_name, users.platform_role, users.status, users.claims, users.created_at, users.updated_at, users.last_login_at, users.revision
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_digest = $1
  AND sessions.expires_at > now()
`

type GetSessionUserRow struct {
	Session Session
	User    User
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenDigest string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenDigest)
	var i GetSessionUserRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenDigest,
		&i.Session.CSRFToken,
		&i.Session.UserAgent,
		&i.Session.ClientIP,
		&i.Session.CreatedAt,
		&i.Session.ExpiresAt,
		&i.User.ID,
		&i.User.OIDCIssuer,
		&i.User.OIDCSubject,
		&i.User.Email,
		&i.User.DisplayName,
		&i.User.PlatformRole,
		&i.User.Status,
		&i.User.Claims,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.LastLoginAt,
		&i.User.Revision,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, oidc_issuer, oidc_subject, email, display_name, platform_role, status, claims, created_at, updated_at, last_login_at, revision FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OIDCIssuer,
		&i.OIDCSubject,
		&i.Email,
		&i.DisplayName,
		&i.PlatformRole,
		&i.Status,
		&i.Claims,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Revision,
	)
	return i, err
}

const insertBootstrapMarker = `-- name: InsertBootstrapMarker :execrows
INSERT INTO platform_bootstrap (oidc_issuer, oidc_subject)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertBootstrapMarkerParams struct {
	OIDCIssuer  string
	OIDCSubject string
}

func (q *Queries) InsertBootstrapMarker(ctx context.Context, arg InsertBootstrapMarkerParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBootstrapMarker, arg.OIDCIssuer, arg.OIDCSubject)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPlatformRole = `-- name: SetPlatformRole :one
UPDATE users
SET platform_role = $1, updated_at = now()
WHERE id = $2
RETURNING id, oidc_issuer, oidc_subject, email, display_name, platform_role, status, claims, created_at, updated_at, last_login_at, revision
`

type SetPlatformRoleParams struct {
	PlatformRole string
	ID           uuid.UUID
}

func (q *Queries) SetPlatformRole(ctx context.Context, arg SetPlatformRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, setPlatformRole, arg.PlatformRole, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OIDCIssuer,
		&i.OIDCSubject,
		&i.Email,
		&i.DisplayName,
		&i.PlatformRole,
		&i.Status,
		&i.Claims,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Revision,
	)
	return i, err
}

const upsertLoginUser = `-- name: UpsertLoginUser :one
INSERT INTO users (oidc_issuer, oidc_subject, email, display_name, claims, last_login_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (oidc_issuer, oidc_subject) DO UPDATE
SET email         = EXCLUDED.email,
    display_name  = EXCLUDED.display_name,
    claims        = EXCLUDED.claims,
    last_login_at = now(),
    updated_at    = now()
RETURNING id, oidc_issuer, oidc_subject, email, display_name, platform_role, status, claims, created_at, updated_at, last_login_at, revision
`

type UpsertLoginUserParams struct {
	OIDCIssuer  string
	OIDCSubject string
	Email       string
	DisplayName string
	Claims      json.RawMessage
}

func (q *Queries) UpsertLoginUser(ctx context.Context, arg UpsertLoginUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertLoginUser,
		arg.OIDCIssuer,
		arg.OIDCSubject,
		arg.Email,
		arg.DisplayName,
		arg.Claims,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OIDCIssuer,
		&i.OIDCSubject,
		&i.Email,
		&i.DisplayName,
		&i.PlatformRole,
		&i.Status,
		&i.Claims,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Revision,
	)
	return i, err
}
