// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kbs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const attachSource = `-- name: AttachSource :execrows
INSERT INTO kb_sources (kb_id, source_id, added_by) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AttachSourceParams struct {
	KBID     uuid.UUID
	SourceID uuid.UUID
	AddedBy  uuid.NullUUID
}

func (q *Queries) AttachSource(ctx context.Context, arg AttachSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachSource, arg.KBID, arg.SourceID, arg.AddedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteKB = `-- name: DeleteKB :exec
DELETE FROM knowledge_bases WHERE id = $1
`

func (q *Queries) DeleteKB(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteKB, id)
	return err
}

const detachSource = `-- name: DetachSource :execrows
DELETE FROM kb_sources WHERE kb_id = $1 AND source_id = $2
`

type DetachSourceParams struct {
	KBID     uuid.UUID
	SourceID uuid.UUID
}

func (q *Queries) DetachSource(ctx context.Context, arg DetachSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, detachSource, arg.KBID, arg.SourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getKB = `-- name: GetKB :one
SELECT id, team_id, name, description, embedding_profile_id, top_k, revision, created_by, created_at, updated_at, vector_weight, keyword_weight FROM knowledge_bases WHERE id = $1
`

func (q *Queries) GetKB(ctx context.Context, id uuid.UUID) (KnowledgeBase, error) {
	row := q.db.QueryRow(ctx, getKB, id)
	var i KnowledgeBase
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.EmbeddingProfileID,
		&i.TopK,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VectorWeight,
		&i.KeywordWeight,
	)
	return i, err
}

const insertKB = `-- name: InsertKB :one
INSERT INTO knowledge_bases (team_id, name, description, embedding_profile_id, top_k, vector_weight, keyword_weight, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, team_id, name, description, embedding_profile_id, top_k, revision, created_by, created_at, updated_at, vector_weight, keyword_weight
`

type InsertKBParams struct {
	TeamID             uuid.UUID
	Name               string
	Description        string
	EmbeddingProfileID uuid.UUID
	TopK               int32
	VectorWeight       *float64
	KeywordWeight      *float64
	CreatedBy          uuid.NullUUID
}

func (q *Queries) InsertKB(ctx context.Context, arg InsertKBParams) (KnowledgeBase, error) {
	row := q.db.QueryRow(ctx, insertKB,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.EmbeddingProfileID,
		arg.TopK,
		arg.VectorWeight,
		arg.KeywordWeight,
		arg.CreatedBy,
	)
	var i KnowledgeBase
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.EmbeddingProfileID,
		&i.TopK,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VectorWeight,
		&i.KeywordWeight,
	)
	return i, err
}

const kBProfileWeights = `-- name: KBProfileWeights :many
SELECT kb.id, p.default_vector_weight, p.default_keyword_weight
FROM knowledge_bases kb
JOIN embedding_profiles p ON p.id = kb.embedding_profile_id
WHERE kb.id = ANY($1::uuid[])
`

type KBProfileWeightsRow struct {
	ID                   uuid.UUID
	DefaultVectorWeight  *float64
	DefaultKeywordWeight *float64
}

// The default fusion weights of the KBs' embedding profiles (DESIGN.md §6).
func (q *Queries) KBProfileWeights(ctx context.Context, kbIds []uuid.UUID) ([]KBProfileWeightsRow, error) {
	rows, err := q.db.Query(ctx, kBProfileWeights, kbIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KBProfileWeightsRow{}
	for rows.Next() {
		var i KBProfileWeightsRow
		if err := rows.Scan(&i.ID, &i.DefaultVectorWeight, &i.DefaultKeywordWeight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kBSourceRows = `-- name: KBSourceRows :many
SELECT ks.kb_id, s.id, s.name, s.classification, cl.rank, (s.team_id IS NULL)::bool AS shared
FROM kb_sources ks
JOIN data_sources s ON s.id = ks.source_id
JOIN classification_levels cl ON cl.key = s.classification
WHERE ks.kb_id = ANY($1::uuid[])
ORDER BY lower(s.name)
`

type KBSourceRowsRow struct {
	KBID           uuid.UUID
	ID             uuid.UUID
	Name           string
	Classification string
	Rank           int32
	Shared         bool
}

func (q *Queries) KBSourceRows(ctx context.Context, kbIds []uuid.UUID) ([]KBSourceRowsRow, error) {
	rows, err := q.db.Query(ctx, kBSourceRows, kbIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KBSourceRowsRow{}
	for rows.Next() {
		var i KBSourceRowsRow
		if err := rows.Scan(
			&i.KBID,
			&i.ID,
			&i.Name,
			&i.Classification,
			&i.Rank,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const kBSources = `-- name: KBSources :many
SELECT s.id, s.team_id, s.name, s.description, s.type, s.config, s.classification, s.embedding_profile_id, s.status, s.revision, s.created_by, s.created_at, s.updated_at, s.last_sync_at, s.next_sync_at, s.ocr_enabled FROM kb_sources ks JOIN data_sources s ON s.id = ks.source_id
WHERE ks.kb_id = $1 ORDER BY lower(s.name)
`

func (q *Queries) KBSources(ctx context.Context, kbID uuid.UUID) ([]DataSource, error) {
	rows, err := q.db.Query(ctx, kBSources, kbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataSource{}
	for rows.Next() {
		var i DataSource
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Config,
			&i.Classification,
			&i.EmbeddingProfileID,
			&i.Status,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSyncAt,
			&i.NextSyncAt,
			&i.OcrEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamKBs = `-- name: ListTeamKBs :many
SELECT id, team_id, name, description, embedding_profile_id, top_k, revision, created_by, created_at, updated_at, vector_weight, keyword_weight FROM knowledge_bases WHERE team_id = $1 ORDER BY lower(name), id
`

func (q *Queries) ListTeamKBs(ctx context.Context, teamID uuid.UUID) ([]KnowledgeBase, error) {
	rows, err := q.db.Query(ctx, listTeamKBs, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeBase{}
	for rows.Next() {
		var i KnowledgeBase
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.EmbeddingProfileID,
			&i.TopK,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VectorWeight,
			&i.KeywordWeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadChunks = `-- name: LoadChunks :many
SELECT c.id, c.document_id, c.source_id, c.ordinal, c.content, c.heading_path, c.page_start, c.page_end,
       d.title, d.filename, d.url, d.external_id
FROM chunks c JOIN documents d ON d.id = c.document_id
WHERE c.id = ANY($1::uuid[])
`

type LoadChunksRow struct {
	ID          uuid.UUID
	DocumentID  uuid.UUID
	SourceID    uuid.UUID
	Ordinal     int32
	Content     string
	HeadingPath []string
	PageStart   int32
	PageEnd     int32
	Title       string
	Filename    string
	URL         string
	ExternalID  string
}

func (q *Queries) LoadChunks(ctx context.Context, ids []uuid.UUID) ([]LoadChunksRow, error) {
	rows, err := q.db.Query(ctx, loadChunks, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadChunksRow{}
	for rows.Next() {
		var i LoadChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.SourceID,
			&i.Ordinal,
			&i.Content,
			&i.HeadingPath,
			&i.PageStart,
			&i.PageEnd,
			&i.Title,
			&i.Filename,
			&i.URL,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockKB = `-- name: LockKB :one
SELECT id, team_id, name, description, embedding_profile_id, top_k, revision, created_by, created_at, updated_at, vector_weight, keyword_weight FROM knowledge_bases WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockKB(ctx context.Context, id uuid.UUID) (KnowledgeBase, error) {
	row := q.db.QueryRow(ctx, lockKB, id)
	var i KnowledgeBase
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.EmbeddingProfileID,
		&i.TopK,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VectorWeight,
		&i.KeywordWeight,
	)
	return i, err
}

const updateKB = `-- name: UpdateKB :one
UPDATE knowledge_bases
SET name = $1, description = $2, top_k = $3,
    vector_weight = $4, keyword_weight = $5, revision = revision + 1, updated_at = now()
WHERE id = $6
RETURNING id, team_id, name, description, embedding_profile_id, top_k, revision, created_by, created_at, updated_at, vector_weight, keyword_weight
`

type UpdateKBParams struct {
	Name          string
	Description   string
	TopK          int32
	VectorWeight  *float64
	KeywordWeight *float64
	ID            uuid.UUID
}

func (q *Queries) UpdateKB(ctx context.Context, arg UpdateKBParams) (KnowledgeBase, error) {
	row := q.db.QueryRow(ctx, updateKB,
		arg.Name,
		arg.Description,
		arg.TopK,
		arg.VectorWeight,
		arg.KeywordWeight,
		arg.ID,
	)
	var i KnowledgeBase
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.EmbeddingProfileID,
		&i.TopK,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VectorWeight,
		&i.KeywordWeight,
	)
	return i, err
}
