// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keyrotation.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const keysNotOnPepper = `-- name: KeysNotOnPepper :many
SELECT 'api_key'::text AS kind, k.id, k.name, k.pepper_id, t.slug AS team_slug, t.name AS team_name,
       ''::text AS agent_name, k.last_used_at, k.created_at
FROM api_keys k JOIN teams t ON t.id = k.team_id
WHERE k.revoked_at IS NULL AND (k.expires_at IS NULL OR k.expires_at > now())
  AND k.pepper_id IS DISTINCT FROM $1::bytea
UNION ALL
SELECT 'publishable_key'::text, p.id, p.name, p.pepper_id, t.slug, t.name, a.name, p.last_used_at, p.created_at
FROM publishable_keys p JOIN teams t ON t.id = p.team_id JOIN agents a ON a.id = p.agent_id
WHERE p.revoked_at IS NULL AND a.deleted_at IS NULL
  AND p.pepper_id IS DISTINCT FROM $1::bytea
ORDER BY team_slug, kind, name, id
`

type KeysNotOnPepperRow struct {
	Kind       string
	ID         uuid.UUID
	Name       string
	PepperID   []byte
	TeamSlug   string
	TeamName   string
	AgentName  string
	LastUsedAt *time.Time
	CreatedAt  time.Time
}

// Usable API keys (not revoked or expired) and widget keys (not revoked, on
// a live agent) whose digest is not recorded as made with the given pepper.
func (q *Queries) KeysNotOnPepper(ctx context.Context, pepperID []byte) ([]KeysNotOnPepperRow, error) {
	rows, err := q.db.Query(ctx, keysNotOnPepper, pepperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeysNotOnPepperRow{}
	for rows.Next() {
		var i KeysNotOnPepperRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.Name,
			&i.PepperID,
			&i.TeamSlug,
			&i.TeamName,
			&i.AgentName,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const labelLegacyAPIKeys = `-- name: LabelLegacyAPIKeys :execrows
UPDATE api_keys SET pepper_id = $1 WHERE pepper_id IS NULL
`

// Records the pepper of digests from before pepper ids (NULL): during a
// rotation that is the previous pepper (docs/operations/rotate-keys.md).
func (q *Queries) LabelLegacyAPIKeys(ctx context.Context, pepperID []byte) (int64, error) {
	result, err := q.db.Exec(ctx, labelLegacyAPIKeys, pepperID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const labelLegacyPublishableKeys = `-- name: LabelLegacyPublishableKeys :execrows
UPDATE publishable_keys SET pepper_id = $1 WHERE pepper_id IS NULL
`

func (q *Queries) LabelLegacyPublishableKeys(ctx context.Context, pepperID []byte) (int64, error) {
	result, err := q.db.Exec(ctx, labelLegacyPublishableKeys, pepperID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rehashAPIKey = `-- name: RehashAPIKey :execrows

UPDATE api_keys SET secret_hash = $1, pepper_id = $2
WHERE id = $3 AND secret_hash = $4
`

type RehashAPIKeyParams struct {
	SecretHash []byte
	PepperID   []byte
	ID         uuid.UUID
	OldHash    []byte
}

// Key rotation (docs/phase5-deploy.md E10, docs/operations/rotate-keys.md).
// Moves a key's digest to the current pepper, or records the pepper of a
// digest from before pepper ids. The old digest guards against a
// concurrent change.
func (q *Queries) RehashAPIKey(ctx context.Context, arg RehashAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, rehashAPIKey,
		arg.SecretHash,
		arg.PepperID,
		arg.ID,
		arg.OldHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rehashPublishableKey = `-- name: RehashPublishableKey :execrows
UPDATE publishable_keys SET secret_hash = $1, pepper_id = $2
WHERE id = $3 AND secret_hash = $4
`

type RehashPublishableKeyParams struct {
	SecretHash []byte
	PepperID   []byte
	ID         uuid.UUID
	OldHash    []byte
}

func (q *Queries) RehashPublishableKey(ctx context.Context, arg RehashPublishableKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, rehashPublishableKey,
		arg.SecretHash,
		arg.PepperID,
		arg.ID,
		arg.OldHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
