// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: limits.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countCrawlSlots = `-- name: CountCrawlSlots :one
SELECT count(*) FROM web_crawls
WHERE team_id = $1 AND status IN ('queued', 'running') AND waiting_reason <> 'concurrent_crawls'
`

// Crawl runs holding a slot: running, or queued and admitted (not waiting
// for a slot).
func (q *Queries) CountCrawlSlots(ctx context.Context, teamID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCrawlSlots, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamInflight = `-- name: CountTeamInflight :one
SELECT count(*) FROM documents WHERE team_id = $1 AND status IN ('queued', 'processing')
`

func (q *Queries) CountTeamInflight(ctx context.Context, teamID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamInflight, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamKBs = `-- name: CountTeamKBs :one
SELECT count(*) FROM knowledge_bases WHERE team_id = $1
`

func (q *Queries) CountTeamKBs(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamKBs, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamSources = `-- name: CountTeamSources :one
SELECT count(*) FROM data_sources WHERE team_id = $1
`

func (q *Queries) CountTeamSources(ctx context.Context, teamID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamSources, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPlatformLimits = `-- name: GetPlatformLimits :one

SELECT singleton, settings, revision, updated_by, updated_at FROM platform_limits WHERE singleton
`

// Team limits (internal/limits, DESIGN.md §11.1).
func (q *Queries) GetPlatformLimits(ctx context.Context) (PlatformLimit, error) {
	row := q.db.QueryRow(ctx, getPlatformLimits)
	var i PlatformLimit
	err := row.Scan(
		&i.Singleton,
		&i.Settings,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamLimits = `-- name: GetTeamLimits :one
SELECT team_id, overrides, revision, updated_by, updated_at FROM team_limits WHERE team_id = $1
`

func (q *Queries) GetTeamLimits(ctx context.Context, teamID uuid.UUID) (TeamLimit, error) {
	row := q.db.QueryRow(ctx, getTeamLimits, teamID)
	var i TeamLimit
	err := row.Scan(
		&i.TeamID,
		&i.Overrides,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTeamLimits = `-- name: InsertTeamLimits :execrows
INSERT INTO team_limits (team_id, overrides, revision, updated_by)
VALUES ($1, $2, 2, $3)
ON CONFLICT (team_id) DO NOTHING
`

type InsertTeamLimitsParams struct {
	TeamID    uuid.UUID
	Overrides json.RawMessage
	UpdatedBy uuid.NullUUID
}

// The first change of a team's overrides: revision 1 was the implicit
// "no overrides" state. Zero rows means another admin inserted first.
func (q *Queries) InsertTeamLimits(ctx context.Context, arg InsertTeamLimitsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTeamLimits, arg.TeamID, arg.Overrides, arg.UpdatedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTeamOverrides = `-- name: ListTeamOverrides :many
SELECT t.slug, t.name, tl.overrides
FROM team_limits tl JOIN teams t ON t.id = tl.team_id
WHERE t.status = 'active' AND tl.overrides <> '{}'::jsonb
ORDER BY t.name
`

type ListTeamOverridesRow struct {
	Slug      string
	Name      string
	Overrides json.RawMessage
}

// Active teams with their own limits (Admin → Limits names those a ceiling caps, AD-14).
func (q *Queries) ListTeamOverrides(ctx context.Context) ([]ListTeamOverridesRow, error) {
	rows, err := q.db.Query(ctx, listTeamOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamOverridesRow{}
	for rows.Next() {
		var i ListTeamOverridesRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.Overrides); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlatformLimits = `-- name: LockPlatformLimits :one
SELECT singleton, settings, revision, updated_by, updated_at FROM platform_limits WHERE singleton FOR UPDATE
`

func (q *Queries) LockPlatformLimits(ctx context.Context) (PlatformLimit, error) {
	row := q.db.QueryRow(ctx, lockPlatformLimits)
	var i PlatformLimit
	err := row.Scan(
		&i.Singleton,
		&i.Settings,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const lockTeamCrawlSlots = `-- name: LockTeamCrawlSlots :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::uuid::text, 7302))
`

// Serialises admitting crawl runs of a team (concurrent_crawls).
func (q *Queries) LockTeamCrawlSlots(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockTeamCrawlSlots, dollar_1)
	return err
}

const lockTeamLimits = `-- name: LockTeamLimits :one
SELECT team_id, overrides, revision, updated_by, updated_at FROM team_limits WHERE team_id = $1 FOR UPDATE
`

func (q *Queries) LockTeamLimits(ctx context.Context, teamID uuid.UUID) (TeamLimit, error) {
	row := q.db.QueryRow(ctx, lockTeamLimits, teamID)
	var i TeamLimit
	err := row.Scan(
		&i.TeamID,
		&i.Overrides,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const lockTeamUsage = `-- name: LockTeamUsage :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::uuid::text, 7301))
`

// Serialises changes that check a team's resource caps (uploads, crawled
// pages, sources, knowledge bases), so two requests cannot both take the
// last slot. Held until the transaction ends.
func (q *Queries) LockTeamUsage(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockTeamUsage, dollar_1)
	return err
}

const teamDocumentUsage = `-- name: TeamDocumentUsage :one
SELECT count(*) AS documents, coalesce(sum(size_bytes), 0)::bigint AS storage_bytes
FROM documents WHERE team_id = $1
`

type TeamDocumentUsageRow struct {
	Documents    int64
	StorageBytes int64
}

func (q *Queries) TeamDocumentUsage(ctx context.Context, teamID uuid.NullUUID) (TeamDocumentUsageRow, error) {
	row := q.db.QueryRow(ctx, teamDocumentUsage, teamID)
	var i TeamDocumentUsageRow
	err := row.Scan(&i.Documents, &i.StorageBytes)
	return i, err
}

const teamLimitConfig = `-- name: TeamLimitConfig :one
SELECT p.settings AS platform, t.overrides
FROM platform_limits p LEFT JOIN team_limits t ON t.team_id = $1
WHERE p.singleton
`

type TeamLimitConfigRow struct {
	Platform  json.RawMessage
	Overrides json.RawMessage
}

// The platform settings and one team's overrides (NULL when it has none).
func (q *Queries) TeamLimitConfig(ctx context.Context, teamID uuid.UUID) (TeamLimitConfigRow, error) {
	row := q.db.QueryRow(ctx, teamLimitConfig, teamID)
	var i TeamLimitConfigRow
	err := row.Scan(&i.Platform, &i.Overrides)
	return i, err
}

const teamUsageSince = `-- name: TeamUsageSince :one
SELECT coalesce(sum(quantity), 0)::bigint
FROM usage_events WHERE team_id = $1 AND kind = $2 AND occurred_at >= $3
`

type TeamUsageSinceParams struct {
	TeamID uuid.NullUUID
	Kind   string
	Since  time.Time
}

func (q *Queries) TeamUsageSince(ctx context.Context, arg TeamUsageSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, teamUsageSince, arg.TeamID, arg.Kind, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updatePlatformLimits = `-- name: UpdatePlatformLimits :one
UPDATE platform_limits
SET settings = $1, revision = revision + 1, updated_by = $2, updated_at = now()
WHERE singleton
RETURNING singleton, settings, revision, updated_by, updated_at
`

type UpdatePlatformLimitsParams struct {
	Settings  json.RawMessage
	UpdatedBy uuid.NullUUID
}

func (q *Queries) UpdatePlatformLimits(ctx context.Context, arg UpdatePlatformLimitsParams) (PlatformLimit, error) {
	row := q.db.QueryRow(ctx, updatePlatformLimits, arg.Settings, arg.UpdatedBy)
	var i PlatformLimit
	err := row.Scan(
		&i.Singleton,
		&i.Settings,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamLimits = `-- name: UpdateTeamLimits :one
UPDATE team_limits
SET overrides = $1, revision = revision + 1, updated_by = $2, updated_at = now()
WHERE team_id = $3
RETURNING team_id, overrides, revision, updated_by, updated_at
`

type UpdateTeamLimitsParams struct {
	Overrides json.RawMessage
	UpdatedBy uuid.NullUUID
	TeamID    uuid.UUID
}

func (q *Queries) UpdateTeamLimits(ctx context.Context, arg UpdateTeamLimitsParams) (TeamLimit, error) {
	row := q.db.QueryRow(ctx, updateTeamLimits, arg.Overrides, arg.UpdatedBy, arg.TeamID)
	var i TeamLimit
	err := row.Scan(
		&i.TeamID,
		&i.Overrides,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
