// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMaintenance = `-- name: GetMaintenance :one

SELECT m.singleton, m.enabled, m.reason, m.planned_end_at, m.started_by, m.started_at, m.revision, m.updated_by, m.updated_at,
       coalesce(su.display_name, '')::text AS started_by_name, coalesce(su.email, '')::text AS started_by_email,
       coalesce(uu.display_name, '')::text AS updated_by_name, coalesce(uu.email, '')::text AS updated_by_email
FROM maintenance_mode m
LEFT JOIN users su ON su.id = m.started_by
LEFT JOIN users uu ON uu.id = m.updated_by
`

type GetMaintenanceRow struct {
	Singleton      bool
	Enabled        bool
	Reason         string
	PlannedEndAt   *time.Time
	StartedBy      uuid.NullUUID
	StartedAt      *time.Time
	Revision       int64
	UpdatedBy      uuid.NullUUID
	UpdatedAt      time.Time
	StartedByName  string
	StartedByEmail string
	UpdatedByName  string
	UpdatedByEmail string
}

// Maintenance mode (docs/phase5-deploy.md §5 P5).
func (q *Queries) GetMaintenance(ctx context.Context) (GetMaintenanceRow, error) {
	row := q.db.QueryRow(ctx, getMaintenance)
	var i GetMaintenanceRow
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Reason,
		&i.PlannedEndAt,
		&i.StartedBy,
		&i.StartedAt,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.StartedByName,
		&i.StartedByEmail,
		&i.UpdatedByName,
		&i.UpdatedByEmail,
	)
	return i, err
}

const lockMaintenance = `-- name: LockMaintenance :one
SELECT singleton, enabled, reason, planned_end_at, started_by, started_at, revision, updated_by, updated_at FROM maintenance_mode FOR UPDATE
`

func (q *Queries) LockMaintenance(ctx context.Context) (MaintenanceMode, error) {
	row := q.db.QueryRow(ctx, lockMaintenance)
	var i MaintenanceMode
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Reason,
		&i.PlannedEndAt,
		&i.StartedBy,
		&i.StartedAt,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const parkDocument = `-- name: ParkDocument :execrows
UPDATE documents SET status = 'pending', updated_at = now()
WHERE id = $1 AND status IN ('queued', 'processing')
`

// A document whose job starts during maintenance goes back to pending (a
// 'processing' one is a retry after a crash); the dispatcher queues it again
// once maintenance ends.
func (q *Queries) ParkDocument(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, parkDocument, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMaintenance = `-- name: SetMaintenance :exec
UPDATE maintenance_mode
SET enabled = $1, reason = $2, planned_end_at = $3,
    started_by = $4, started_at = $5,
    updated_by = $6, revision = revision + 1, updated_at = now()
`

type SetMaintenanceParams struct {
	Enabled      bool
	Reason       string
	PlannedEndAt *time.Time
	StartedBy    uuid.NullUUID
	StartedAt    *time.Time
	UpdatedBy    uuid.NullUUID
}

func (q *Queries) SetMaintenance(ctx context.Context, arg SetMaintenanceParams) error {
	_, err := q.db.Exec(ctx, setMaintenance,
		arg.Enabled,
		arg.Reason,
		arg.PlannedEndAt,
		arg.StartedBy,
		arg.StartedAt,
		arg.UpdatedBy,
	)
	return err
}
