// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getMCPSettings = `-- name: GetMCPSettings :one

SELECT singleton, enabled, revision, updated_by, updated_at, oauth_enabled FROM mcp_settings
`

// The MCP server's platform switch (migrations/00035_mcp_server.sql, docs/mcp.md).
func (q *Queries) GetMCPSettings(ctx context.Context) (McpSetting, error) {
	row := q.db.QueryRow(ctx, getMCPSettings)
	var i McpSetting
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.OauthEnabled,
	)
	return i, err
}

const lockMCPSettings = `-- name: LockMCPSettings :one
SELECT singleton, enabled, revision, updated_by, updated_at, oauth_enabled FROM mcp_settings FOR UPDATE
`

func (q *Queries) LockMCPSettings(ctx context.Context) (McpSetting, error) {
	row := q.db.QueryRow(ctx, lockMCPSettings)
	var i McpSetting
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.OauthEnabled,
	)
	return i, err
}

const setMCPSettings = `-- name: SetMCPSettings :one
UPDATE mcp_settings
SET enabled = $1, oauth_enabled = $2, revision = revision + 1, updated_by = $3, updated_at = now()
RETURNING singleton, enabled, revision, updated_by, updated_at, oauth_enabled
`

type SetMCPSettingsParams struct {
	Enabled      bool
	OauthEnabled bool
	UpdatedBy    uuid.NullUUID
}

func (q *Queries) SetMCPSettings(ctx context.Context, arg SetMCPSettingsParams) (McpSetting, error) {
	row := q.db.QueryRow(ctx, setMCPSettings, arg.Enabled, arg.OauthEnabled, arg.UpdatedBy)
	var i McpSetting
	err := row.Scan(
		&i.Singleton,
		&i.Enabled,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.OauthEnabled,
	)
	return i, err
}
