// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_client.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteMCPServer = `-- name: DeleteMCPServer :exec
DELETE FROM mcp_servers WHERE id = $1
`

func (q *Queries) DeleteMCPServer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMCPServer, id)
	return err
}

const getMCPServer = `-- name: GetMCPServer :one
SELECT s.id, s.name, s.description, s.url, s.auth_header_name, s.auth_value_cipher, s.auth_value_hint, s.max_classification, s.timeout_seconds, s.enabled, s.tools_refreshed_at, s.revision, s.created_by, s.created_at, s.updated_by, s.updated_at, cl.rank::int AS max_rank,
       (SELECT count(*) FROM mcp_server_tools t WHERE t.server_id = s.id AND t.gone_at IS NULL)::bigint AS tool_count,
       (SELECT count(*) FROM mcp_server_tools t WHERE t.server_id = s.id AND t.approved)::bigint AS approved_count
FROM mcp_servers s
JOIN classification_levels cl ON cl.key = s.max_classification
WHERE s.id = $1
`

type GetMCPServerRow struct {
	ID                uuid.UUID
	Name              string
	Description       string
	URL               string
	AuthHeaderName    *string
	AuthValueCipher   []byte
	AuthValueHint     string
	MaxClassification string
	TimeoutSeconds    int32
	Enabled           bool
	ToolsRefreshedAt  *time.Time
	Revision          int64
	CreatedBy         uuid.NullUUID
	CreatedAt         time.Time
	UpdatedBy         uuid.NullUUID
	UpdatedAt         time.Time
	MaxRank           int32
	ToolCount         int64
	ApprovedCount     int64
}

func (q *Queries) GetMCPServer(ctx context.Context, id uuid.UUID) (GetMCPServerRow, error) {
	row := q.db.QueryRow(ctx, getMCPServer, id)
	var i GetMCPServerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.URL,
		&i.AuthHeaderName,
		&i.AuthValueCipher,
		&i.AuthValueHint,
		&i.MaxClassification,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.ToolsRefreshedAt,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.MaxRank,
		&i.ToolCount,
		&i.ApprovedCount,
	)
	return i, err
}

const getMCPServerTool = `-- name: GetMCPServerTool :one
SELECT id, server_id, name, title, description, input_schema, approved, approved_by, approved_at, first_seen_at, last_seen_at, gone_at FROM mcp_server_tools WHERE id = $1 AND server_id = $2
`

type GetMCPServerToolParams struct {
	ID       uuid.UUID
	ServerID uuid.UUID
}

func (q *Queries) GetMCPServerTool(ctx context.Context, arg GetMCPServerToolParams) (McpServerTool, error) {
	row := q.db.QueryRow(ctx, getMCPServerTool, arg.ID, arg.ServerID)
	var i McpServerTool
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.InputSchema,
		&i.Approved,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.GoneAt,
	)
	return i, err
}

const insertAgentTool = `-- name: InsertAgentTool :exec
INSERT INTO agent_tools (version_id, tool_id) VALUES ($1, $2)
`

type InsertAgentToolParams struct {
	VersionID uuid.UUID
	ToolID    uuid.UUID
}

func (q *Queries) InsertAgentTool(ctx context.Context, arg InsertAgentToolParams) error {
	_, err := q.db.Exec(ctx, insertAgentTool, arg.VersionID, arg.ToolID)
	return err
}

const insertMCPServer = `-- name: InsertMCPServer :one
INSERT INTO mcp_servers (id, name, description, url, auth_header_name, auth_value_cipher, auth_value_hint,
                         max_classification, timeout_seconds, enabled, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $11)
RETURNING id, name, description, url, auth_header_name, auth_value_cipher, auth_value_hint, max_classification, timeout_seconds, enabled, tools_refreshed_at, revision, created_by, created_at, updated_by, updated_at
`

type InsertMCPServerParams struct {
	ID                uuid.UUID
	Name              string
	Description       string
	URL               string
	AuthHeaderName    *string
	AuthValueCipher   []byte
	AuthValueHint     string
	MaxClassification string
	TimeoutSeconds    int32
	Enabled           bool
	CreatedBy         uuid.NullUUID
}

func (q *Queries) InsertMCPServer(ctx context.Context, arg InsertMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, insertMCPServer,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.URL,
		arg.AuthHeaderName,
		arg.AuthValueCipher,
		arg.AuthValueHint,
		arg.MaxClassification,
		arg.TimeoutSeconds,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.URL,
		&i.AuthHeaderName,
		&i.AuthValueCipher,
		&i.AuthValueHint,
		&i.MaxClassification,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.ToolsRefreshedAt,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listMCPServerTools = `-- name: ListMCPServerTools :many

SELECT t.id, t.server_id, t.name, t.title, t.description, t.input_schema, t.approved, t.approved_by, t.approved_at, t.first_seen_at, t.last_seen_at, t.gone_at, COALESCE(u.display_name, '')::text AS approved_by_name
FROM mcp_server_tools t
LEFT JOIN users u ON u.id = t.approved_by
WHERE t.server_id = $1
ORDER BY t.gone_at IS NOT NULL, lower(t.name), t.id
`

type ListMCPServerToolsRow struct {
	ID             uuid.UUID
	ServerID       uuid.UUID
	Name           string
	Title          string
	Description    string
	InputSchema    json.RawMessage
	Approved       bool
	ApprovedBy     uuid.NullUUID
	ApprovedAt     *time.Time
	FirstSeenAt    time.Time
	LastSeenAt     time.Time
	GoneAt         *time.Time
	ApprovedByName string
}

// ---- tools ----------------------------------------------------------------------
func (q *Queries) ListMCPServerTools(ctx context.Context, serverID uuid.UUID) ([]ListMCPServerToolsRow, error) {
	rows, err := q.db.Query(ctx, listMCPServerTools, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMCPServerToolsRow{}
	for rows.Next() {
		var i ListMCPServerToolsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.InputSchema,
			&i.Approved,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.GoneAt,
			&i.ApprovedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServers = `-- name: ListMCPServers :many


SELECT s.id, s.name, s.description, s.url, s.auth_header_name, s.auth_value_cipher, s.auth_value_hint, s.max_classification, s.timeout_seconds, s.enabled, s.tools_refreshed_at, s.revision, s.created_by, s.created_at, s.updated_by, s.updated_at, cl.rank::int AS max_rank,
       (SELECT count(*) FROM mcp_server_tools t WHERE t.server_id = s.id AND t.gone_at IS NULL)::bigint AS tool_count,
       (SELECT count(*) FROM mcp_server_tools t WHERE t.server_id = s.id AND t.approved)::bigint AS approved_count
FROM mcp_servers s
JOIN classification_levels cl ON cl.key = s.max_classification
ORDER BY lower(s.name), s.id
`

type ListMCPServersRow struct {
	ID                uuid.UUID
	Name              string
	Description       string
	URL               string
	AuthHeaderName    *string
	AuthValueCipher   []byte
	AuthValueHint     string
	MaxClassification string
	TimeoutSeconds    int32
	Enabled           bool
	ToolsRefreshedAt  *time.Time
	Revision          int64
	CreatedBy         uuid.NullUUID
	CreatedAt         time.Time
	UpdatedBy         uuid.NullUUID
	UpdatedAt         time.Time
	MaxRank           int32
	ToolCount         int64
	ApprovedCount     int64
}

// The MCP client in agents (migrations/00037_mcp_client.sql, docs/mcp-client.md).
// ---- servers ------------------------------------------------------------------
func (q *Queries) ListMCPServers(ctx context.Context) ([]ListMCPServersRow, error) {
	rows, err := q.db.Query(ctx, listMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMCPServersRow{}
	for rows.Next() {
		var i ListMCPServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.URL,
			&i.AuthHeaderName,
			&i.AuthValueCipher,
			&i.AuthValueHint,
			&i.MaxClassification,
			&i.TimeoutSeconds,
			&i.Enabled,
			&i.ToolsRefreshedAt,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.MaxRank,
			&i.ToolCount,
			&i.ApprovedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsableMCPTools = `-- name: ListUsableMCPTools :many
SELECT t.id, t.server_id, t.name, t.title, t.description, t.input_schema,
       s.name AS server_name, s.max_classification AS server_max_classification, cl.rank::int AS server_max_rank
FROM mcp_server_tools t
JOIN mcp_servers s ON s.id = t.server_id
JOIN classification_levels cl ON cl.key = s.max_classification
WHERE t.approved AND t.gone_at IS NULL AND s.enabled
ORDER BY lower(s.name), s.id, lower(t.name), t.id
`

type ListUsableMCPToolsRow struct {
	ID                      uuid.UUID
	ServerID                uuid.UUID
	Name                    string
	Title                   string
	Description             string
	InputSchema             json.RawMessage
	ServerName              string
	ServerMaxClassification string
	ServerMaxRank           int32
}

// Approved tools of enabled servers (the agent editor's choices).
func (q *Queries) ListUsableMCPTools(ctx context.Context) ([]ListUsableMCPToolsRow, error) {
	rows, err := q.db.Query(ctx, listUsableMCPTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsableMCPToolsRow{}
	for rows.Next() {
		var i ListUsableMCPToolsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.InputSchema,
			&i.ServerName,
			&i.ServerMaxClassification,
			&i.ServerMaxRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMCPServer = `-- name: LockMCPServer :one
SELECT id, name, description, url, auth_header_name, auth_value_cipher, auth_value_hint, max_classification, timeout_seconds, enabled, tools_refreshed_at, revision, created_by, created_at, updated_by, updated_at FROM mcp_servers WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockMCPServer(ctx context.Context, id uuid.UUID) (McpServer, error) {
	row := q.db.QueryRow(ctx, lockMCPServer, id)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.URL,
		&i.AuthHeaderName,
		&i.AuthValueCipher,
		&i.AuthValueHint,
		&i.MaxClassification,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.ToolsRefreshedAt,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const lockMCPServerTool = `-- name: LockMCPServerTool :one
SELECT id, server_id, name, title, description, input_schema, approved, approved_by, approved_at, first_seen_at, last_seen_at, gone_at FROM mcp_server_tools WHERE id = $1 AND server_id = $2 FOR UPDATE
`

type LockMCPServerToolParams struct {
	ID       uuid.UUID
	ServerID uuid.UUID
}

func (q *Queries) LockMCPServerTool(ctx context.Context, arg LockMCPServerToolParams) (McpServerTool, error) {
	row := q.db.QueryRow(ctx, lockMCPServerTool, arg.ID, arg.ServerID)
	var i McpServerTool
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.InputSchema,
		&i.Approved,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.GoneAt,
	)
	return i, err
}

const mCPServerCallTarget = `-- name: MCPServerCallTarget :one
SELECT s.id, s.name, s.url, s.auth_header_name, s.auth_value_cipher, s.timeout_seconds, s.enabled, cl.rank::int AS max_rank
FROM mcp_servers s
JOIN classification_levels cl ON cl.key = s.max_classification
WHERE s.id = $1
`

type MCPServerCallTargetRow struct {
	ID              uuid.UUID
	Name            string
	URL             string
	AuthHeaderName  *string
	AuthValueCipher []byte
	TimeoutSeconds  int32
	Enabled         bool
	MaxRank         int32
}

// A server's settings at call time (the ceiling is checked on every call).
func (q *Queries) MCPServerCallTarget(ctx context.Context, id uuid.UUID) (MCPServerCallTargetRow, error) {
	row := q.db.QueryRow(ctx, mCPServerCallTarget, id)
	var i MCPServerCallTargetRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.URL,
		&i.AuthHeaderName,
		&i.AuthValueCipher,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.MaxRank,
	)
	return i, err
}

const mCPServerPublishedUses = `-- name: MCPServerPublishedUses :many
SELECT DISTINCT a.id, a.name, t.slug AS team_slug, t.name AS team_name
FROM agents a
JOIN teams t ON t.id = a.team_id
JOIN agent_tools vt ON vt.version_id = a.published_version_id
JOIN mcp_server_tools st ON st.id = vt.tool_id
WHERE st.server_id = $1 AND a.deleted_at IS NULL
ORDER BY a.name, a.id
`

type MCPServerPublishedUsesRow struct {
	ID       uuid.UUID
	Name     string
	TeamSlug string
	TeamName string
}

// The agents whose published (current) version uses a tool of the server.
func (q *Queries) MCPServerPublishedUses(ctx context.Context, serverID uuid.UUID) ([]MCPServerPublishedUsesRow, error) {
	rows, err := q.db.Query(ctx, mCPServerPublishedUses, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MCPServerPublishedUsesRow{}
	for rows.Next() {
		var i MCPServerPublishedUsesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamSlug,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mCPToolsByIDs = `-- name: MCPToolsByIDs :many
SELECT t.id, t.server_id, t.name, t.title, t.description, t.input_schema, t.approved, t.gone_at,
       s.name AS server_name, s.url AS server_url, s.enabled AS server_enabled,
       s.max_classification AS server_max_classification, cl.rank::int AS server_max_rank, s.timeout_seconds AS server_timeout_seconds
FROM mcp_server_tools t
JOIN mcp_servers s ON s.id = t.server_id
JOIN classification_levels cl ON cl.key = s.max_classification
WHERE t.id = ANY($1::uuid[])
`

type MCPToolsByIDsRow struct {
	ID                      uuid.UUID
	ServerID                uuid.UUID
	Name                    string
	Title                   string
	Description             string
	InputSchema             json.RawMessage
	Approved                bool
	GoneAt                  *time.Time
	ServerName              string
	ServerUrl               string
	ServerEnabled           bool
	ServerMaxClassification string
	ServerMaxRank           int32
	ServerTimeoutSeconds    int32
}

// Tools with their server, for agents: the editor's choices, publish checks
// and answers.
func (q *Queries) MCPToolsByIDs(ctx context.Context, ids []uuid.UUID) ([]MCPToolsByIDsRow, error) {
	rows, err := q.db.Query(ctx, mCPToolsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MCPToolsByIDsRow{}
	for rows.Next() {
		var i MCPToolsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.InputSchema,
			&i.Approved,
			&i.GoneAt,
			&i.ServerName,
			&i.ServerUrl,
			&i.ServerEnabled,
			&i.ServerMaxClassification,
			&i.ServerMaxRank,
			&i.ServerTimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMCPServerToolsGone = `-- name: MarkMCPServerToolsGone :many
UPDATE mcp_server_tools
SET gone_at = COALESCE(gone_at, now()), approved = false, approved_by = NULL, approved_at = NULL
WHERE server_id = $1 AND NOT (name = ANY($2::text[])) AND gone_at IS NULL
RETURNING id, server_id, name, title, description, input_schema, approved, approved_by, approved_at, first_seen_at, last_seen_at, gone_at
`

type MarkMCPServerToolsGoneParams struct {
	ServerID uuid.UUID
	Listed   []string
}

// Tools the server no longer lists: gone and unapproved.
func (q *Queries) MarkMCPServerToolsGone(ctx context.Context, arg MarkMCPServerToolsGoneParams) ([]McpServerTool, error) {
	rows, err := q.db.Query(ctx, markMCPServerToolsGone, arg.ServerID, arg.Listed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServerTool{}
	for rows.Next() {
		var i McpServerTool
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.InputSchema,
			&i.Approved,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.GoneAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMCPServerToolApproval = `-- name: SetMCPServerToolApproval :one
UPDATE mcp_server_tools
SET approved = $1, approved_by = $2, approved_at = CASE WHEN $1::boolean THEN now() END
WHERE id = $3 AND server_id = $4
RETURNING id, server_id, name, title, description, input_schema, approved, approved_by, approved_at, first_seen_at, last_seen_at, gone_at
`

type SetMCPServerToolApprovalParams struct {
	Approved   bool
	ApprovedBy uuid.NullUUID
	ID         uuid.UUID
	ServerID   uuid.UUID
}

func (q *Queries) SetMCPServerToolApproval(ctx context.Context, arg SetMCPServerToolApprovalParams) (McpServerTool, error) {
	row := q.db.QueryRow(ctx, setMCPServerToolApproval,
		arg.Approved,
		arg.ApprovedBy,
		arg.ID,
		arg.ServerID,
	)
	var i McpServerTool
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.InputSchema,
		&i.Approved,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.GoneAt,
	)
	return i, err
}

const touchMCPServerTools = `-- name: TouchMCPServerTools :exec
UPDATE mcp_servers SET tools_refreshed_at = now() WHERE id = $1
`

func (q *Queries) TouchMCPServerTools(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchMCPServerTools, id)
	return err
}

const updateMCPServer = `-- name: UpdateMCPServer :one
UPDATE mcp_servers
SET name = $1, description = $2, url = $3, auth_header_name = $4,
    auth_value_cipher = $5, auth_value_hint = $6,
    max_classification = $7, timeout_seconds = $8, enabled = $9,
    revision = revision + 1, updated_by = $10, updated_at = now()
WHERE id = $11
RETURNING id, name, description, url, auth_header_name, auth_value_cipher, auth_value_hint, max_classification, timeout_seconds, enabled, tools_refreshed_at, revision, created_by, created_at, updated_by, updated_at
`

type UpdateMCPServerParams struct {
	Name              string
	Description       string
	URL               string
	AuthHeaderName    *string
	AuthValueCipher   []byte
	AuthValueHint     string
	MaxClassification string
	TimeoutSeconds    int32
	Enabled           bool
	UpdatedBy         uuid.NullUUID
	ID                uuid.UUID
}

func (q *Queries) UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, updateMCPServer,
		arg.Name,
		arg.Description,
		arg.URL,
		arg.AuthHeaderName,
		arg.AuthValueCipher,
		arg.AuthValueHint,
		arg.MaxClassification,
		arg.TimeoutSeconds,
		arg.Enabled,
		arg.UpdatedBy,
		arg.ID,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.URL,
		&i.AuthHeaderName,
		&i.AuthValueCipher,
		&i.AuthValueHint,
		&i.MaxClassification,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.ToolsRefreshedAt,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMCPServerTool = `-- name: UpsertMCPServerTool :one
INSERT INTO mcp_server_tools (server_id, name, title, description, input_schema, last_seen_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (server_id, name) DO UPDATE
SET title = EXCLUDED.title, description = EXCLUDED.description, input_schema = EXCLUDED.input_schema,
    last_seen_at = now(), gone_at = NULL,
    approved = mcp_server_tools.approved AND $6::boolean,
    approved_by = CASE WHEN $6::boolean THEN mcp_server_tools.approved_by END,
    approved_at = CASE WHEN $6::boolean THEN mcp_server_tools.approved_at END
RETURNING id, server_id, name, title, description, input_schema, approved, approved_by, approved_at, first_seen_at, last_seen_at, gone_at
`

type UpsertMCPServerToolParams struct {
	ServerID     uuid.UUID
	Name         string
	Title        string
	Description  string
	InputSchema  json.RawMessage
	KeepApproval bool
}

// A tool the server lists now: inserted, or refreshed (and brought back if
// it was gone). The caller decides whether its approval stands.
func (q *Queries) UpsertMCPServerTool(ctx context.Context, arg UpsertMCPServerToolParams) (McpServerTool, error) {
	row := q.db.QueryRow(ctx, upsertMCPServerTool,
		arg.ServerID,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.InputSchema,
		arg.KeepApproval,
	)
	var i McpServerTool
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.InputSchema,
		&i.Approved,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.GoneAt,
	)
	return i, err
}
