// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const clearDefaultEmbeddingProfile = `-- name: ClearDefaultEmbeddingProfile :exec
UPDATE embedding_profiles
SET is_default = false, revision = revision + 1, updated_at = now()
WHERE is_default AND id <> $1
`

func (q *Queries) ClearDefaultEmbeddingProfile(ctx context.Context, exceptID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultEmbeddingProfile, exceptID)
	return err
}

const countConnectionModels = `-- name: CountConnectionModels :one
SELECT count(*) FROM models WHERE connection_id = $1
`

func (q *Queries) CountConnectionModels(ctx context.Context, connectionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConnectionModels, connectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmbeddingProfiles = `-- name: CountEmbeddingProfiles :one
SELECT count(*) FROM embedding_profiles
`

func (q *Queries) CountEmbeddingProfiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEmbeddingProfiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countModelProfiles = `-- name: CountModelProfiles :one
SELECT count(*) FROM embedding_profiles WHERE model_id = $1
`

func (q *Queries) CountModelProfiles(ctx context.Context, modelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countModelProfiles, modelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM model_connections WHERE id = $1
`

func (q *Queries) DeleteConnection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConnection, id)
	return err
}

const deleteEmbeddingProfile = `-- name: DeleteEmbeddingProfile :exec
DELETE FROM embedding_profiles WHERE id = $1
`

func (q *Queries) DeleteEmbeddingProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmbeddingProfile, id)
	return err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM models WHERE id = $1
`

func (q *Queries) DeleteModel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteModel, id)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT id, name, description, base_url, api_key_ciphertext, api_key_hint, timeout_seconds, enabled, revision, created_by, created_at, updated_at, requests_per_minute, max_concurrent_requests FROM model_connections WHERE id = $1
`

func (q *Queries) GetConnection(ctx context.Context, id uuid.UUID) (ModelConnection, error) {
	row := q.db.QueryRow(ctx, getConnection, id)
	var i ModelConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BaseURL,
		&i.ApiKeyCiphertext,
		&i.ApiKeyHint,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestsPerMinute,
		&i.MaxConcurrentRequests,
	)
	return i, err
}

const getEmbeddingProfile = `-- name: GetEmbeddingProfile :one
SELECT p.id, p.key, p.name, p.description, p.model_id, p.dimensions, p.storage_type, p.document_prefix, p.query_prefix, p.chunk_size, p.chunk_overlap, p.chunker_version, p.status, p.is_default, p.revision, p.created_by, p.created_at, p.updated_at, p.output_dimensions, p.default_vector_weight, p.default_keyword_weight, m.id, m.connection_id, m.key, m.upstream_model, m.display_name, m.description, m.kind, m.max_classification, m.enabled, m.context_window, m.max_output_tokens, m.supports_tools, m.supports_vision, m.dimensions, m.max_input_tokens, m.compat, m.revision, m.created_by, m.created_at, m.updated_at, m.moderation_provider, m.moderation_family, m.moderation_timeout_seconds
FROM embedding_profiles p
JOIN models m ON m.id = p.model_id
WHERE p.id = $1
`

type GetEmbeddingProfileRow struct {
	EmbeddingProfile EmbeddingProfile
	Model            Model
}

func (q *Queries) GetEmbeddingProfile(ctx context.Context, id uuid.UUID) (GetEmbeddingProfileRow, error) {
	row := q.db.QueryRow(ctx, getEmbeddingProfile, id)
	var i GetEmbeddingProfileRow
	err := row.Scan(
		&i.EmbeddingProfile.ID,
		&i.EmbeddingProfile.Key,
		&i.EmbeddingProfile.Name,
		&i.EmbeddingProfile.Description,
		&i.EmbeddingProfile.ModelID,
		&i.EmbeddingProfile.Dimensions,
		&i.EmbeddingProfile.StorageType,
		&i.EmbeddingProfile.DocumentPrefix,
		&i.EmbeddingProfile.QueryPrefix,
		&i.EmbeddingProfile.ChunkSize,
		&i.EmbeddingProfile.ChunkOverlap,
		&i.EmbeddingProfile.ChunkerVersion,
		&i.EmbeddingProfile.Status,
		&i.EmbeddingProfile.IsDefault,
		&i.EmbeddingProfile.Revision,
		&i.EmbeddingProfile.CreatedBy,
		&i.EmbeddingProfile.CreatedAt,
		&i.EmbeddingProfile.UpdatedAt,
		&i.EmbeddingProfile.OutputDimensions,
		&i.EmbeddingProfile.DefaultVectorWeight,
		&i.EmbeddingProfile.DefaultKeywordWeight,
		&i.Model.ID,
		&i.Model.ConnectionID,
		&i.Model.Key,
		&i.Model.UpstreamModel,
		&i.Model.DisplayName,
		&i.Model.Description,
		&i.Model.Kind,
		&i.Model.MaxClassification,
		&i.Model.Enabled,
		&i.Model.ContextWindow,
		&i.Model.MaxOutputTokens,
		&i.Model.SupportsTools,
		&i.Model.SupportsVision,
		&i.Model.Dimensions,
		&i.Model.MaxInputTokens,
		&i.Model.Compat,
		&i.Model.Revision,
		&i.Model.CreatedBy,
		&i.Model.CreatedAt,
		&i.Model.UpdatedAt,
		&i.Model.ModerationProvider,
		&i.Model.ModerationFamily,
		&i.Model.ModerationTimeoutSeconds,
	)
	return i, err
}

const getModel = `-- name: GetModel :one
SELECT id, connection_id, key, upstream_model, display_name, description, kind, max_classification, enabled, context_window, max_output_tokens, supports_tools, supports_vision, dimensions, max_input_tokens, compat, revision, created_by, created_at, updated_at, moderation_provider, moderation_family, moderation_timeout_seconds FROM models WHERE id = $1
`

func (q *Queries) GetModel(ctx context.Context, id uuid.UUID) (Model, error) {
	row := q.db.QueryRow(ctx, getModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Key,
		&i.UpstreamModel,
		&i.DisplayName,
		&i.Description,
		&i.Kind,
		&i.MaxClassification,
		&i.Enabled,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.SupportsTools,
		&i.SupportsVision,
		&i.Dimensions,
		&i.MaxInputTokens,
		&i.Compat,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationProvider,
		&i.ModerationFamily,
		&i.ModerationTimeoutSeconds,
	)
	return i, err
}

const insertConnection = `-- name: InsertConnection :one
INSERT INTO model_connections (id, name, description, base_url, api_key_ciphertext, api_key_hint, timeout_seconds, enabled, requests_per_minute,
                               max_concurrent_requests, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11)
RETURNING id, name, description, base_url, api_key_ciphertext, api_key_hint, timeout_seconds, enabled, revision, created_by, created_at, updated_at, requests_per_minute, max_concurrent_requests
`

type InsertConnectionParams struct {
	ID                    uuid.UUID
	Name                  string
	Description           string
	BaseURL               string
	ApiKeyCiphertext      []byte
	ApiKeyHint            string
	TimeoutSeconds        int32
	Enabled               bool
	RequestsPerMinute     *int32
	MaxConcurrentRequests int32
	CreatedBy             uuid.NullUUID
}

func (q *Queries) InsertConnection(ctx context.Context, arg InsertConnectionParams) (ModelConnection, error) {
	row := q.db.QueryRow(ctx, insertConnection,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.BaseURL,
		arg.ApiKeyCiphertext,
		arg.ApiKeyHint,
		arg.TimeoutSeconds,
		arg.Enabled,
		arg.RequestsPerMinute,
		arg.MaxConcurrentRequests,
		arg.CreatedBy,
	)
	var i ModelConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BaseURL,
		&i.ApiKeyCiphertext,
		&i.ApiKeyHint,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestsPerMinute,
		&i.MaxConcurrentRequests,
	)
	return i, err
}

const insertEmbeddingProfile = `-- name: InsertEmbeddingProfile :one
INSERT INTO embedding_profiles (key, name, description, model_id, dimensions, storage_type,
                                document_prefix, query_prefix, chunk_size, chunk_overlap, created_by,
                                output_dimensions, default_vector_weight, default_keyword_weight)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11,
        $12, $13, $14)
RETURNING id, key, name, description, model_id, dimensions, storage_type, document_prefix, query_prefix, chunk_size, chunk_overlap, chunker_version, status, is_default, revision, created_by, created_at, updated_at, output_dimensions, default_vector_weight, default_keyword_weight
`

type InsertEmbeddingProfileParams struct {
	Key                  string
	Name                 string
	Description          string
	ModelID              uuid.UUID
	Dimensions           int32
	StorageType          string
	DocumentPrefix       string
	QueryPrefix          string
	ChunkSize            int32
	ChunkOverlap         int32
	CreatedBy            uuid.NullUUID
	OutputDimensions     *int32
	DefaultVectorWeight  *float64
	DefaultKeywordWeight *float64
}

func (q *Queries) InsertEmbeddingProfile(ctx context.Context, arg InsertEmbeddingProfileParams) (EmbeddingProfile, error) {
	row := q.db.QueryRow(ctx, insertEmbeddingProfile,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.ModelID,
		arg.Dimensions,
		arg.StorageType,
		arg.DocumentPrefix,
		arg.QueryPrefix,
		arg.ChunkSize,
		arg.ChunkOverlap,
		arg.CreatedBy,
		arg.OutputDimensions,
		arg.DefaultVectorWeight,
		arg.DefaultKeywordWeight,
	)
	var i EmbeddingProfile
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ModelID,
		&i.Dimensions,
		&i.StorageType,
		&i.DocumentPrefix,
		&i.QueryPrefix,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.ChunkerVersion,
		&i.Status,
		&i.IsDefault,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutputDimensions,
		&i.DefaultVectorWeight,
		&i.DefaultKeywordWeight,
	)
	return i, err
}

const insertModel = `-- name: InsertModel :one
INSERT INTO models (connection_id, key, upstream_model, display_name, description, kind, max_classification,
                    enabled, context_window, max_output_tokens, supports_tools, supports_vision,
                    dimensions, max_input_tokens, compat, moderation_provider, moderation_family,
                    moderation_timeout_seconds, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12,
        $13, $14, $15, $16, $17,
        $18, $19)
RETURNING id, connection_id, key, upstream_model, display_name, description, kind, max_classification, enabled, context_window, max_output_tokens, supports_tools, supports_vision, dimensions, max_input_tokens, compat, revision, created_by, created_at, updated_at, moderation_provider, moderation_family, moderation_timeout_seconds
`

type InsertModelParams struct {
	ConnectionID             uuid.UUID
	Key                      string
	UpstreamModel            string
	DisplayName              string
	Description              string
	Kind                     string
	MaxClassification        string
	Enabled                  bool
	ContextWindow            *int32
	MaxOutputTokens          *int32
	SupportsTools            bool
	SupportsVision           bool
	Dimensions               *int32
	MaxInputTokens           *int32
	Compat                   json.RawMessage
	ModerationProvider       *string
	ModerationFamily         *string
	ModerationTimeoutSeconds *int32
	CreatedBy                uuid.NullUUID
}

func (q *Queries) InsertModel(ctx context.Context, arg InsertModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, insertModel,
		arg.ConnectionID,
		arg.Key,
		arg.UpstreamModel,
		arg.DisplayName,
		arg.Description,
		arg.Kind,
		arg.MaxClassification,
		arg.Enabled,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.SupportsTools,
		arg.SupportsVision,
		arg.Dimensions,
		arg.MaxInputTokens,
		arg.Compat,
		arg.ModerationProvider,
		arg.ModerationFamily,
		arg.ModerationTimeoutSeconds,
		arg.CreatedBy,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Key,
		&i.UpstreamModel,
		&i.DisplayName,
		&i.Description,
		&i.Kind,
		&i.MaxClassification,
		&i.Enabled,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.SupportsTools,
		&i.SupportsVision,
		&i.Dimensions,
		&i.MaxInputTokens,
		&i.Compat,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationProvider,
		&i.ModerationFamily,
		&i.ModerationTimeoutSeconds,
	)
	return i, err
}

const listConnections = `-- name: ListConnections :many
SELECT c.id, c.name, c.description, c.base_url, c.api_key_ciphertext, c.api_key_hint, c.timeout_seconds, c.enabled, c.revision, c.created_by, c.created_at, c.updated_at, c.requests_per_minute, c.max_concurrent_requests, (SELECT count(*) FROM models m WHERE m.connection_id = c.id)::bigint AS model_count
FROM model_connections c
ORDER BY c.name
`

type ListConnectionsRow struct {
	ID                    uuid.UUID
	Name                  string
	Description           string
	BaseURL               string
	ApiKeyCiphertext      []byte
	ApiKeyHint            string
	TimeoutSeconds        int32
	Enabled               bool
	Revision              int64
	CreatedBy             uuid.NullUUID
	CreatedAt             time.Time
	UpdatedAt             time.Time
	RequestsPerMinute     *int32
	MaxConcurrentRequests int32
	ModelCount            int64
}

func (q *Queries) ListConnections(ctx context.Context) ([]ListConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionsRow{}
	for rows.Next() {
		var i ListConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BaseURL,
			&i.ApiKeyCiphertext,
			&i.ApiKeyHint,
			&i.TimeoutSeconds,
			&i.Enabled,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequestsPerMinute,
			&i.MaxConcurrentRequests,
			&i.ModelCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbeddingProfiles = `-- name: ListEmbeddingProfiles :many
SELECT p.id, p.key, p.name, p.description, p.model_id, p.dimensions, p.storage_type, p.document_prefix, p.query_prefix, p.chunk_size, p.chunk_overlap, p.chunker_version, p.status, p.is_default, p.revision, p.created_by, p.created_at, p.updated_at, p.output_dimensions, p.default_vector_weight, p.default_keyword_weight, m.id, m.connection_id, m.key, m.upstream_model, m.display_name, m.description, m.kind, m.max_classification, m.enabled, m.context_window, m.max_output_tokens, m.supports_tools, m.supports_vision, m.dimensions, m.max_input_tokens, m.compat, m.revision, m.created_by, m.created_at, m.updated_at, m.moderation_provider, m.moderation_family, m.moderation_timeout_seconds
FROM embedding_profiles p
JOIN models m ON m.id = p.model_id
ORDER BY p.is_default DESC, p.name, p.key
`

type ListEmbeddingProfilesRow struct {
	EmbeddingProfile EmbeddingProfile
	Model            Model
}

func (q *Queries) ListEmbeddingProfiles(ctx context.Context) ([]ListEmbeddingProfilesRow, error) {
	rows, err := q.db.Query(ctx, listEmbeddingProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmbeddingProfilesRow{}
	for rows.Next() {
		var i ListEmbeddingProfilesRow
		if err := rows.Scan(
			&i.EmbeddingProfile.ID,
			&i.EmbeddingProfile.Key,
			&i.EmbeddingProfile.Name,
			&i.EmbeddingProfile.Description,
			&i.EmbeddingProfile.ModelID,
			&i.EmbeddingProfile.Dimensions,
			&i.EmbeddingProfile.StorageType,
			&i.EmbeddingProfile.DocumentPrefix,
			&i.EmbeddingProfile.QueryPrefix,
			&i.EmbeddingProfile.ChunkSize,
			&i.EmbeddingProfile.ChunkOverlap,
			&i.EmbeddingProfile.ChunkerVersion,
			&i.EmbeddingProfile.Status,
			&i.EmbeddingProfile.IsDefault,
			&i.EmbeddingProfile.Revision,
			&i.EmbeddingProfile.CreatedBy,
			&i.EmbeddingProfile.CreatedAt,
			&i.EmbeddingProfile.UpdatedAt,
			&i.EmbeddingProfile.OutputDimensions,
			&i.EmbeddingProfile.DefaultVectorWeight,
			&i.EmbeddingProfile.DefaultKeywordWeight,
			&i.Model.ID,
			&i.Model.ConnectionID,
			&i.Model.Key,
			&i.Model.UpstreamModel,
			&i.Model.DisplayName,
			&i.Model.Description,
			&i.Model.Kind,
			&i.Model.MaxClassification,
			&i.Model.Enabled,
			&i.Model.ContextWindow,
			&i.Model.MaxOutputTokens,
			&i.Model.SupportsTools,
			&i.Model.SupportsVision,
			&i.Model.Dimensions,
			&i.Model.MaxInputTokens,
			&i.Model.Compat,
			&i.Model.Revision,
			&i.Model.CreatedBy,
			&i.Model.CreatedAt,
			&i.Model.UpdatedAt,
			&i.Model.ModerationProvider,
			&i.Model.ModerationFamily,
			&i.Model.ModerationTimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT id, connection_id, key, upstream_model, display_name, description, kind, max_classification, enabled, context_window, max_output_tokens, supports_tools, supports_vision, dimensions, max_input_tokens, compat, revision, created_by, created_at, updated_at, moderation_provider, moderation_family, moderation_timeout_seconds FROM models
WHERE ($1::text IS NULL OR kind = $1::text)
  AND ($2::uuid IS NULL OR connection_id = $2::uuid)
ORDER BY kind, display_name, key
`

type ListModelsParams struct {
	Kind         *string
	ConnectionID uuid.NullUUID
}

func (q *Queries) ListModels(ctx context.Context, arg ListModelsParams) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels, arg.Kind, arg.ConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Key,
			&i.UpstreamModel,
			&i.DisplayName,
			&i.Description,
			&i.Kind,
			&i.MaxClassification,
			&i.Enabled,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.SupportsTools,
			&i.SupportsVision,
			&i.Dimensions,
			&i.MaxInputTokens,
			&i.Compat,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModerationProvider,
			&i.ModerationFamily,
			&i.ModerationTimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsableChatModels = `-- name: ListUsableChatModels :many
SELECT m.id, m.connection_id, m.key, m.upstream_model, m.display_name, m.description, m.kind, m.max_classification, m.enabled, m.context_window, m.max_output_tokens, m.supports_tools, m.supports_vision, m.dimensions, m.max_input_tokens, m.compat, m.revision, m.created_by, m.created_at, m.updated_at, m.moderation_provider, m.moderation_family, m.moderation_timeout_seconds FROM models m
JOIN model_connections c ON c.id = m.connection_id
WHERE m.kind = 'chat' AND m.enabled AND c.enabled
ORDER BY m.display_name, m.key
`

// Chat models teams may pick for agents: enabled, on an enabled connection.
func (q *Queries) ListUsableChatModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listUsableChatModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Key,
			&i.UpstreamModel,
			&i.DisplayName,
			&i.Description,
			&i.Kind,
			&i.MaxClassification,
			&i.Enabled,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.SupportsTools,
			&i.SupportsVision,
			&i.Dimensions,
			&i.MaxInputTokens,
			&i.Compat,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModerationProvider,
			&i.ModerationFamily,
			&i.ModerationTimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsableSystemOneModels = `-- name: ListUsableSystemOneModels :many
SELECT m.id, m.connection_id, m.key, m.upstream_model, m.display_name, m.description, m.kind, m.max_classification, m.enabled, m.context_window, m.max_output_tokens, m.supports_tools, m.supports_vision, m.dimensions, m.max_input_tokens, m.compat, m.revision, m.created_by, m.created_at, m.updated_at, m.moderation_provider, m.moderation_family, m.moderation_timeout_seconds FROM models m
JOIN model_connections c ON c.id = m.connection_id
WHERE m.kind = 'systemone' AND m.enabled AND c.enabled
ORDER BY m.display_name, m.key
`

// SystemOne models admins may choose (moderation providers, features):
// enabled, on an enabled connection.
func (q *Queries) ListUsableSystemOneModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listUsableSystemOneModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Key,
			&i.UpstreamModel,
			&i.DisplayName,
			&i.Description,
			&i.Kind,
			&i.MaxClassification,
			&i.Enabled,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.SupportsTools,
			&i.SupportsVision,
			&i.Dimensions,
			&i.MaxInputTokens,
			&i.Compat,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModerationProvider,
			&i.ModerationFamily,
			&i.ModerationTimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsableVisionModels = `-- name: ListUsableVisionModels :many
SELECT m.id, m.connection_id, m.key, m.upstream_model, m.display_name, m.description, m.kind, m.max_classification, m.enabled, m.context_window, m.max_output_tokens, m.supports_tools, m.supports_vision, m.dimensions, m.max_input_tokens, m.compat, m.revision, m.created_by, m.created_at, m.updated_at, m.moderation_provider, m.moderation_family, m.moderation_timeout_seconds FROM models m
JOIN model_connections c ON c.id = m.connection_id
WHERE m.kind = 'vision' AND m.enabled AND c.enabled
ORDER BY m.display_name, m.key
`

func (q *Queries) ListUsableVisionModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.Query(ctx, listUsableVisionModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.Key,
			&i.UpstreamModel,
			&i.DisplayName,
			&i.Description,
			&i.Kind,
			&i.MaxClassification,
			&i.Enabled,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.SupportsTools,
			&i.SupportsVision,
			&i.Dimensions,
			&i.MaxInputTokens,
			&i.Compat,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModerationProvider,
			&i.ModerationFamily,
			&i.ModerationTimeoutSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConnection = `-- name: LockConnection :one
SELECT id, name, description, base_url, api_key_ciphertext, api_key_hint, timeout_seconds, enabled, revision, created_by, created_at, updated_at, requests_per_minute, max_concurrent_requests FROM model_connections WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockConnection(ctx context.Context, id uuid.UUID) (ModelConnection, error) {
	row := q.db.QueryRow(ctx, lockConnection, id)
	var i ModelConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BaseURL,
		&i.ApiKeyCiphertext,
		&i.ApiKeyHint,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestsPerMinute,
		&i.MaxConcurrentRequests,
	)
	return i, err
}

const lockEmbeddingProfile = `-- name: LockEmbeddingProfile :one
SELECT id, key, name, description, model_id, dimensions, storage_type, document_prefix, query_prefix, chunk_size, chunk_overlap, chunker_version, status, is_default, revision, created_by, created_at, updated_at, output_dimensions, default_vector_weight, default_keyword_weight FROM embedding_profiles WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockEmbeddingProfile(ctx context.Context, id uuid.UUID) (EmbeddingProfile, error) {
	row := q.db.QueryRow(ctx, lockEmbeddingProfile, id)
	var i EmbeddingProfile
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ModelID,
		&i.Dimensions,
		&i.StorageType,
		&i.DocumentPrefix,
		&i.QueryPrefix,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.ChunkerVersion,
		&i.Status,
		&i.IsDefault,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutputDimensions,
		&i.DefaultVectorWeight,
		&i.DefaultKeywordWeight,
	)
	return i, err
}

const lockModel = `-- name: LockModel :one
SELECT id, connection_id, key, upstream_model, display_name, description, kind, max_classification, enabled, context_window, max_output_tokens, supports_tools, supports_vision, dimensions, max_input_tokens, compat, revision, created_by, created_at, updated_at, moderation_provider, moderation_family, moderation_timeout_seconds FROM models WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockModel(ctx context.Context, id uuid.UUID) (Model, error) {
	row := q.db.QueryRow(ctx, lockModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Key,
		&i.UpstreamModel,
		&i.DisplayName,
		&i.Description,
		&i.Kind,
		&i.MaxClassification,
		&i.Enabled,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.SupportsTools,
		&i.SupportsVision,
		&i.Dimensions,
		&i.MaxInputTokens,
		&i.Compat,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationProvider,
		&i.ModerationFamily,
		&i.ModerationTimeoutSeconds,
	)
	return i, err
}

const lockModelConfig = `-- name: LockModelConfig :exec
SELECT pg_advisory_xact_lock(7378431002)
`

func (q *Queries) LockModelConfig(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockModelConfig)
	return err
}

const updateConnection = `-- name: UpdateConnection :one
UPDATE model_connections
SET name = $1, description = $2, base_url = $3,
    api_key_ciphertext = $4, api_key_hint = $5,
    timeout_seconds = $6, enabled = $7, requests_per_minute = $8,
    max_concurrent_requests = $9,
    revision = revision + 1, updated_at = now()
WHERE id = $10
RETURNING id, name, description, base_url, api_key_ciphertext, api_key_hint, timeout_seconds, enabled, revision, created_by, created_at, updated_at, requests_per_minute, max_concurrent_requests
`

type UpdateConnectionParams struct {
	Name                  string
	Description           string
	BaseURL               string
	ApiKeyCiphertext      []byte
	ApiKeyHint            string
	TimeoutSeconds        int32
	Enabled               bool
	RequestsPerMinute     *int32
	MaxConcurrentRequests int32
	ID                    uuid.UUID
}

func (q *Queries) UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (ModelConnection, error) {
	row := q.db.QueryRow(ctx, updateConnection,
		arg.Name,
		arg.Description,
		arg.BaseURL,
		arg.ApiKeyCiphertext,
		arg.ApiKeyHint,
		arg.TimeoutSeconds,
		arg.Enabled,
		arg.RequestsPerMinute,
		arg.MaxConcurrentRequests,
		arg.ID,
	)
	var i ModelConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BaseURL,
		&i.ApiKeyCiphertext,
		&i.ApiKeyHint,
		&i.TimeoutSeconds,
		&i.Enabled,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequestsPerMinute,
		&i.MaxConcurrentRequests,
	)
	return i, err
}

const updateEmbeddingProfile = `-- name: UpdateEmbeddingProfile :one
UPDATE embedding_profiles
SET name = $1, description = $2, status = $3, is_default = $4,
    default_vector_weight = $5, default_keyword_weight = $6,
    revision = revision + 1, updated_at = now()
WHERE id = $7
RETURNING id, key, name, description, model_id, dimensions, storage_type, document_prefix, query_prefix, chunk_size, chunk_overlap, chunker_version, status, is_default, revision, created_by, created_at, updated_at, output_dimensions, default_vector_weight, default_keyword_weight
`

type UpdateEmbeddingProfileParams struct {
	Name                 string
	Description          string
	Status               string
	IsDefault            bool
	DefaultVectorWeight  *float64
	DefaultKeywordWeight *float64
	ID                   uuid.UUID
}

func (q *Queries) UpdateEmbeddingProfile(ctx context.Context, arg UpdateEmbeddingProfileParams) (EmbeddingProfile, error) {
	row := q.db.QueryRow(ctx, updateEmbeddingProfile,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.IsDefault,
		arg.DefaultVectorWeight,
		arg.DefaultKeywordWeight,
		arg.ID,
	)
	var i EmbeddingProfile
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.ModelID,
		&i.Dimensions,
		&i.StorageType,
		&i.DocumentPrefix,
		&i.QueryPrefix,
		&i.ChunkSize,
		&i.ChunkOverlap,
		&i.ChunkerVersion,
		&i.Status,
		&i.IsDefault,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutputDimensions,
		&i.DefaultVectorWeight,
		&i.DefaultKeywordWeight,
	)
	return i, err
}

const updateModel = `-- name: UpdateModel :one
UPDATE models
SET upstream_model = $1, display_name = $2, description = $3,
    max_classification = $4, enabled = $5,
    context_window = $6, max_output_tokens = $7,
    supports_tools = $8, supports_vision = $9,
    dimensions = $10, max_input_tokens = $11, compat = $12,
    moderation_provider = $13, moderation_family = $14,
    moderation_timeout_seconds = $15,
    revision = revision + 1, updated_at = now()
WHERE id = $16
RETURNING id, connection_id, key, upstream_model, display_name, description, kind, max_classification, enabled, context_window, max_output_tokens, supports_tools, supports_vision, dimensions, max_input_tokens, compat, revision, created_by, created_at, updated_at, moderation_provider, moderation_family, moderation_timeout_seconds
`

type UpdateModelParams struct {
	UpstreamModel            string
	DisplayName              string
	Description              string
	MaxClassification        string
	Enabled                  bool
	ContextWindow            *int32
	MaxOutputTokens          *int32
	SupportsTools            bool
	SupportsVision           bool
	Dimensions               *int32
	MaxInputTokens           *int32
	Compat                   json.RawMessage
	ModerationProvider       *string
	ModerationFamily         *string
	ModerationTimeoutSeconds *int32
	ID                       uuid.UUID
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, updateModel,
		arg.UpstreamModel,
		arg.DisplayName,
		arg.Description,
		arg.MaxClassification,
		arg.Enabled,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.SupportsTools,
		arg.SupportsVision,
		arg.Dimensions,
		arg.MaxInputTokens,
		arg.Compat,
		arg.ModerationProvider,
		arg.ModerationFamily,
		arg.ModerationTimeoutSeconds,
		arg.ID,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.Key,
		&i.UpstreamModel,
		&i.DisplayName,
		&i.Description,
		&i.Kind,
		&i.MaxClassification,
		&i.Enabled,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.SupportsTools,
		&i.SupportsVision,
		&i.Dimensions,
		&i.MaxInputTokens,
		&i.Compat,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModerationProvider,
		&i.ModerationFamily,
		&i.ModerationTimeoutSeconds,
	)
	return i, err
}
