// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getModerationPolicy = `-- name: GetModerationPolicy :one
SELECT audience, model_id, policy, revision, updated_by, updated_at FROM moderation_policies WHERE audience = $1
`

func (q *Queries) GetModerationPolicy(ctx context.Context, audience string) (ModerationPolicy, error) {
	row := q.db.QueryRow(ctx, getModerationPolicy, audience)
	var i ModerationPolicy
	err := row.Scan(
		&i.Audience,
		&i.ModelID,
		&i.Policy,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertModerationPolicy = `-- name: InsertModerationPolicy :one
INSERT INTO moderation_policies (audience, model_id, policy, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (audience) DO NOTHING
RETURNING audience, model_id, policy, revision, updated_by, updated_at
`

type InsertModerationPolicyParams struct {
	Audience  string
	ModelID   uuid.NullUUID
	Policy    json.RawMessage
	UpdatedBy uuid.NullUUID
}

func (q *Queries) InsertModerationPolicy(ctx context.Context, arg InsertModerationPolicyParams) (ModerationPolicy, error) {
	row := q.db.QueryRow(ctx, insertModerationPolicy,
		arg.Audience,
		arg.ModelID,
		arg.Policy,
		arg.UpdatedBy,
	)
	var i ModerationPolicy
	err := row.Scan(
		&i.Audience,
		&i.ModelID,
		&i.Policy,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const lockModerationPolicy = `-- name: LockModerationPolicy :one
SELECT audience, model_id, policy, revision, updated_by, updated_at FROM moderation_policies WHERE audience = $1 FOR UPDATE
`

func (q *Queries) LockModerationPolicy(ctx context.Context, audience string) (ModerationPolicy, error) {
	row := q.db.QueryRow(ctx, lockModerationPolicy, audience)
	var i ModerationPolicy
	err := row.Scan(
		&i.Audience,
		&i.ModelID,
		&i.Policy,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateModerationPolicy = `-- name: UpdateModerationPolicy :one
UPDATE moderation_policies
SET model_id = $1, policy = $2, updated_by = $3,
    revision = revision + 1, updated_at = now()
WHERE audience = $4
RETURNING audience, model_id, policy, revision, updated_by, updated_at
`

type UpdateModerationPolicyParams struct {
	ModelID   uuid.NullUUID
	Policy    json.RawMessage
	UpdatedBy uuid.NullUUID
	Audience  string
}

func (q *Queries) UpdateModerationPolicy(ctx context.Context, arg UpdateModerationPolicyParams) (ModerationPolicy, error) {
	row := q.db.QueryRow(ctx, updateModerationPolicy,
		arg.ModelID,
		arg.Policy,
		arg.UpdatedBy,
		arg.Audience,
	)
	var i ModerationPolicy
	err := row.Scan(
		&i.Audience,
		&i.ModelID,
		&i.Policy,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
