// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredOAuthCodes = `-- name: DeleteExpiredOAuthCodes :exec
DELETE FROM oauth_codes WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredOAuthCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthCodes)
	return err
}

const deleteExpiredOAuthTokens = `-- name: DeleteExpiredOAuthTokens :exec
DELETE FROM oauth_tokens WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredOAuthTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthTokens)
	return err
}

const deleteOAuthGrantTokens = `-- name: DeleteOAuthGrantTokens :exec
WITH codes AS (DELETE FROM oauth_codes c WHERE c.grant_id = $1)
DELETE FROM oauth_tokens t WHERE t.grant_id = $1
`

func (q *Queries) DeleteOAuthGrantTokens(ctx context.Context, grantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthGrantTokens, grantID)
	return err
}

const deleteOAuthToken = `-- name: DeleteOAuthToken :exec
DELETE FROM oauth_tokens WHERE id = $1
`

func (q *Queries) DeleteOAuthToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthToken, id)
	return err
}

const deleteUnusedOAuthClients = `-- name: DeleteUnusedOAuthClients :exec
DELETE FROM oauth_clients WHERE last_used_at <= $1
`

func (q *Queries) DeleteUnusedOAuthClients(ctx context.Context, unusedSince time.Time) error {
	_, err := q.db.Exec(ctx, deleteUnusedOAuthClients, unusedSince)
	return err
}

const getActiveOAuthGrant = `-- name: GetActiveOAuthGrant :one

SELECT id, user_id, client_id, client_kind, client_name, client_uri, resource, scopes, created_at, last_used_at, revoked_at, revoked_reason FROM oauth_grants WHERE user_id = $1 AND client_id = $2 AND revoked_at IS NULL
`

type GetActiveOAuthGrantParams struct {
	UserID   uuid.UUID
	ClientID string
}

// ---- grants (a person's consent for a client) ----------------------------------
func (q *Queries) GetActiveOAuthGrant(ctx context.Context, arg GetActiveOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, getActiveOAuthGrant, arg.UserID, arg.ClientID)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.ClientKind,
		&i.ClientName,
		&i.ClientUri,
		&i.Resource,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, client_id, client_name, redirect_uris, client_uri, logo_uri, created_at, last_used_at FROM oauth_clients WHERE client_id = $1 AND last_used_at > $2
`

type GetOAuthClientParams struct {
	ClientID    string
	UnusedSince time.Time
}

func (q *Queries) GetOAuthClient(ctx context.Context, arg GetOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, arg.ClientID, arg.UnusedSince)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.ClientUri,
		&i.LogoUri,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT t.id, t.grant_id, t.kind, t.token_hash, t.pepper_id, t.resource, t.expires_at, t.rotated_at, t.created_at, g.id, g.user_id, g.client_id, g.client_kind, g.client_name, g.client_uri, g.resource, g.scopes, g.created_at, g.last_used_at, g.revoked_at, g.revoked_reason, u.id, u.oidc_issuer, u.oidc_subject, u.email, u.display_name, u.platform_role, u.status, u.claims, u.created_at, u.updated_at, u.last_login_at, u.revision
FROM oauth_tokens t
JOIN oauth_grants g ON g.id = t.grant_id
JOIN users u ON u.id = g.user_id
WHERE t.token_hash = $1 AND t.kind = $2
`

type GetOAuthTokenParams struct {
	TokenHash []byte
	Kind      string
}

type GetOAuthTokenRow struct {
	OauthToken OauthToken
	OauthGrant OauthGrant
	User       User
}

// GetOAuthToken is a token with its grant and the grant's person.
func (q *Queries) GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (GetOAuthTokenRow, error) {
	row := q.db.QueryRow(ctx, getOAuthToken, arg.TokenHash, arg.Kind)
	var i GetOAuthTokenRow
	err := row.Scan(
		&i.OauthToken.ID,
		&i.OauthToken.GrantID,
		&i.OauthToken.Kind,
		&i.OauthToken.TokenHash,
		&i.OauthToken.PepperID,
		&i.OauthToken.Resource,
		&i.OauthToken.ExpiresAt,
		&i.OauthToken.RotatedAt,
		&i.OauthToken.CreatedAt,
		&i.OauthGrant.ID,
		&i.OauthGrant.UserID,
		&i.OauthGrant.ClientID,
		&i.OauthGrant.ClientKind,
		&i.OauthGrant.ClientName,
		&i.OauthGrant.ClientUri,
		&i.OauthGrant.Resource,
		&i.OauthGrant.Scopes,
		&i.OauthGrant.CreatedAt,
		&i.OauthGrant.LastUsedAt,
		&i.OauthGrant.RevokedAt,
		&i.OauthGrant.RevokedReason,
		&i.User.ID,
		&i.User.OIDCIssuer,
		&i.User.OIDCSubject,
		&i.User.Email,
		&i.User.DisplayName,
		&i.User.PlatformRole,
		&i.User.Status,
		&i.User.Claims,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.LastLoginAt,
		&i.User.Revision,
	)
	return i, err
}

const insertOAuthClient = `-- name: InsertOAuthClient :one


INSERT INTO oauth_clients (client_id, client_name, redirect_uris, client_uri, logo_uri)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, client_id, client_name, redirect_uris, client_uri, logo_uri, created_at, last_used_at
`

type InsertOAuthClientParams struct {
	ClientID     string
	ClientName   string
	RedirectUris []string
	ClientUri    *string
	LogoUri      *string
}

// OAuth sign-in for MCP clients (migrations/00038_mcp_oauth.sql, docs/mcp.md).
// ---- registered clients (RFC 7591) ---------------------------------------------
func (q *Queries) InsertOAuthClient(ctx context.Context, arg InsertOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, insertOAuthClient,
		arg.ClientID,
		arg.ClientName,
		arg.RedirectUris,
		arg.ClientUri,
		arg.LogoUri,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.ClientUri,
		&i.LogoUri,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertOAuthCode = `-- name: InsertOAuthCode :exec

INSERT INTO oauth_codes (code_hash, grant_id, client_id, redirect_uri, code_challenge, resource, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOAuthCodeParams struct {
	CodeHash      []byte
	GrantID       uuid.UUID
	ClientID      string
	RedirectUri   string
	CodeChallenge string
	Resource      string
	ExpiresAt     time.Time
}

// ---- authorization codes --------------------------------------------------------
func (q *Queries) InsertOAuthCode(ctx context.Context, arg InsertOAuthCodeParams) error {
	_, err := q.db.Exec(ctx, insertOAuthCode,
		arg.CodeHash,
		arg.GrantID,
		arg.ClientID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.Resource,
		arg.ExpiresAt,
	)
	return err
}

const insertOAuthGrant = `-- name: InsertOAuthGrant :one
INSERT INTO oauth_grants (user_id, client_id, client_kind, client_name, client_uri, resource)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, client_id, client_kind, client_name, client_uri, resource, scopes, created_at, last_used_at, revoked_at, revoked_reason
`

type InsertOAuthGrantParams struct {
	UserID     uuid.UUID
	ClientID   string
	ClientKind string
	ClientName string
	ClientUri  *string
	Resource   string
}

func (q *Queries) InsertOAuthGrant(ctx context.Context, arg InsertOAuthGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, insertOAuthGrant,
		arg.UserID,
		arg.ClientID,
		arg.ClientKind,
		arg.ClientName,
		arg.ClientUri,
		arg.Resource,
	)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.ClientKind,
		&i.ClientName,
		&i.ClientUri,
		&i.Resource,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const insertOAuthToken = `-- name: InsertOAuthToken :one

INSERT INTO oauth_tokens (grant_id, kind, token_hash, pepper_id, resource, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, grant_id, kind, token_hash, pepper_id, resource, expires_at, rotated_at, created_at
`

type InsertOAuthTokenParams struct {
	GrantID   uuid.UUID
	Kind      string
	TokenHash []byte
	PepperID  []byte
	Resource  string
	ExpiresAt time.Time
}

// ---- access and refresh tokens --------------------------------------------------
func (q *Queries) InsertOAuthToken(ctx context.Context, arg InsertOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRow(ctx, insertOAuthToken,
		arg.GrantID,
		arg.Kind,
		arg.TokenHash,
		arg.PepperID,
		arg.Resource,
		arg.ExpiresAt,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.Kind,
		&i.TokenHash,
		&i.PepperID,
		&i.Resource,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserOAuthGrants = `-- name: ListUserOAuthGrants :many
SELECT id, user_id, client_id, client_kind, client_name, client_uri, resource, scopes, created_at, last_used_at, revoked_at, revoked_reason FROM oauth_grants WHERE user_id = $1 AND revoked_at IS NULL ORDER BY created_at DESC, id
`

func (q *Queries) ListUserOAuthGrants(ctx context.Context, userID uuid.UUID) ([]OauthGrant, error) {
	rows, err := q.db.Query(ctx, listUserOAuthGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthGrant{}
	for rows.Next() {
		var i OauthGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.ClientKind,
			&i.ClientName,
			&i.ClientUri,
			&i.Resource,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOAuthGrant = `-- name: LockOAuthGrant :one
SELECT id, user_id, client_id, client_kind, client_name, client_uri, resource, scopes, created_at, last_used_at, revoked_at, revoked_reason FROM oauth_grants WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockOAuthGrant(ctx context.Context, id uuid.UUID) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, lockOAuthGrant, id)
	var i OauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.ClientKind,
		&i.ClientName,
		&i.ClientUri,
		&i.Resource,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const lockOAuthToken = `-- name: LockOAuthToken :one
SELECT id, grant_id, kind, token_hash, pepper_id, resource, expires_at, rotated_at, created_at FROM oauth_tokens WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockOAuthToken(ctx context.Context, id uuid.UUID) (OauthToken, error) {
	row := q.db.QueryRow(ctx, lockOAuthToken, id)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.Kind,
		&i.TokenHash,
		&i.PepperID,
		&i.Resource,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeOAuthGrant = `-- name: RevokeOAuthGrant :execrows
UPDATE oauth_grants SET revoked_at = now(), revoked_reason = $1 WHERE id = $2 AND revoked_at IS NULL
`

type RevokeOAuthGrantParams struct {
	Reason *string
	ID     uuid.UUID
}

func (q *Queries) RevokeOAuthGrant(ctx context.Context, arg RevokeOAuthGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOAuthGrant, arg.Reason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateOAuthToken = `-- name: RotateOAuthToken :execrows
UPDATE oauth_tokens SET rotated_at = now() WHERE id = $1 AND rotated_at IS NULL
`

func (q *Queries) RotateOAuthToken(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, rotateOAuthToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeOAuthCode = `-- name: TakeOAuthCode :one
DELETE FROM oauth_codes WHERE code_hash = $1 RETURNING code_hash, grant_id, client_id, redirect_uri, code_challenge, resource, expires_at, created_at
`

// TakeOAuthCode consumes a code: a second exchange finds nothing.
func (q *Queries) TakeOAuthCode(ctx context.Context, codeHash []byte) (OauthCode, error) {
	row := q.db.QueryRow(ctx, takeOAuthCode, codeHash)
	var i OauthCode
	err := row.Scan(
		&i.CodeHash,
		&i.GrantID,
		&i.ClientID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.Resource,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchOAuthClient = `-- name: TouchOAuthClient :exec
UPDATE oauth_clients SET last_used_at = now()
WHERE client_id = $1 AND last_used_at < now() - interval '1 hour'
`

func (q *Queries) TouchOAuthClient(ctx context.Context, clientID string) error {
	_, err := q.db.Exec(ctx, touchOAuthClient, clientID)
	return err
}

const touchOAuthGrant = `-- name: TouchOAuthGrant :exec
UPDATE oauth_grants SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchOAuthGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchOAuthGrant, id)
	return err
}
