// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ocr.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countNeedsOCRByTeam = `-- name: CountNeedsOCRByTeam :many
SELECT d.team_id, coalesce(t.slug, '')::text AS team_slug, coalesce(t.name, '')::text AS team_name, count(*)::bigint AS documents
FROM documents d LEFT JOIN teams t ON t.id = d.team_id
WHERE d.error_code = 'needs_ocr'
GROUP BY d.team_id, t.slug, t.name
ORDER BY count(*) DESC, t.slug NULLS LAST
`

type CountNeedsOCRByTeamRow struct {
	TeamID    uuid.NullUUID
	TeamSlug  string
	TeamName  string
	Documents int64
}

// Documents skipped as scanned, per team (NULL: platform-shared sources).
func (q *Queries) CountNeedsOCRByTeam(ctx context.Context) ([]CountNeedsOCRByTeamRow, error) {
	rows, err := q.db.Query(ctx, countNeedsOCRByTeam)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNeedsOCRByTeamRow{}
	for rows.Next() {
		var i CountNeedsOCRByTeamRow
		if err := rows.Scan(
			&i.TeamID,
			&i.TeamSlug,
			&i.TeamName,
			&i.Documents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParsingSettings = `-- name: GetParsingSettings :one

SELECT singleton, ocr_enabled, ocr_backend, vision_model_id, languages, revision, updated_by, updated_at FROM parsing_settings WHERE singleton
`

// OCR for scanned documents (docs/ocr.md): Admin -> Parsing, documents
// waiting for the daily OCR page limit, and retrying scanned documents.
func (q *Queries) GetParsingSettings(ctx context.Context) (ParsingSetting, error) {
	row := q.db.QueryRow(ctx, getParsingSettings)
	var i ParsingSetting
	err := row.Scan(
		&i.Singleton,
		&i.OcrEnabled,
		&i.OcrBackend,
		&i.VisionModelID,
		&i.Languages,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertParsingSettings = `-- name: InsertParsingSettings :one
INSERT INTO parsing_settings (ocr_enabled, ocr_backend, vision_model_id, languages, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (singleton) DO NOTHING
RETURNING singleton, ocr_enabled, ocr_backend, vision_model_id, languages, revision, updated_by, updated_at
`

type InsertParsingSettingsParams struct {
	OcrEnabled    bool
	OcrBackend    string
	VisionModelID uuid.NullUUID
	Languages     string
	UpdatedBy     uuid.NullUUID
}

func (q *Queries) InsertParsingSettings(ctx context.Context, arg InsertParsingSettingsParams) (ParsingSetting, error) {
	row := q.db.QueryRow(ctx, insertParsingSettings,
		arg.OcrEnabled,
		arg.OcrBackend,
		arg.VisionModelID,
		arg.Languages,
		arg.UpdatedBy,
	)
	var i ParsingSetting
	err := row.Scan(
		&i.Singleton,
		&i.OcrEnabled,
		&i.OcrBackend,
		&i.VisionModelID,
		&i.Languages,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const lockParsingSettings = `-- name: LockParsingSettings :one
SELECT singleton, ocr_enabled, ocr_backend, vision_model_id, languages, revision, updated_by, updated_at FROM parsing_settings WHERE singleton FOR UPDATE
`

func (q *Queries) LockParsingSettings(ctx context.Context) (ParsingSetting, error) {
	row := q.db.QueryRow(ctx, lockParsingSettings)
	var i ParsingSetting
	err := row.Scan(
		&i.Singleton,
		&i.OcrEnabled,
		&i.OcrBackend,
		&i.VisionModelID,
		&i.Languages,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const retryDocumentsByError = `-- name: RetryDocumentsByError :many
UPDATE documents
SET status = 'pending', error_code = '', error_message = '', attempts = 0, waiting_until = NULL, updated_at = now()
WHERE source_id = $1 AND error_code = $2 AND status IN ('failed', 'skipped')
RETURNING id
`

type RetryDocumentsByErrorParams struct {
	SourceID  uuid.UUID
	ErrorCode string
}

// Retry of a source's failed or skipped documents with one error code
// (e.g. needs_ocr, once OCR is on).
func (q *Queries) RetryDocumentsByError(ctx context.Context, arg RetryDocumentsByErrorParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, retryDocumentsByError, arg.SourceID, arg.ErrorCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocumentOCR = `-- name: SetDocumentOCR :exec
UPDATE documents
SET metadata = CASE WHEN $1::jsonb = 'null'::jsonb THEN metadata - 'ocr' ELSE jsonb_set(metadata, '{ocr}', $1::jsonb) END
WHERE id = $2
`

type SetDocumentOCRParams struct {
	Ocr json.RawMessage
	ID  uuid.UUID
}

// Records the pages read with OCR (metadata.ocr), or removes the record
// when ocr is JSON null.
func (q *Queries) SetDocumentOCR(ctx context.Context, arg SetDocumentOCRParams) error {
	_, err := q.db.Exec(ctx, setDocumentOCR, arg.Ocr, arg.ID)
	return err
}

const setSourceOCR = `-- name: SetSourceOCR :exec
UPDATE data_sources SET ocr_enabled = $1 WHERE id = $2
`

type SetSourceOCRParams struct {
	OcrEnabled bool
	ID         uuid.UUID
}

func (q *Queries) SetSourceOCR(ctx context.Context, arg SetSourceOCRParams) error {
	_, err := q.db.Exec(ctx, setSourceOCR, arg.OcrEnabled, arg.ID)
	return err
}

const updateParsingSettings = `-- name: UpdateParsingSettings :one
UPDATE parsing_settings
SET ocr_enabled = $1, ocr_backend = $2, vision_model_id = $3,
    languages = $4, updated_by = $5, revision = revision + 1, updated_at = now()
WHERE singleton
RETURNING singleton, ocr_enabled, ocr_backend, vision_model_id, languages, revision, updated_by, updated_at
`

type UpdateParsingSettingsParams struct {
	OcrEnabled    bool
	OcrBackend    string
	VisionModelID uuid.NullUUID
	Languages     string
	UpdatedBy     uuid.NullUUID
}

func (q *Queries) UpdateParsingSettings(ctx context.Context, arg UpdateParsingSettingsParams) (ParsingSetting, error) {
	row := q.db.QueryRow(ctx, updateParsingSettings,
		arg.OcrEnabled,
		arg.OcrBackend,
		arg.VisionModelID,
		arg.Languages,
		arg.UpdatedBy,
	)
	var i ParsingSetting
	err := row.Scan(
		&i.Singleton,
		&i.OcrEnabled,
		&i.OcrBackend,
		&i.VisionModelID,
		&i.Languages,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const waitDocument = `-- name: WaitDocument :execrows
UPDATE documents
SET status = 'pending', waiting_until = $1, attempts = greatest(attempts - 1, 0),
    error_code = $2, error_message = $3, updated_at = now()
WHERE id = $4 AND status = 'processing'
`

type WaitDocumentParams struct {
	WaitingUntil *time.Time
	ErrorCode    string
	ErrorMessage string
	ID           uuid.UUID
}

// A document whose OCR would pass the team's daily page limit goes back to
// pending and waits until @waiting_until (or until the limit is raised).
// Like a snooze, the attempt doesn't count.
func (q *Queries) WaitDocument(ctx context.Context, arg WaitDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, waitDocument,
		arg.WaitingUntil,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wakeDueDocuments = `-- name: WakeDueDocuments :execrows
UPDATE documents SET waiting_until = NULL, error_code = '', error_message = '', updated_at = now()
WHERE status = 'pending' AND waiting_until IS NOT NULL AND waiting_until <= now()
`

// Waiting documents whose time has come are pending again.
func (q *Queries) WakeDueDocuments(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, wakeDueDocuments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wakeWaitingDocuments = `-- name: WakeWaitingDocuments :execrows
UPDATE documents SET waiting_until = NULL, error_code = '', error_message = '', updated_at = now()
WHERE status = 'pending' AND waiting_until IS NOT NULL AND error_code = $1
  AND ($2::uuid IS NULL OR team_id = $2::uuid)
`

type WakeWaitingDocumentsParams struct {
	ErrorCode string
	TeamID    uuid.NullUUID
}

// A team's documents waiting for a daily limit (every team's when team_id
// is NULL) check it again: the limit changed.
func (q *Queries) WakeWaitingDocuments(ctx context.Context, arg WakeWaitingDocumentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, wakeWaitingDocuments, arg.ErrorCode, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
