// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rerank.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countRerankAgents = `-- name: CountRerankAgents :one
SELECT count(*)::int
FROM agents a
JOIN teams t ON t.id = a.team_id
JOIN agent_versions v ON v.id = a.published_version_id
WHERE a.deleted_at IS NULL AND a.status = 'active' AND t.status = 'active'
  AND coalesce((v.config->>'rerank')::boolean, true)
`

// Published, active agents in active teams that rerank (their published
// version doesn't turn it off; docs/v0.4.0.md §3).
func (q *Queries) CountRerankAgents(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countRerankAgents)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getRerankSettings = `-- name: GetRerankSettings :one
SELECT singleton, model_id, settings, revision, updated_by, updated_at FROM rerank_settings WHERE singleton
`

func (q *Queries) GetRerankSettings(ctx context.Context) (RerankSetting, error) {
	row := q.db.QueryRow(ctx, getRerankSettings)
	var i RerankSetting
	err := row.Scan(
		&i.Singleton,
		&i.ModelID,
		&i.Settings,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRerankSettings = `-- name: InsertRerankSettings :one
INSERT INTO rerank_settings (model_id, settings, updated_by)
VALUES ($1, $2, $3)
ON CONFLICT (singleton) DO NOTHING
RETURNING singleton, model_id, settings, revision, updated_by, updated_at
`

type InsertRerankSettingsParams struct {
	ModelID   uuid.NullUUID
	Settings  json.RawMessage
	UpdatedBy uuid.NullUUID
}

func (q *Queries) InsertRerankSettings(ctx context.Context, arg InsertRerankSettingsParams) (RerankSetting, error) {
	row := q.db.QueryRow(ctx, insertRerankSettings, arg.ModelID, arg.Settings, arg.UpdatedBy)
	var i RerankSetting
	err := row.Scan(
		&i.Singleton,
		&i.ModelID,
		&i.Settings,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listRerankOffAgents = `-- name: ListRerankOffAgents :many
SELECT a.id, a.name, t.slug AS team_slug, t.name AS team_name
FROM agents a
JOIN teams t ON t.id = a.team_id
JOIN agent_versions v ON v.id = a.published_version_id
WHERE a.deleted_at IS NULL AND a.status = 'active' AND t.status = 'active'
  AND NOT coalesce((v.config->>'rerank')::boolean, true)
ORDER BY t.name, a.name
LIMIT 100
`

type ListRerankOffAgentsRow struct {
	ID       uuid.UUID
	Name     string
	TeamSlug string
	TeamName string
}

// Published, active agents in active teams whose published version turns
// reranking off (Admin → Models → Reranking lists them, docs/v0.4.2.md OW-2).
func (q *Queries) ListRerankOffAgents(ctx context.Context) ([]ListRerankOffAgentsRow, error) {
	rows, err := q.db.Query(ctx, listRerankOffAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRerankOffAgentsRow{}
	for rows.Next() {
		var i ListRerankOffAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamSlug,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRerankSettings = `-- name: LockRerankSettings :one
SELECT singleton, model_id, settings, revision, updated_by, updated_at FROM rerank_settings WHERE singleton FOR UPDATE
`

func (q *Queries) LockRerankSettings(ctx context.Context) (RerankSetting, error) {
	row := q.db.QueryRow(ctx, lockRerankSettings)
	var i RerankSetting
	err := row.Scan(
		&i.Singleton,
		&i.ModelID,
		&i.Settings,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRerankSettings = `-- name: UpdateRerankSettings :one
UPDATE rerank_settings
SET model_id = $1, settings = $2, updated_by = $3,
    revision = revision + 1, updated_at = now()
WHERE singleton
RETURNING singleton, model_id, settings, revision, updated_by, updated_at
`

type UpdateRerankSettingsParams struct {
	ModelID   uuid.NullUUID
	Settings  json.RawMessage
	UpdatedBy uuid.NullUUID
}

func (q *Queries) UpdateRerankSettings(ctx context.Context, arg UpdateRerankSettingsParams) (RerankSetting, error) {
	row := q.db.QueryRow(ctx, updateRerankSettings, arg.ModelID, arg.Settings, arg.UpdatedBy)
	var i RerankSetting
	err := row.Scan(
		&i.Singleton,
		&i.ModelID,
		&i.Settings,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
