// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const searchAgents = `-- name: SearchAgents :many

SELECT a.id, a.name, a.slug, t.slug AS team_slug, t.name AS team_name,
       (tm.user_id IS NOT NULL)::bool AS member,
       (a.published_version_id IS NOT NULL AND a.status = 'active' AND t.status = 'active')::bool AS chat,
       (CASE WHEN a.name ILIKE $1::text THEN 0 WHEN a.name ~* $2::text THEN 1 WHEN a.name ILIKE $3::text THEN 2 ELSE 3 END)::int AS rank
FROM agents a
JOIN teams t ON t.id = a.team_id
LEFT JOIN team_members tm ON tm.team_id = a.team_id AND tm.user_id = $4::uuid
LEFT JOIN agent_audience_grants g ON g.agent_id = a.id
WHERE a.deleted_at IS NULL AND (a.name ILIKE $3::text OR a.description ILIKE $3::text)
  AND (tm.user_id IS NOT NULL
       OR (a.published_version_id IS NOT NULL AND a.status = 'active' AND t.status = 'active'
           AND (g.principal_type = 'all_authenticated' OR (g.principal_type = 'public' AND $5::bool))))
ORDER BY rank, length(a.name), lower(a.name), a.id
LIMIT $6
`

type SearchAgentsParams struct {
	Prefix        string
	Word          string
	Contains      string
	UserID        uuid.UUID
	PublicEnabled bool
	Lim           int32
}

type SearchAgentsRow struct {
	ID       uuid.UUID
	Name     string
	Slug     string
	TeamSlug string
	TeamName string
	Member   bool
	Chat     bool
	Rank     int32
}

// ---- everyone --------------------------------------------------------------------
// Agents the user may open or chat with: every agent of the user's teams
// (members see their team's agents), and the published, active agents of
// active teams they may chat with as the directory lists them
// (all_authenticated, or public while the public switch is on). The name or
// the description matches; a match in the description only ranks 3, after
// every name match. The description has no trigram index: agents are few
// (one row per configured agent, not per user or document), so the scan is
// cheap, and the name index can't serve an OR with it anyway.
func (q *Queries) SearchAgents(ctx context.Context, arg SearchAgentsParams) ([]SearchAgentsRow, error) {
	rows, err := q.db.Query(ctx, searchAgents,
		arg.Prefix,
		arg.Word,
		arg.Contains,
		arg.UserID,
		arg.PublicEnabled,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAgentsRow{}
	for rows.Next() {
		var i SearchAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.TeamSlug,
			&i.TeamName,
			&i.Member,
			&i.Chat,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchConnections = `-- name: SearchConnections :many
SELECT c.id, c.name, c.base_url, c.enabled,
       (CASE WHEN c.name ILIKE $1::text THEN 0 WHEN c.name ~* $2::text THEN 1 ELSE 2 END)::int AS rank
FROM model_connections c
WHERE c.name ILIKE $3::text
ORDER BY rank, length(c.name), lower(c.name), c.id
LIMIT $4
`

type SearchConnectionsParams struct {
	Prefix   string
	Word     string
	Contains string
	Lim      int32
}

type SearchConnectionsRow struct {
	ID      uuid.UUID
	Name    string
	BaseURL string
	Enabled bool
	Rank    int32
}

func (q *Queries) SearchConnections(ctx context.Context, arg SearchConnectionsParams) ([]SearchConnectionsRow, error) {
	rows, err := q.db.Query(ctx, searchConnections,
		arg.Prefix,
		arg.Word,
		arg.Contains,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchConnectionsRow{}
	for rows.Next() {
		var i SearchConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseURL,
			&i.Enabled,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchConversations = `-- name: SearchConversations :many
SELECT c.id, c.title, c.updated_at, a.name AS agent_name, a.slug AS agent_slug, t.slug AS team_slug,
       (a.deleted_at IS NOT NULL)::bool AS agent_deleted,
       (CASE WHEN c.title ILIKE $1::text THEN 0 WHEN c.title ~* $2::text THEN 1 ELSE 2 END)::int AS rank
FROM conversations c
JOIN agents a ON a.id = c.agent_id
JOIN teams t ON t.id = a.team_id
WHERE c.user_id = $3::uuid AND c.deleted_at IS NULL AND c.title ILIKE $4::text
ORDER BY rank, c.updated_at DESC, c.id DESC
LIMIT $5
`

type SearchConversationsParams struct {
	Prefix   string
	Word     string
	UserID   uuid.UUID
	Contains string
	Lim      int32
}

type SearchConversationsRow struct {
	ID           uuid.UUID
	Title        string
	UpdatedAt    time.Time
	AgentName    string
	AgentSlug    string
	TeamSlug     string
	AgentDeleted bool
	Rank         int32
}

// The user's own conversations by title (never anyone else's; deleted
// ones are gone), most recent first within a rank.
func (q *Queries) SearchConversations(ctx context.Context, arg SearchConversationsParams) ([]SearchConversationsRow, error) {
	rows, err := q.db.Query(ctx, searchConversations,
		arg.Prefix,
		arg.Word,
		arg.UserID,
		arg.Contains,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchConversationsRow{}
	for rows.Next() {
		var i SearchConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UpdatedAt,
			&i.AgentName,
			&i.AgentSlug,
			&i.TeamSlug,
			&i.AgentDeleted,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDataSources = `-- name: SearchDataSources :many
SELECT s.id, s.name, s.type, s.status, t.slug AS team_slug, t.name AS team_name,
       (CASE WHEN s.name ILIKE $1::text THEN 0 WHEN s.name ~* $2::text THEN 1 ELSE 2 END)::int AS rank
FROM data_sources s
JOIN team_members tm ON tm.team_id = s.team_id AND tm.user_id = $3::uuid
JOIN teams t ON t.id = s.team_id
WHERE s.name ILIKE $4::text
ORDER BY rank, length(s.name), lower(s.name), s.id
LIMIT $5
`

type SearchDataSourcesParams struct {
	Prefix   string
	Word     string
	UserID   uuid.UUID
	Contains string
	Lim      int32
}

type SearchDataSourcesRow struct {
	ID       uuid.UUID
	Name     string
	Type     string
	Status   string
	TeamSlug string
	TeamName string
	Rank     int32
}

// The data sources of the user's teams (shared sources are platform
// objects, searched by staff).
func (q *Queries) SearchDataSources(ctx context.Context, arg SearchDataSourcesParams) ([]SearchDataSourcesRow, error) {
	rows, err := q.db.Query(ctx, searchDataSources,
		arg.Prefix,
		arg.Word,
		arg.UserID,
		arg.Contains,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDataSourcesRow{}
	for rows.Next() {
		var i SearchDataSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.TeamSlug,
			&i.TeamName,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEmbeddingProfiles = `-- name: SearchEmbeddingProfiles :many
SELECT p.id, p.name, p.key, p.status,
       LEAST(CASE WHEN p.name ILIKE $1::text THEN 0 WHEN p.name ~* $2::text THEN 1 ELSE 2 END,
             CASE WHEN p.key ILIKE $1::text THEN 0 WHEN p.key ~* $2::text THEN 1 ELSE 2 END)::int AS rank
FROM embedding_profiles p
WHERE p.name ILIKE $3::text OR p.key ILIKE $3::text
ORDER BY rank, length(p.name), lower(p.name), p.id
LIMIT $4
`

type SearchEmbeddingProfilesParams struct {
	Prefix   string
	Word     string
	Contains string
	Lim      int32
}

type SearchEmbeddingProfilesRow struct {
	ID     uuid.UUID
	Name   string
	Key    string
	Status string
	Rank   int32
}

func (q *Queries) SearchEmbeddingProfiles(ctx context.Context, arg SearchEmbeddingProfilesParams) ([]SearchEmbeddingProfilesRow, error) {
	rows, err := q.db.Query(ctx, searchEmbeddingProfiles,
		arg.Prefix,
		arg.Word,
		arg.Contains,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEmbeddingProfilesRow{}
	for rows.Next() {
		var i SearchEmbeddingProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Key,
			&i.Status,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKnowledgeBases = `-- name: SearchKnowledgeBases :many
SELECT kb.id, kb.name, t.slug AS team_slug, t.name AS team_name,
       (CASE WHEN kb.name ILIKE $1::text THEN 0 WHEN kb.name ~* $2::text THEN 1 ELSE 2 END)::int AS rank
FROM knowledge_bases kb
JOIN team_members tm ON tm.team_id = kb.team_id AND tm.user_id = $3::uuid
JOIN teams t ON t.id = kb.team_id
WHERE kb.name ILIKE $4::text
ORDER BY rank, length(kb.name), lower(kb.name), kb.id
LIMIT $5
`

type SearchKnowledgeBasesParams struct {
	Prefix   string
	Word     string
	UserID   uuid.UUID
	Contains string
	Lim      int32
}

type SearchKnowledgeBasesRow struct {
	ID       uuid.UUID
	Name     string
	TeamSlug string
	TeamName string
	Rank     int32
}

// The knowledge bases of the user's teams.
func (q *Queries) SearchKnowledgeBases(ctx context.Context, arg SearchKnowledgeBasesParams) ([]SearchKnowledgeBasesRow, error) {
	rows, err := q.db.Query(ctx, searchKnowledgeBases,
		arg.Prefix,
		arg.Word,
		arg.UserID,
		arg.Contains,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchKnowledgeBasesRow{}
	for rows.Next() {
		var i SearchKnowledgeBasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamSlug,
			&i.TeamName,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchModels = `-- name: SearchModels :many
SELECT m.id, m.display_name, m.key, m.kind, m.enabled,
       LEAST(CASE WHEN m.display_name ILIKE $1::text THEN 0 WHEN m.display_name ~* $2::text THEN 1 ELSE 2 END,
             CASE WHEN m.key ILIKE $1::text THEN 0 WHEN m.key ~* $2::text THEN 1 ELSE 2 END)::int AS rank
FROM models m
WHERE m.display_name ILIKE $3::text OR m.key ILIKE $3::text
ORDER BY rank, length(m.display_name), lower(m.display_name), m.id
LIMIT $4
`

type SearchModelsParams struct {
	Prefix   string
	Word     string
	Contains string
	Lim      int32
}

type SearchModelsRow struct {
	ID          uuid.UUID
	DisplayName string
	Key         string
	Kind        string
	Enabled     bool
	Rank        int32
}

func (q *Queries) SearchModels(ctx context.Context, arg SearchModelsParams) ([]SearchModelsRow, error) {
	rows, err := q.db.Query(ctx, searchModels,
		arg.Prefix,
		arg.Word,
		arg.Contains,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchModelsRow{}
	for rows.Next() {
		var i SearchModelsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Key,
			&i.Kind,
			&i.Enabled,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSharedSources = `-- name: SearchSharedSources :many
SELECT s.id, s.name, s.type, s.status,
       (CASE WHEN s.name ILIKE $1::text THEN 0 WHEN s.name ~* $2::text THEN 1 ELSE 2 END)::int AS rank
FROM data_sources s
WHERE s.team_id IS NULL AND s.name ILIKE $3::text
ORDER BY rank, length(s.name), lower(s.name), s.id
LIMIT $4
`

type SearchSharedSourcesParams struct {
	Prefix   string
	Word     string
	Contains string
	Lim      int32
}

type SearchSharedSourcesRow struct {
	ID     uuid.UUID
	Name   string
	Type   string
	Status string
	Rank   int32
}

func (q *Queries) SearchSharedSources(ctx context.Context, arg SearchSharedSourcesParams) ([]SearchSharedSourcesRow, error) {
	rows, err := q.db.Query(ctx, searchSharedSources,
		arg.Prefix,
		arg.Word,
		arg.Contains,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSharedSourcesRow{}
	for rows.Next() {
		var i SearchSharedSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTeams = `-- name: SearchTeams :many


SELECT t.id, t.slug, t.name, t.status,
       (CASE WHEN t.name ILIKE $1::text THEN 0 WHEN t.name ~* $2::text THEN 1 ELSE 2 END)::int AS rank
FROM teams t
WHERE t.name ILIKE $3::text
ORDER BY rank, length(t.name), lower(t.name), t.id
LIMIT $4
`

type SearchTeamsParams struct {
	Prefix   string
	Word     string
	Contains string
	Lim      int32
}

type SearchTeamsRow struct {
	ID     uuid.UUID
	Slug   string
	Name   string
	Status string
	Rank   int32
}

// The command palette's object search (GET /v1/search, internal/search).
// Every query takes the same three patterns, built from the caller's text:
//
//	@contains  '%text%' (ILIKE, escaped): the filter, served by the trigram
//	           indexes of 00030
//	@prefix    'text%'  (ILIKE, escaped): rank 0
//	@word      '\mtext' (a case-insensitive regex, quoted): rank 1, a word
//	           of the name starts with the text
//
// anything else that contains the text ranks 2 (an agent whose description
// alone matches ranks 3). Each query returns its best @lim rows; the service
// merges them.
// ---- platform staff (admins and auditors) --------------------------------------
func (q *Queries) SearchTeams(ctx context.Context, arg SearchTeamsParams) ([]SearchTeamsRow, error) {
	rows, err := q.db.Query(ctx, searchTeams,
		arg.Prefix,
		arg.Word,
		arg.Contains,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTeamsRow{}
	for rows.Next() {
		var i SearchTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT u.id, u.email, u.display_name, u.status,
       LEAST(CASE WHEN u.display_name ILIKE $1::text THEN 0 WHEN u.display_name ~* $2::text THEN 1 ELSE 2 END,
             CASE WHEN u.email::text ILIKE $1::text THEN 0 WHEN u.email::text ~* $2::text THEN 1 ELSE 2 END)::int AS rank
FROM users u
WHERE (u.display_name || ' ' || u.email::text) ILIKE $3::text
ORDER BY rank, length(coalesce(nullif(u.display_name, ''), u.email::text)), lower(u.display_name), u.email, u.id
LIMIT $4
`

type SearchUsersParams struct {
	Prefix   string
	Word     string
	Contains string
	Lim      int32
}

type SearchUsersRow struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	Status      string
	Rank        int32
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Prefix,
		arg.Word,
		arg.Contains,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
