// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssogroups.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countSSORules = `-- name: CountSSORules :one
SELECT count(*) FROM sso_group_rules
`

func (q *Queries) CountSSORules(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSSORules)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSSOMembership = `-- name: DeleteSSOMembership :exec
DELETE FROM sso_memberships WHERE team_id = $1 AND user_id = $2
`

type DeleteSSOMembershipParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

// A hand change takes a membership over from the mapping.
func (q *Queries) DeleteSSOMembership(ctx context.Context, arg DeleteSSOMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteSSOMembership, arg.TeamID, arg.UserID)
	return err
}

const deleteSSORule = `-- name: DeleteSSORule :exec
DELETE FROM sso_group_rules WHERE id = $1
`

func (q *Queries) DeleteSSORule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSSORule, id)
	return err
}

const getSSOMembership = `-- name: GetSSOMembership :one
SELECT s.rule_id, r.group_name
FROM sso_memberships s
LEFT JOIN sso_group_rules r ON r.id = s.rule_id
WHERE s.team_id = $1 AND s.user_id = $2
`

type GetSSOMembershipParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

type GetSSOMembershipRow struct {
	RuleID    uuid.NullUUID
	GroupName *string
}

func (q *Queries) GetSSOMembership(ctx context.Context, arg GetSSOMembershipParams) (GetSSOMembershipRow, error) {
	row := q.db.QueryRow(ctx, getSSOMembership, arg.TeamID, arg.UserID)
	var i GetSSOMembershipRow
	err := row.Scan(&i.RuleID, &i.GroupName)
	return i, err
}

const getSSORuleForUpdate = `-- name: GetSSORuleForUpdate :one
SELECT id, group_name, team_id, role, created_by, revision, created_at, updated_at FROM sso_group_rules WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSSORuleForUpdate(ctx context.Context, id uuid.UUID) (SsoGroupRule, error) {
	row := q.db.QueryRow(ctx, getSSORuleForUpdate, id)
	var i SsoGroupRule
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.TeamID,
		&i.Role,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSSORuleView = `-- name: GetSSORuleView :one
SELECT r.id, r.group_name, r.team_id, r.role, r.created_by, r.revision, r.created_at, r.updated_at, t.slug AS team_slug, t.name AS team_name, t.status AS team_status,
       (SELECT count(*) FROM sso_memberships s WHERE s.rule_id = r.id)::bigint AS member_count
FROM sso_group_rules r
JOIN teams t ON t.id = r.team_id
WHERE r.id = $1
`

type GetSSORuleViewRow struct {
	SsoGroupRule SsoGroupRule
	TeamSlug     string
	TeamName     string
	TeamStatus   string
	MemberCount  int64
}

func (q *Queries) GetSSORuleView(ctx context.Context, id uuid.UUID) (GetSSORuleViewRow, error) {
	row := q.db.QueryRow(ctx, getSSORuleView, id)
	var i GetSSORuleViewRow
	err := row.Scan(
		&i.SsoGroupRule.ID,
		&i.SsoGroupRule.GroupName,
		&i.SsoGroupRule.TeamID,
		&i.SsoGroupRule.Role,
		&i.SsoGroupRule.CreatedBy,
		&i.SsoGroupRule.Revision,
		&i.SsoGroupRule.CreatedAt,
		&i.SsoGroupRule.UpdatedAt,
		&i.TeamSlug,
		&i.TeamName,
		&i.TeamStatus,
		&i.MemberCount,
	)
	return i, err
}

const insertSSORule = `-- name: InsertSSORule :one

INSERT INTO sso_group_rules (group_name, team_id, role, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, group_name, team_id, role, created_by, revision, created_at, updated_at
`

type InsertSSORuleParams struct {
	GroupName string
	TeamID    uuid.UUID
	Role      string
	CreatedBy uuid.NullUUID
}

// SSO group mapping (migrations/00031_sso_group_mapping.sql).
func (q *Queries) InsertSSORule(ctx context.Context, arg InsertSSORuleParams) (SsoGroupRule, error) {
	row := q.db.QueryRow(ctx, insertSSORule,
		arg.GroupName,
		arg.TeamID,
		arg.Role,
		arg.CreatedBy,
	)
	var i SsoGroupRule
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.TeamID,
		&i.Role,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastGroupsClaimAt = `-- name: LastGroupsClaimAt :one
SELECT seen_at FROM sso_user_groups WHERE claim_present ORDER BY seen_at DESC LIMIT 1
`

func (q *Queries) LastGroupsClaimAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, lastGroupsClaimAt)
	var seen_at time.Time
	err := row.Scan(&seen_at)
	return seen_at, err
}

const listMembershipsForSSO = `-- name: ListMembershipsForSSO :many
SELECT m.team_id, m.role, t.status AS team_status,
       (s.user_id IS NOT NULL)::boolean AS sso, s.rule_id
FROM team_members m
JOIN teams t ON t.id = m.team_id
LEFT JOIN sso_memberships s ON s.team_id = m.team_id AND s.user_id = m.user_id
WHERE m.user_id = $1
`

type ListMembershipsForSSORow struct {
	TeamID     uuid.UUID
	Role       string
	TeamStatus string
	Sso        bool
	RuleID     uuid.NullUUID
}

// Every membership of a person, with its team's status and whether the
// mapping created it.
func (q *Queries) ListMembershipsForSSO(ctx context.Context, userID uuid.UUID) ([]ListMembershipsForSSORow, error) {
	rows, err := q.db.Query(ctx, listMembershipsForSSO, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsForSSORow{}
	for rows.Next() {
		var i ListMembershipsForSSORow
		if err := rows.Scan(
			&i.TeamID,
			&i.Role,
			&i.TeamStatus,
			&i.Sso,
			&i.RuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSOCandidates = `-- name: ListSSOCandidates :many
SELECT u.id, u.oidc_issuer, u.oidc_subject, u.email, u.display_name, u.platform_role, u.status, u.claims, u.created_at, u.updated_at, u.last_login_at, u.revision, coalesce(g.groups, '{}')::text[] AS groups, g.seen_at AS groups_seen_at
FROM users u
LEFT JOIN sso_user_groups g ON g.user_id = u.id
WHERE g.groups && $1::text[] OR u.id = ANY($2::uuid[])
ORDER BY u.email, u.id
`

type ListSSOCandidatesParams struct {
	Groups  []string
	UserIds []uuid.UUID
}

type ListSSOCandidatesRow struct {
	User         User
	Groups       []string
	GroupsSeenAt *time.Time
}

// People whose last-seen groups include any of these (lower-cased), or who
// are listed by ID, with their last-seen groups (empty when never seen).
func (q *Queries) ListSSOCandidates(ctx context.Context, arg ListSSOCandidatesParams) ([]ListSSOCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listSSOCandidates, arg.Groups, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSSOCandidatesRow{}
	for rows.Next() {
		var i ListSSOCandidatesRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.OIDCIssuer,
			&i.User.OIDCSubject,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.PlatformRole,
			&i.User.Status,
			&i.User.Claims,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.LastLoginAt,
			&i.User.Revision,
			&i.Groups,
			&i.GroupsSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSORuleUserIDs = `-- name: ListSSORuleUserIDs :many
SELECT user_id FROM sso_memberships WHERE rule_id = $1
`

// People the mapping gave a membership through this rule.
func (q *Queries) ListSSORuleUserIDs(ctx context.Context, ruleID uuid.NullUUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSSORuleUserIDs, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSORuleViews = `-- name: ListSSORuleViews :many
SELECT r.id, r.group_name, r.team_id, r.role, r.created_by, r.revision, r.created_at, r.updated_at, t.slug AS team_slug, t.name AS team_name, t.status AS team_status,
       (SELECT count(*) FROM sso_memberships s WHERE s.rule_id = r.id)::bigint AS member_count
FROM sso_group_rules r
JOIN teams t ON t.id = r.team_id
WHERE ($1::uuid IS NULL OR r.team_id = $1::uuid)
ORDER BY lower(r.group_name), t.slug, r.id
`

type ListSSORuleViewsRow struct {
	SsoGroupRule SsoGroupRule
	TeamSlug     string
	TeamName     string
	TeamStatus   string
	MemberCount  int64
}

// The rules with their team and the number of memberships each grants.
func (q *Queries) ListSSORuleViews(ctx context.Context, teamID uuid.NullUUID) ([]ListSSORuleViewsRow, error) {
	rows, err := q.db.Query(ctx, listSSORuleViews, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSSORuleViewsRow{}
	for rows.Next() {
		var i ListSSORuleViewsRow
		if err := rows.Scan(
			&i.SsoGroupRule.ID,
			&i.SsoGroupRule.GroupName,
			&i.SsoGroupRule.TeamID,
			&i.SsoGroupRule.Role,
			&i.SsoGroupRule.CreatedBy,
			&i.SsoGroupRule.Revision,
			&i.SsoGroupRule.CreatedAt,
			&i.SsoGroupRule.UpdatedAt,
			&i.TeamSlug,
			&i.TeamName,
			&i.TeamStatus,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSORulesForGroups = `-- name: ListSSORulesForGroups :many
SELECT r.id, r.group_name, r.team_id, r.role, r.created_by, r.revision, r.created_at, r.updated_at, t.status AS team_status
FROM sso_group_rules r
JOIN teams t ON t.id = r.team_id
WHERE lower(r.group_name) = ANY($1::text[])
ORDER BY r.created_at, r.id
`

type ListSSORulesForGroupsRow struct {
	SsoGroupRule SsoGroupRule
	TeamStatus   string
}

// Rules matching any of the (lower-cased) groups, with their team's status.
func (q *Queries) ListSSORulesForGroups(ctx context.Context, groups []string) ([]ListSSORulesForGroupsRow, error) {
	rows, err := q.db.Query(ctx, listSSORulesForGroups, groups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSSORulesForGroupsRow{}
	for rows.Next() {
		var i ListSSORulesForGroupsRow
		if err := rows.Scan(
			&i.SsoGroupRule.ID,
			&i.SsoGroupRule.GroupName,
			&i.SsoGroupRule.TeamID,
			&i.SsoGroupRule.Role,
			&i.SsoGroupRule.CreatedBy,
			&i.SsoGroupRule.Revision,
			&i.SsoGroupRule.CreatedAt,
			&i.SsoGroupRule.UpdatedAt,
			&i.TeamStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSORulesForTeam = `-- name: ListSSORulesForTeam :many
SELECT id, group_name, team_id, role, created_by, revision, created_at, updated_at FROM sso_group_rules WHERE team_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListSSORulesForTeam(ctx context.Context, teamID uuid.UUID) ([]SsoGroupRule, error) {
	rows, err := q.db.Query(ctx, listSSORulesForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SsoGroupRule{}
	for rows.Next() {
		var i SsoGroupRule
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.TeamID,
			&i.Role,
			&i.CreatedBy,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeenGroups = `-- name: ListSeenGroups :many
SELECT grp::text AS name, count(*)::bigint AS people
FROM sso_user_groups, unnest(groups) AS grp
GROUP BY grp
ORDER BY people DESC, grp
LIMIT $1
`

type ListSeenGroupsRow struct {
	Name   string
	People int64
}

// The groups seen at sign-in, most people first.
func (q *Queries) ListSeenGroups(ctx context.Context, maxGroups int32) ([]ListSeenGroupsRow, error) {
	rows, err := q.db.Query(ctx, listSeenGroups, maxGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeenGroupsRow{}
	for rows.Next() {
		var i ListSeenGroupsRow
		if err := rows.Scan(&i.Name, &i.People); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sSOGroupStats = `-- name: SSOGroupStats :one
SELECT (SELECT count(*) FROM sso_group_rules)::bigint AS rule_count,
       count(*)::bigint AS people_seen,
       count(*) FILTER (WHERE claim_present)::bigint AS people_with_claim,
       count(*) FILTER (WHERE seen_at > now() - interval '30 days')::bigint AS recent_sign_ins,
       count(*) FILTER (WHERE claim_present AND seen_at > now() - interval '30 days')::bigint AS recent_with_claim
FROM sso_user_groups
`

type SSOGroupStatsRow struct {
	RuleCount       int64
	PeopleSeen      int64
	PeopleWithClaim int64
	RecentSignIns   int64
	RecentWithClaim int64
}

func (q *Queries) SSOGroupStats(ctx context.Context) (SSOGroupStatsRow, error) {
	row := q.db.QueryRow(ctx, sSOGroupStats)
	var i SSOGroupStatsRow
	err := row.Scan(
		&i.RuleCount,
		&i.PeopleSeen,
		&i.PeopleWithClaim,
		&i.RecentSignIns,
		&i.RecentWithClaim,
	)
	return i, err
}

const updateSSORule = `-- name: UpdateSSORule :one
UPDATE sso_group_rules
SET group_name = $1, role = $2, revision = revision + 1, updated_at = now()
WHERE id = $3
RETURNING id, group_name, team_id, role, created_by, revision, created_at, updated_at
`

type UpdateSSORuleParams struct {
	GroupName string
	Role      string
	ID        uuid.UUID
}

func (q *Queries) UpdateSSORule(ctx context.Context, arg UpdateSSORuleParams) (SsoGroupRule, error) {
	row := q.db.QueryRow(ctx, updateSSORule, arg.GroupName, arg.Role, arg.ID)
	var i SsoGroupRule
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.TeamID,
		&i.Role,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSSOMembership = `-- name: UpsertSSOMembership :exec
INSERT INTO sso_memberships (team_id, user_id, rule_id)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, user_id) DO UPDATE SET rule_id = EXCLUDED.rule_id, updated_at = now()
`

type UpsertSSOMembershipParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
	RuleID uuid.NullUUID
}

func (q *Queries) UpsertSSOMembership(ctx context.Context, arg UpsertSSOMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertSSOMembership, arg.TeamID, arg.UserID, arg.RuleID)
	return err
}

const upsertUserGroups = `-- name: UpsertUserGroups :exec
INSERT INTO sso_user_groups (user_id, groups, claim_present, seen_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE
SET groups = EXCLUDED.groups, claim_present = EXCLUDED.claim_present, seen_at = EXCLUDED.seen_at
`

type UpsertUserGroupsParams struct {
	UserID       uuid.UUID
	Groups       []string
	ClaimPresent bool
}

func (q *Queries) UpsertUserGroups(ctx context.Context, arg UpsertUserGroupsParams) error {
	_, err := q.db.Exec(ctx, upsertUserGroups, arg.UserID, arg.Groups, arg.ClaimPresent)
	return err
}
