// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: systemone.sql

package dbgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getSystemOneSettings = `-- name: GetSystemOneSettings :one
SELECT singleton, model_id, settings, revision, updated_by, updated_at FROM systemone_settings WHERE singleton
`

func (q *Queries) GetSystemOneSettings(ctx context.Context) (SystemoneSetting, error) {
	row := q.db.QueryRow(ctx, getSystemOneSettings)
	var i SystemoneSetting
	err := row.Scan(
		&i.Singleton,
		&i.ModelID,
		&i.Settings,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSystemOneSettings = `-- name: InsertSystemOneSettings :one
INSERT INTO systemone_settings (model_id, settings, updated_by)
VALUES ($1, $2, $3)
ON CONFLICT (singleton) DO NOTHING
RETURNING singleton, model_id, settings, revision, updated_by, updated_at
`

type InsertSystemOneSettingsParams struct {
	ModelID   uuid.NullUUID
	Settings  json.RawMessage
	UpdatedBy uuid.NullUUID
}

func (q *Queries) InsertSystemOneSettings(ctx context.Context, arg InsertSystemOneSettingsParams) (SystemoneSetting, error) {
	row := q.db.QueryRow(ctx, insertSystemOneSettings, arg.ModelID, arg.Settings, arg.UpdatedBy)
	var i SystemoneSetting
	err := row.Scan(
		&i.Singleton,
		&i.ModelID,
		&i.Settings,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSystemOneSettings = `-- name: LockSystemOneSettings :one
SELECT singleton, model_id, settings, revision, updated_by, updated_at FROM systemone_settings WHERE singleton FOR UPDATE
`

func (q *Queries) LockSystemOneSettings(ctx context.Context) (SystemoneSetting, error) {
	row := q.db.QueryRow(ctx, lockSystemOneSettings)
	var i SystemoneSetting
	err := row.Scan(
		&i.Singleton,
		&i.ModelID,
		&i.Settings,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSystemOneSettings = `-- name: UpdateSystemOneSettings :one
UPDATE systemone_settings
SET model_id = $1, settings = $2, updated_by = $3,
    revision = revision + 1, updated_at = now()
WHERE singleton
RETURNING singleton, model_id, settings, revision, updated_by, updated_at
`

type UpdateSystemOneSettingsParams struct {
	ModelID   uuid.NullUUID
	Settings  json.RawMessage
	UpdatedBy uuid.NullUUID
}

func (q *Queries) UpdateSystemOneSettings(ctx context.Context, arg UpdateSystemOneSettingsParams) (SystemoneSetting, error) {
	row := q.db.QueryRow(ctx, updateSystemOneSettings, arg.ModelID, arg.Settings, arg.UpdatedBy)
	var i SystemoneSetting
	err := row.Scan(
		&i.Singleton,
		&i.ModelID,
		&i.Settings,
		&i.Revision,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
