// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptInvite = `-- name: AcceptInvite :exec
UPDATE team_invites SET accepted_at = now(), accepted_user_id = $1 WHERE id = $2
`

type AcceptInviteParams struct {
	UserID uuid.NullUUID
	ID     uuid.UUID
}

func (q *Queries) AcceptInvite(ctx context.Context, arg AcceptInviteParams) error {
	_, err := q.db.Exec(ctx, acceptInvite, arg.UserID, arg.ID)
	return err
}

const claimInvitesForEmail = `-- name: ClaimInvitesForEmail :many
SELECT id, team_id, email, role, invited_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at FROM team_invites
WHERE email = $1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
ORDER BY created_at
FOR UPDATE
`

func (q *Queries) ClaimInvitesForEmail(ctx context.Context, email string) ([]TeamInvite, error) {
	rows, err := q.db.Query(ctx, claimInvitesForEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamInvite{}
	for rows.Next() {
		var i TeamInvite
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedUserID,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM team_members WHERE team_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.TeamID, arg.UserID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT team_id, user_id, role, added_by, revision, created_at, updated_at FROM team_members WHERE team_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	TeamID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.AddedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenInvite = `-- name: GetOpenInvite :one
SELECT id, team_id, email, role, invited_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at FROM team_invites
WHERE id = $1 AND team_id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
FOR UPDATE
`

type GetOpenInviteParams struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

func (q *Queries) GetOpenInvite(ctx context.Context, arg GetOpenInviteParams) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, getOpenInvite, arg.ID, arg.TeamID)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.RevokedAt,
	)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, slug, name, description, max_classification, status, created_by, revision, created_at, updated_at, archived_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.MaxClassification,
		&i.Status,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, slug, name, description, max_classification, status, created_by, revision, created_at, updated_at, archived_at FROM teams WHERE slug = $1
`

func (q *Queries) GetTeamBySlug(ctx context.Context, slug string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamBySlug, slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.MaxClassification,
		&i.Status,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :one
INSERT INTO team_members (team_id, user_id, role, added_by)
VALUES ($1, $2, $3, $4)
RETURNING team_id, user_id, role, added_by, revision, created_at, updated_at
`

type InsertMemberParams struct {
	TeamID  uuid.UUID
	UserID  uuid.UUID
	Role    string
	AddedBy uuid.NullUUID
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, insertMember,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.AddedBy,
	)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.AddedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMemberIfAbsent = `-- name: InsertMemberIfAbsent :execrows
INSERT INTO team_members (team_id, user_id, role, added_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (team_id, user_id) DO NOTHING
`

type InsertMemberIfAbsentParams struct {
	TeamID  uuid.UUID
	UserID  uuid.UUID
	Role    string
	AddedBy uuid.NullUUID
}

func (q *Queries) InsertMemberIfAbsent(ctx context.Context, arg InsertMemberIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertMemberIfAbsent,
		arg.TeamID,
		arg.UserID,
		arg.Role,
		arg.AddedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTeam = `-- name: InsertTeam :one
INSERT INTO teams (slug, name, description, max_classification, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, name, description, max_classification, status, created_by, revision, created_at, updated_at, archived_at
`

type InsertTeamParams struct {
	Slug              string
	Name              string
	Description       string
	MaxClassification string
	CreatedBy         uuid.NullUUID
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, insertTeam,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.MaxClassification,
		arg.CreatedBy,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.MaxClassification,
		&i.Status,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT m.team_id, m.user_id, m.role, m.added_by, m.revision, m.created_at, m.updated_at, u.id, u.oidc_issuer, u.oidc_subject, u.email, u.display_name, u.platform_role, u.status, u.claims, u.created_at, u.updated_at, u.last_login_at, u.revision,
       (s.user_id IS NOT NULL)::boolean AS sso, s.rule_id AS sso_rule_id, r.group_name AS sso_group
FROM team_members m
JOIN users u ON u.id = m.user_id
LEFT JOIN sso_memberships s ON s.team_id = m.team_id AND s.user_id = m.user_id
LEFT JOIN sso_group_rules r ON r.id = s.rule_id
WHERE m.team_id = $1
ORDER BY CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 WHEN 'editor' THEN 2 ELSE 3 END,
         u.email::text
`

type ListMembersRow struct {
	TeamMember TeamMember
	User       User
	Sso        bool
	SsoRuleID  uuid.NullUUID
	SsoGroup   *string
}

// sso is true for memberships the SSO group mapping created; sso_group is
// the group of the rule that grants it (NULL when that rule was deleted).
func (q *Queries) ListMembers(ctx context.Context, teamID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.TeamMember.TeamID,
			&i.TeamMember.UserID,
			&i.TeamMember.Role,
			&i.TeamMember.AddedBy,
			&i.TeamMember.Revision,
			&i.TeamMember.CreatedAt,
			&i.TeamMember.UpdatedAt,
			&i.User.ID,
			&i.User.OIDCIssuer,
			&i.User.OIDCSubject,
			&i.User.Email,
			&i.User.DisplayName,
			&i.User.PlatformRole,
			&i.User.Status,
			&i.User.Claims,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.LastLoginAt,
			&i.User.Revision,
			&i.Sso,
			&i.SsoRuleID,
			&i.SsoGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenInvites = `-- name: ListOpenInvites :many
SELECT id, team_id, email, role, invited_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at FROM team_invites
WHERE team_id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListOpenInvites(ctx context.Context, teamID uuid.UUID) ([]TeamInvite, error) {
	rows, err := q.db.Query(ctx, listOpenInvites, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamInvite{}
	for rows.Next() {
		var i TeamInvite
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedUserID,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsAdmin = `-- name: ListTeamsAdmin :many
SELECT t.id, t.slug, t.name, t.description, t.max_classification, t.status, t.created_by, t.revision, t.created_at, t.updated_at, t.archived_at,
       (SELECT count(*) FROM team_members m WHERE m.team_id = t.id)::bigint AS member_count,
       (SELECT count(*) FROM team_members m WHERE m.team_id = t.id AND m.role = 'owner')::bigint AS owner_count,
       (SELECT count(*) FROM team_invites i WHERE i.team_id = t.id AND i.role = 'owner' AND i.accepted_at IS NULL AND i.revoked_at IS NULL
          AND i.expires_at > now())::bigint AS owner_invites,
       (SELECT count(*) FROM agents ag WHERE ag.team_id = t.id AND ag.deleted_at IS NULL)::bigint AS agent_count,
       (SELECT count(*) FROM data_sources ds WHERE ds.team_id = t.id)::bigint AS source_count,
       (SELECT count(*) FROM knowledge_bases kb WHERE kb.team_id = t.id)::bigint AS kb_count,
       (SELECT count(*) FROM documents d WHERE d.team_id = t.id)::bigint AS document_count,
       (SELECT coalesce(sum(d.size_bytes), 0) FROM documents d WHERE d.team_id = t.id)::bigint AS storage_bytes
FROM teams t
WHERE ($1::text IS NULL
       OR t.slug ILIKE '%' || $1::text || '%' ESCAPE '\'
       OR t.name ILIKE '%' || $1::text || '%' ESCAPE '\')
  AND ($2::text IS NULL OR t.status = $2::text)
  AND ($3::text IS NULL OR t.slug > $3::text)
ORDER BY t.slug
LIMIT $4
`

type ListTeamsAdminParams struct {
	Search    *string
	Status    *string
	AfterSlug *string
	PageSize  int32
}

type ListTeamsAdminRow struct {
	Team          Team
	MemberCount   int64
	OwnerCount    int64
	OwnerInvites  int64
	AgentCount    int64
	SourceCount   int64
	KbCount       int64
	DocumentCount int64
	StorageBytes  int64
}

func (q *Queries) ListTeamsAdmin(ctx context.Context, arg ListTeamsAdminParams) ([]ListTeamsAdminRow, error) {
	rows, err := q.db.Query(ctx, listTeamsAdmin,
		arg.Search,
		arg.Status,
		arg.AfterSlug,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsAdminRow{}
	for rows.Next() {
		var i ListTeamsAdminRow
		if err := rows.Scan(
			&i.Team.ID,
			&i.Team.Slug,
			&i.Team.Name,
			&i.Team.Description,
			&i.Team.MaxClassification,
			&i.Team.Status,
			&i.Team.CreatedBy,
			&i.Team.Revision,
			&i.Team.CreatedAt,
			&i.Team.UpdatedAt,
			&i.Team.ArchivedAt,
			&i.MemberCount,
			&i.OwnerCount,
			&i.OwnerInvites,
			&i.AgentCount,
			&i.SourceCount,
			&i.KbCount,
			&i.DocumentCount,
			&i.StorageBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT t.id, t.slug, t.name, t.description, t.max_classification, t.status, t.created_by, t.revision, t.created_at, t.updated_at, t.archived_at, m.role AS member_role
FROM team_members m
JOIN teams t ON t.id = m.team_id
WHERE m.user_id = $1
ORDER BY t.name, t.id
`

type ListTeamsForUserRow struct {
	ID                uuid.UUID
	Slug              string
	Name              string
	Description       string
	MaxClassification string
	Status            string
	CreatedBy         uuid.NullUUID
	Revision          int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ArchivedAt        *time.Time
	MemberRole        string
}

func (q *Queries) ListTeamsForUser(ctx context.Context, userID uuid.UUID) ([]ListTeamsForUserRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsForUserRow{}
	for rows.Next() {
		var i ListTeamsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.MaxClassification,
			&i.Status,
			&i.CreatedBy,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTeam = `-- name: LockTeam :one
SELECT id, slug, name, description, max_classification, status, created_by, revision, created_at, updated_at, archived_at FROM teams WHERE id = $1 FOR UPDATE
`

// Serialises membership changes for one team (owner counting, invites).
func (q *Queries) LockTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, lockTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.MaxClassification,
		&i.Status,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE team_invites SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeInvite, id)
	return err
}

const teamCounts = `-- name: TeamCounts :one
SELECT (SELECT count(*) FROM team_members m WHERE m.team_id = $1)::bigint AS member_count,
       (SELECT count(*) FROM team_members m WHERE m.team_id = $1 AND m.role = 'owner')::bigint AS owner_count,
       (SELECT count(*) FROM team_invites i WHERE i.team_id = $1 AND i.role = 'owner' AND i.accepted_at IS NULL AND i.revoked_at IS NULL
          AND i.expires_at > now())::bigint AS owner_invites,
       (SELECT count(*) FROM agents ag WHERE ag.team_id = $1 AND ag.deleted_at IS NULL)::bigint AS agent_count,
       (SELECT count(*) FROM data_sources ds WHERE ds.team_id = $1)::bigint AS source_count,
       (SELECT count(*) FROM knowledge_bases kb WHERE kb.team_id = $1)::bigint AS kb_count,
       (SELECT count(*) FROM documents d WHERE d.team_id = $1)::bigint AS document_count,
       (SELECT coalesce(sum(d.size_bytes), 0) FROM documents d WHERE d.team_id = $1)::bigint AS storage_bytes
`

type TeamCountsRow struct {
	MemberCount   int64
	OwnerCount    int64
	OwnerInvites  int64
	AgentCount    int64
	SourceCount   int64
	KbCount       int64
	DocumentCount int64
	StorageBytes  int64
}

func (q *Queries) TeamCounts(ctx context.Context, teamID uuid.UUID) (TeamCountsRow, error) {
	row := q.db.QueryRow(ctx, teamCounts, teamID)
	var i TeamCountsRow
	err := row.Scan(
		&i.MemberCount,
		&i.OwnerCount,
		&i.OwnerInvites,
		&i.AgentCount,
		&i.SourceCount,
		&i.KbCount,
		&i.DocumentCount,
		&i.StorageBytes,
	)
	return i, err
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE team_members
SET role = $1, revision = revision + 1, updated_at = now()
WHERE team_id = $2 AND user_id = $3
RETURNING team_id, user_id, role, added_by, revision, created_at, updated_at
`

type UpdateMemberRoleParams struct {
	Role   string
	TeamID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.Role, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.AddedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name               = $1,
    description        = $2,
    max_classification = $3,
    status             = $4,
    archived_at        = CASE WHEN $4::text = 'archived' THEN coalesce(archived_at, now()) ELSE NULL END,
    revision           = revision + 1,
    updated_at         = now()
WHERE id = $5
RETURNING id, slug, name, description, max_classification, status, created_by, revision, created_at, updated_at, archived_at
`

type UpdateTeamParams struct {
	Name              string
	Description       string
	MaxClassification string
	Status            string
	ID                uuid.UUID
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.Name,
		arg.Description,
		arg.MaxClassification,
		arg.Status,
		arg.ID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.MaxClassification,
		&i.Status,
		&i.CreatedBy,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const upsertInvite = `-- name: UpsertInvite :one
INSERT INTO team_invites (team_id, email, role, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (team_id, email) WHERE accepted_at IS NULL AND revoked_at IS NULL
DO UPDATE SET role = EXCLUDED.role, invited_by = EXCLUDED.invited_by,
              expires_at = EXCLUDED.expires_at, created_at = now()
RETURNING id, team_id, email, role, invited_by, created_at, expires_at, accepted_at, accepted_user_id, revoked_at
`

type UpsertInviteParams struct {
	TeamID    uuid.UUID
	Email     string
	Role      string
	InvitedBy uuid.NullUUID
	ExpiresAt time.Time
}

func (q *Queries) UpsertInvite(ctx context.Context, arg UpsertInviteParams) (TeamInvite, error) {
	row := q.db.QueryRow(ctx, upsertInvite,
		arg.TeamID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i TeamInvite
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedUserID,
		&i.RevokedAt,
	)
	return i, err
}
