// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const activePlatformAdminIDs = `-- name: ActivePlatformAdminIDs :many
SELECT id FROM users WHERE platform_role = 'platform_admin' AND status = 'active' ORDER BY id
`

func (q *Queries) ActivePlatformAdminIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, activePlatformAdminIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserForUpdate = `-- name: GetUserForUpdate :one
SELECT id, oidc_issuer, oidc_subject, email, display_name, platform_role, status, claims, created_at, updated_at, last_login_at, revision FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetUserForUpdate(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OIDCIssuer,
		&i.OIDCSubject,
		&i.Email,
		&i.DisplayName,
		&i.PlatformRole,
		&i.Status,
		&i.Claims,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Revision,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, oidc_issuer, oidc_subject, email, display_name, platform_role, status, claims, created_at, updated_at, last_login_at, revision FROM users
WHERE ($1::text IS NULL
       OR email::text ILIKE '%' || $1::text || '%' ESCAPE '\'
       OR display_name ILIKE '%' || $1::text || '%' ESCAPE '\')
  AND ($2::text IS NULL OR platform_role = $2::text)
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::text IS NULL
       OR (email::text, id) > ($4::text, $5::uuid))
ORDER BY email::text, id
LIMIT $6
`

type ListUsersParams struct {
	Search       *string
	PlatformRole *string
	Status       *string
	AfterEmail   *string
	AfterID      uuid.NullUUID
	PageSize     int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.PlatformRole,
		arg.Status,
		arg.AfterEmail,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OIDCIssuer,
			&i.OIDCSubject,
			&i.Email,
			&i.DisplayName,
			&i.PlatformRole,
			&i.Status,
			&i.Claims,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByEmail = `-- name: ListUsersByEmail :many
SELECT id, oidc_issuer, oidc_subject, email, display_name, platform_role, status, claims, created_at, updated_at, last_login_at, revision FROM users WHERE email = $1 ORDER BY created_at
`

func (q *Queries) ListUsersByEmail(ctx context.Context, email string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OIDCIssuer,
			&i.OIDCSubject,
			&i.Email,
			&i.DisplayName,
			&i.PlatformRole,
			&i.Status,
			&i.Claims,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.Revision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActivePlatformAdmins = `-- name: LockActivePlatformAdmins :many
SELECT id FROM users
WHERE platform_role = 'platform_admin' AND status = 'active'
ORDER BY id
FOR UPDATE
`

// Locks every active platform admin so concurrent demotions serialise.
func (q *Queries) LockActivePlatformAdmins(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockActivePlatformAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAccess = `-- name: UpdateUserAccess :one
UPDATE users
SET platform_role = $1,
    status        = $2,
    revision      = revision + 1,
    updated_at    = now()
WHERE id = $3
RETURNING id, oidc_issuer, oidc_subject, email, display_name, platform_role, status, claims, created_at, updated_at, last_login_at, revision
`

type UpdateUserAccessParams struct {
	PlatformRole string
	Status       string
	ID           uuid.UUID
}

func (q *Queries) UpdateUserAccess(ctx context.Context, arg UpdateUserAccessParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAccess, arg.PlatformRole, arg.Status, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OIDCIssuer,
		&i.OIDCSubject,
		&i.Email,
		&i.DisplayName,
		&i.PlatformRole,
		&i.Status,
		&i.Claims,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.Revision,
	)
	return i, err
}

const userTeamCounts = `-- name: UserTeamCounts :many
SELECT user_id, count(*)::bigint AS teams FROM team_members WHERE user_id = ANY($1::uuid[]) GROUP BY user_id
`

type UserTeamCountsRow struct {
	UserID uuid.UUID
	Teams  int64
}

// How many teams each user belongs to (the admin Users list).
func (q *Queries) UserTeamCounts(ctx context.Context, ids []uuid.UUID) ([]UserTeamCountsRow, error) {
	rows, err := q.db.Query(ctx, userTeamCounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserTeamCountsRow{}
	for rows.Next() {
		var i UserTeamCountsRow
		if err := rows.Scan(&i.UserID, &i.Teams); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
