// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: web.sql

package dbgen

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const activeCrawl = `-- name: ActiveCrawl :one
SELECT id, source_id, team_id, status, trigger, config, pages_discovered, pages_fetched, pages_changed, pages_unchanged, pages_skipped, pages_failed, documents_deleted, truncated, error, created_by, created_at, started_at, finished_at, truncated_reason, waiting_reason, waiting_until FROM web_crawls WHERE source_id = $1 AND status IN ('queued', 'running')
`

func (q *Queries) ActiveCrawl(ctx context.Context, sourceID uuid.UUID) (WebCrawl, error) {
	row := q.db.QueryRow(ctx, activeCrawl, sourceID)
	var i WebCrawl
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TeamID,
		&i.Status,
		&i.Trigger,
		&i.Config,
		&i.PagesDiscovered,
		&i.PagesFetched,
		&i.PagesChanged,
		&i.PagesUnchanged,
		&i.PagesSkipped,
		&i.PagesFailed,
		&i.DocumentsDeleted,
		&i.Truncated,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TruncatedReason,
		&i.WaitingReason,
		&i.WaitingUntil,
	)
	return i, err
}

const activeCrawlsForSources = `-- name: ActiveCrawlsForSources :many
SELECT id, source_id, team_id, status, trigger, config, pages_discovered, pages_fetched, pages_changed, pages_unchanged, pages_skipped, pages_failed, documents_deleted, truncated, error, created_by, created_at, started_at, finished_at, truncated_reason, waiting_reason, waiting_until FROM web_crawls WHERE source_id = ANY($1::uuid[]) AND status IN ('queued', 'running')
`

func (q *Queries) ActiveCrawlsForSources(ctx context.Context, sourceIds []uuid.UUID) ([]WebCrawl, error) {
	rows, err := q.db.Query(ctx, activeCrawlsForSources, sourceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebCrawl{}
	for rows.Next() {
		var i WebCrawl
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TeamID,
			&i.Status,
			&i.Trigger,
			&i.Config,
			&i.PagesDiscovered,
			&i.PagesFetched,
			&i.PagesChanged,
			&i.PagesUnchanged,
			&i.PagesSkipped,
			&i.PagesFailed,
			&i.DocumentsDeleted,
			&i.Truncated,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TruncatedReason,
			&i.WaitingReason,
			&i.WaitingUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addCrawlCounts = `-- name: AddCrawlCounts :exec
UPDATE web_crawls
SET pages_discovered = pages_discovered + $1, pages_fetched = pages_fetched + $2,
    pages_changed = pages_changed + $3, pages_unchanged = pages_unchanged + $4,
    pages_skipped = pages_skipped + $5, pages_failed = pages_failed + $6,
    truncated = truncated OR $7
WHERE id = $8
`

type AddCrawlCountsParams struct {
	Discovered int32
	Fetched    int32
	Changed    int32
	Unchanged  int32
	Skipped    int32
	Failed     int32
	Truncated  bool
	ID         uuid.UUID
}

func (q *Queries) AddCrawlCounts(ctx context.Context, arg AddCrawlCountsParams) error {
	_, err := q.db.Exec(ctx, addCrawlCounts,
		arg.Discovered,
		arg.Fetched,
		arg.Changed,
		arg.Unchanged,
		arg.Skipped,
		arg.Failed,
		arg.Truncated,
		arg.ID,
	)
	return err
}

const admitCrawl = `-- name: AdmitCrawl :execrows
UPDATE web_crawls SET waiting_reason = ''
WHERE id = $1 AND status = 'queued' AND waiting_reason = 'concurrent_crawls'
`

func (q *Queries) AdmitCrawl(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, admitCrawl, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const approvedTeamPatterns = `-- name: ApprovedTeamPatterns :many
SELECT pattern FROM crawl_domain_requests WHERE team_id = $1 AND status = 'approved'
`

func (q *Queries) ApprovedTeamPatterns(ctx context.Context, teamID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, approvedTeamPatterns, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var pattern string
		if err := rows.Scan(&pattern); err != nil {
			return nil, err
		}
		items = append(items, pattern)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countFrontier = `-- name: CountFrontier :one
SELECT count(*) FROM web_frontier WHERE crawl_id = $1
`

func (q *Queries) CountFrontier(ctx context.Context, crawlID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFrontier, crawlID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingDomainRequests = `-- name: CountPendingDomainRequests :one
SELECT count(*) FROM crawl_domain_requests WHERE status = 'pending'
`

func (q *Queries) CountPendingDomainRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingDomainRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dailyLimitedCrawls = `-- name: DailyLimitedCrawls :many
SELECT id FROM web_crawls
WHERE status IN ('queued', 'running') AND waiting_reason = 'daily_page_limit'
  AND ($1::uuid IS NULL OR team_id = $1::uuid)
ORDER BY created_at, id
LIMIT 1000
`

// Runs waiting for the next day's crawled-page quota: one team's, or
// every team's (a platform default changed).
func (q *Queries) DailyLimitedCrawls(ctx context.Context, teamID uuid.NullUUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dailyLimitedCrawls, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllowlist = `-- name: DeleteAllowlist :one
DELETE FROM crawl_allowlist WHERE id = $1 RETURNING id, pattern, note, created_by, created_at
`

func (q *Queries) DeleteAllowlist(ctx context.Context, id uuid.UUID) (CrawlAllowlist, error) {
	row := q.db.QueryRow(ctx, deleteAllowlist, id)
	var i CrawlAllowlist
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUnseenDocuments = `-- name: DeleteUnseenDocuments :many
DELETE FROM documents
WHERE source_id = $1 AND (last_seen_crawl_id IS NULL OR last_seen_crawl_id <> $2)
RETURNING id, blob_key, created_at
`

type DeleteUnseenDocumentsParams struct {
	SourceID uuid.UUID
	CrawlID  uuid.NullUUID
}

type DeleteUnseenDocumentsRow struct {
	ID        uuid.UUID
	BlobKey   string
	CreatedAt time.Time
}

// Pages not seen by a completed, untruncated crawl no longer exist on the site.
func (q *Queries) DeleteUnseenDocuments(ctx context.Context, arg DeleteUnseenDocumentsParams) ([]DeleteUnseenDocumentsRow, error) {
	rows, err := q.db.Query(ctx, deleteUnseenDocuments, arg.SourceID, arg.CrawlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteUnseenDocumentsRow{}
	for rows.Next() {
		var i DeleteUnseenDocumentsRow
		if err := rows.Scan(&i.ID, &i.BlobKey, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dueWebSources = `-- name: DueWebSources :many

SELECT id, team_id, name, description, type, config, classification, embedding_profile_id, status, revision, created_by, created_at, updated_at, last_sync_at, next_sync_at, ocr_enabled FROM data_sources
WHERE type = 'web' AND status = 'active' AND next_sync_at IS NOT NULL AND next_sync_at <= now()
ORDER BY next_sync_at
LIMIT 100
FOR UPDATE SKIP LOCKED
`

// ---- scheduling -------------------------------------------------------------------
func (q *Queries) DueWebSources(ctx context.Context) ([]DataSource, error) {
	rows, err := q.db.Query(ctx, dueWebSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataSource{}
	for rows.Next() {
		var i DataSource
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Config,
			&i.Classification,
			&i.EmbeddingProfileID,
			&i.Status,
			&i.Revision,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSyncAt,
			&i.NextSyncAt,
			&i.OcrEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishCrawl = `-- name: FinishCrawl :execrows
UPDATE web_crawls
SET status = $1, error = $2, documents_deleted = $3, finished_at = now(),
    waiting_reason = '', waiting_until = NULL
WHERE id = $4 AND status IN ('queued', 'running')
`

type FinishCrawlParams struct {
	Status           string
	Error            string
	DocumentsDeleted int32
	ID               uuid.UUID
}

// Only an active run can finish; a run cancelled meanwhile stays cancelled.
func (q *Queries) FinishCrawl(ctx context.Context, arg FinishCrawlParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishCrawl,
		arg.Status,
		arg.Error,
		arg.DocumentsDeleted,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCrawl = `-- name: GetCrawl :one
SELECT id, source_id, team_id, status, trigger, config, pages_discovered, pages_fetched, pages_changed, pages_unchanged, pages_skipped, pages_failed, documents_deleted, truncated, error, created_by, created_at, started_at, finished_at, truncated_reason, waiting_reason, waiting_until FROM web_crawls WHERE id = $1
`

func (q *Queries) GetCrawl(ctx context.Context, id uuid.UUID) (WebCrawl, error) {
	row := q.db.QueryRow(ctx, getCrawl, id)
	var i WebCrawl
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TeamID,
		&i.Status,
		&i.Trigger,
		&i.Config,
		&i.PagesDiscovered,
		&i.PagesFetched,
		&i.PagesChanged,
		&i.PagesUnchanged,
		&i.PagesSkipped,
		&i.PagesFailed,
		&i.DocumentsDeleted,
		&i.Truncated,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TruncatedReason,
		&i.WaitingReason,
		&i.WaitingUntil,
	)
	return i, err
}

const getDomainRequestView = `-- name: GetDomainRequestView :one
SELECT r.id, r.team_id, r.pattern, r.reason, r.status, r.requested_by, r.reviewed_by, r.review_note, r.reviewed_at, r.created_at, t.slug AS team_slug, t.name AS team_name,
       coalesce(ru.display_name, '')::text AS requester_name, coalesce(ru.email::text, '')::text AS requester_email,
       coalesce(rv.display_name, '')::text AS reviewer_name, coalesce(rv.email::text, '')::text AS reviewer_email
FROM crawl_domain_requests r JOIN teams t ON t.id = r.team_id
LEFT JOIN users ru ON ru.id = r.requested_by
LEFT JOIN users rv ON rv.id = r.reviewed_by
WHERE r.id = $1
`

type GetDomainRequestViewRow struct {
	ID             uuid.UUID
	TeamID         uuid.UUID
	Pattern        string
	Reason         string
	Status         string
	RequestedBy    uuid.NullUUID
	ReviewedBy     uuid.NullUUID
	ReviewNote     string
	ReviewedAt     *time.Time
	CreatedAt      time.Time
	TeamSlug       string
	TeamName       string
	RequesterName  string
	RequesterEmail string
	ReviewerName   string
	ReviewerEmail  string
}

func (q *Queries) GetDomainRequestView(ctx context.Context, id uuid.UUID) (GetDomainRequestViewRow, error) {
	row := q.db.QueryRow(ctx, getDomainRequestView, id)
	var i GetDomainRequestViewRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Pattern,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.TeamSlug,
		&i.TeamName,
		&i.RequesterName,
		&i.RequesterEmail,
		&i.ReviewerName,
		&i.ReviewerEmail,
	)
	return i, err
}

const insertAllowlist = `-- name: InsertAllowlist :one
INSERT INTO crawl_allowlist (pattern, note, created_by) VALUES ($1, $2, $3) RETURNING id, pattern, note, created_by, created_at
`

type InsertAllowlistParams struct {
	Pattern   string
	Note      string
	CreatedBy uuid.NullUUID
}

func (q *Queries) InsertAllowlist(ctx context.Context, arg InsertAllowlistParams) (CrawlAllowlist, error) {
	row := q.db.QueryRow(ctx, insertAllowlist, arg.Pattern, arg.Note, arg.CreatedBy)
	var i CrawlAllowlist
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertBootstrapState = `-- name: InsertBootstrapState :execrows

INSERT INTO bootstrap_state (key, details) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertBootstrapStateParams struct {
	Key     string
	Details json.RawMessage
}

// ---- first-run seed ----------------------------------------------------------
// Returns 1 for the caller that records the step first, 0 afterwards.
func (q *Queries) InsertBootstrapState(ctx context.Context, arg InsertBootstrapStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertBootstrapState, arg.Key, arg.Details)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCrawl = `-- name: InsertCrawl :one

INSERT INTO web_crawls (source_id, team_id, trigger, config, created_by, waiting_reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, source_id, team_id, status, trigger, config, pages_discovered, pages_fetched, pages_changed, pages_unchanged, pages_skipped, pages_failed, documents_deleted, truncated, error, created_by, created_at, started_at, finished_at, truncated_reason, waiting_reason, waiting_until
`

type InsertCrawlParams struct {
	SourceID      uuid.UUID
	TeamID        uuid.NullUUID
	Trigger       string
	Config        json.RawMessage
	CreatedBy     uuid.NullUUID
	WaitingReason string
}

// ---- crawls -------------------------------------------------------------------
func (q *Queries) InsertCrawl(ctx context.Context, arg InsertCrawlParams) (WebCrawl, error) {
	row := q.db.QueryRow(ctx, insertCrawl,
		arg.SourceID,
		arg.TeamID,
		arg.Trigger,
		arg.Config,
		arg.CreatedBy,
		arg.WaitingReason,
	)
	var i WebCrawl
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TeamID,
		&i.Status,
		&i.Trigger,
		&i.Config,
		&i.PagesDiscovered,
		&i.PagesFetched,
		&i.PagesChanged,
		&i.PagesUnchanged,
		&i.PagesSkipped,
		&i.PagesFailed,
		&i.DocumentsDeleted,
		&i.Truncated,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TruncatedReason,
		&i.WaitingReason,
		&i.WaitingUntil,
	)
	return i, err
}

const insertDomainRequest = `-- name: InsertDomainRequest :one
INSERT INTO crawl_domain_requests (team_id, pattern, reason, requested_by)
VALUES ($1, $2, $3, $4)
RETURNING id, team_id, pattern, reason, status, requested_by, reviewed_by, review_note, reviewed_at, created_at
`

type InsertDomainRequestParams struct {
	TeamID      uuid.UUID
	Pattern     string
	Reason      string
	RequestedBy uuid.NullUUID
}

func (q *Queries) InsertDomainRequest(ctx context.Context, arg InsertDomainRequestParams) (CrawlDomainRequest, error) {
	row := q.db.QueryRow(ctx, insertDomainRequest,
		arg.TeamID,
		arg.Pattern,
		arg.Reason,
		arg.RequestedBy,
	)
	var i CrawlDomainRequest
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Pattern,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertFrontier = `-- name: InsertFrontier :execrows
INSERT INTO web_frontier (crawl_id, url, depth)
SELECT $1, u, $2 FROM unnest($3::text[]) AS u
ON CONFLICT DO NOTHING
`

type InsertFrontierParams struct {
	CrawlID uuid.UUID
	Depth   int32
	Urls    []string
}

func (q *Queries) InsertFrontier(ctx context.Context, arg InsertFrontierParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFrontier, arg.CrawlID, arg.Depth, arg.Urls)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAllowlist = `-- name: ListAllowlist :many

SELECT id, pattern, note, created_by, created_at FROM crawl_allowlist ORDER BY pattern
`

// ---- allowlist and domain requests -------------------------------------
func (q *Queries) ListAllowlist(ctx context.Context) ([]CrawlAllowlist, error) {
	rows, err := q.db.Query(ctx, listAllowlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CrawlAllowlist{}
	for rows.Next() {
		var i CrawlAllowlist
		if err := rows.Scan(
			&i.ID,
			&i.Pattern,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainRequests = `-- name: ListDomainRequests :many
SELECT r.id, r.team_id, r.pattern, r.reason, r.status, r.requested_by, r.reviewed_by, r.review_note, r.reviewed_at, r.created_at, t.slug AS team_slug, t.name AS team_name,
       coalesce(ru.display_name, '')::text AS requester_name, coalesce(ru.email::text, '')::text AS requester_email,
       coalesce(rv.display_name, '')::text AS reviewer_name, coalesce(rv.email::text, '')::text AS reviewer_email
FROM crawl_domain_requests r JOIN teams t ON t.id = r.team_id
LEFT JOIN users ru ON ru.id = r.requested_by
LEFT JOIN users rv ON rv.id = r.reviewed_by
WHERE ($1::text IS NULL OR r.status = $1::text)
ORDER BY (r.status = 'pending') DESC, r.created_at DESC
LIMIT 500
`

type ListDomainRequestsRow struct {
	ID             uuid.UUID
	TeamID         uuid.UUID
	Pattern        string
	Reason         string
	Status         string
	RequestedBy    uuid.NullUUID
	ReviewedBy     uuid.NullUUID
	ReviewNote     string
	ReviewedAt     *time.Time
	CreatedAt      time.Time
	TeamSlug       string
	TeamName       string
	RequesterName  string
	RequesterEmail string
	ReviewerName   string
	ReviewerEmail  string
}

func (q *Queries) ListDomainRequests(ctx context.Context, status *string) ([]ListDomainRequestsRow, error) {
	rows, err := q.db.Query(ctx, listDomainRequests, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainRequestsRow{}
	for rows.Next() {
		var i ListDomainRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Pattern,
			&i.Reason,
			&i.Status,
			&i.RequestedBy,
			&i.ReviewedBy,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.TeamSlug,
			&i.TeamName,
			&i.RequesterName,
			&i.RequesterEmail,
			&i.ReviewerName,
			&i.ReviewerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceCrawls = `-- name: ListSourceCrawls :many
SELECT id, source_id, team_id, status, trigger, config, pages_discovered, pages_fetched, pages_changed, pages_unchanged, pages_skipped, pages_failed, documents_deleted, truncated, error, created_by, created_at, started_at, finished_at, truncated_reason, waiting_reason, waiting_until FROM web_crawls WHERE source_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListSourceCrawlsParams struct {
	SourceID uuid.UUID
	PageSize int32
}

func (q *Queries) ListSourceCrawls(ctx context.Context, arg ListSourceCrawlsParams) ([]WebCrawl, error) {
	rows, err := q.db.Query(ctx, listSourceCrawls, arg.SourceID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebCrawl{}
	for rows.Next() {
		var i WebCrawl
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TeamID,
			&i.Status,
			&i.Trigger,
			&i.Config,
			&i.PagesDiscovered,
			&i.PagesFetched,
			&i.PagesChanged,
			&i.PagesUnchanged,
			&i.PagesSkipped,
			&i.PagesFailed,
			&i.DocumentsDeleted,
			&i.Truncated,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TruncatedReason,
			&i.WaitingReason,
			&i.WaitingUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamDomainRequests = `-- name: ListTeamDomainRequests :many
SELECT r.id, r.team_id, r.pattern, r.reason, r.status, r.requested_by, r.reviewed_by, r.review_note, r.reviewed_at, r.created_at, t.slug AS team_slug, t.name AS team_name,
       coalesce(ru.display_name, '')::text AS requester_name, coalesce(ru.email::text, '')::text AS requester_email,
       coalesce(rv.display_name, '')::text AS reviewer_name, coalesce(rv.email::text, '')::text AS reviewer_email
FROM crawl_domain_requests r JOIN teams t ON t.id = r.team_id
LEFT JOIN users ru ON ru.id = r.requested_by
LEFT JOIN users rv ON rv.id = r.reviewed_by
WHERE r.team_id = $1
ORDER BY r.created_at DESC
`

type ListTeamDomainRequestsRow struct {
	ID             uuid.UUID
	TeamID         uuid.UUID
	Pattern        string
	Reason         string
	Status         string
	RequestedBy    uuid.NullUUID
	ReviewedBy     uuid.NullUUID
	ReviewNote     string
	ReviewedAt     *time.Time
	CreatedAt      time.Time
	TeamSlug       string
	TeamName       string
	RequesterName  string
	RequesterEmail string
	ReviewerName   string
	ReviewerEmail  string
}

// Requests with the requester's and reviewer's names (” when the user
// no longer exists).
func (q *Queries) ListTeamDomainRequests(ctx context.Context, teamID uuid.UUID) ([]ListTeamDomainRequestsRow, error) {
	rows, err := q.db.Query(ctx, listTeamDomainRequests, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamDomainRequestsRow{}
	for rows.Next() {
		var i ListTeamDomainRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Pattern,
			&i.Reason,
			&i.Status,
			&i.RequestedBy,
			&i.ReviewedBy,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.TeamSlug,
			&i.TeamName,
			&i.RequesterName,
			&i.RequesterEmail,
			&i.ReviewerName,
			&i.ReviewerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCrawl = `-- name: LockCrawl :one
SELECT id, source_id, team_id, status, trigger, config, pages_discovered, pages_fetched, pages_changed, pages_unchanged, pages_skipped, pages_failed, documents_deleted, truncated, error, created_by, created_at, started_at, finished_at, truncated_reason, waiting_reason, waiting_until FROM web_crawls WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCrawl(ctx context.Context, id uuid.UUID) (WebCrawl, error) {
	row := q.db.QueryRow(ctx, lockCrawl, id)
	var i WebCrawl
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TeamID,
		&i.Status,
		&i.Trigger,
		&i.Config,
		&i.PagesDiscovered,
		&i.PagesFetched,
		&i.PagesChanged,
		&i.PagesUnchanged,
		&i.PagesSkipped,
		&i.PagesFailed,
		&i.DocumentsDeleted,
		&i.Truncated,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.TruncatedReason,
		&i.WaitingReason,
		&i.WaitingUntil,
	)
	return i, err
}

const lockDomainRequest = `-- name: LockDomainRequest :one
SELECT id, team_id, pattern, reason, status, requested_by, reviewed_by, review_note, reviewed_at, created_at FROM crawl_domain_requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockDomainRequest(ctx context.Context, id uuid.UUID) (CrawlDomainRequest, error) {
	row := q.db.QueryRow(ctx, lockDomainRequest, id)
	var i CrawlDomainRequest
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Pattern,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markCrawlTruncated = `-- name: MarkCrawlTruncated :exec
UPDATE web_crawls
SET truncated = true, truncated_reason = CASE WHEN truncated_reason = '' THEN $1::text ELSE truncated_reason END
WHERE id = $2
`

type MarkCrawlTruncatedParams struct {
	Reason string
	ID     uuid.UUID
}

// The first reason a run stopped early is kept.
func (q *Queries) MarkCrawlTruncated(ctx context.Context, arg MarkCrawlTruncatedParams) error {
	_, err := q.db.Exec(ctx, markCrawlTruncated, arg.Reason, arg.ID)
	return err
}

const markDocumentSeen = `-- name: MarkDocumentSeen :exec
UPDATE documents SET last_seen_crawl_id = $1,
    http_etag = CASE WHEN $2::text = '' THEN http_etag ELSE $2::text END,
    http_last_modified = CASE WHEN $3::text = '' THEN http_last_modified ELSE $3::text END
WHERE id = $4
`

type MarkDocumentSeenParams struct {
	CrawlID          uuid.NullUUID
	HttpEtag         string
	HttpLastModified string
	ID               uuid.UUID
}

func (q *Queries) MarkDocumentSeen(ctx context.Context, arg MarkDocumentSeenParams) error {
	_, err := q.db.Exec(ctx, markDocumentSeen,
		arg.CrawlID,
		arg.HttpEtag,
		arg.HttpLastModified,
		arg.ID,
	)
	return err
}

const markFrontier = `-- name: MarkFrontier :exec
UPDATE web_frontier SET status = $1, reason = $2, http_status = $3, updated_at = now()
WHERE crawl_id = $4 AND url = $5
`

type MarkFrontierParams struct {
	Status     string
	Reason     string
	HttpStatus int32
	CrawlID    uuid.UUID
	URL        string
}

func (q *Queries) MarkFrontier(ctx context.Context, arg MarkFrontierParams) error {
	_, err := q.db.Exec(ctx, markFrontier,
		arg.Status,
		arg.Reason,
		arg.HttpStatus,
		arg.CrawlID,
		arg.URL,
	)
	return err
}

const markFrontierFetched = `-- name: MarkFrontierFetched :exec
INSERT INTO web_frontier (crawl_id, url, depth, status)
VALUES ($1, $2, $3, 'done')
ON CONFLICT (crawl_id, url) DO UPDATE SET status = 'done', updated_at = now()
WHERE web_frontier.status = 'pending'
`

type MarkFrontierFetchedParams struct {
	CrawlID uuid.UUID
	URL     string
	Depth   int32
}

// A redirect target fetched under another URL is recorded as done, so it
// is not fetched again in the same run.
func (q *Queries) MarkFrontierFetched(ctx context.Context, arg MarkFrontierFetchedParams) error {
	_, err := q.db.Exec(ctx, markFrontierFetched, arg.CrawlID, arg.URL, arg.Depth)
	return err
}

const nextFrontier = `-- name: NextFrontier :many
SELECT url, depth FROM web_frontier
WHERE crawl_id = $1 AND status = 'pending'
ORDER BY depth, created_at, url
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type NextFrontierParams struct {
	CrawlID  uuid.UUID
	PageSize int32
}

type NextFrontierRow struct {
	URL   string
	Depth int32
}

func (q *Queries) NextFrontier(ctx context.Context, arg NextFrontierParams) ([]NextFrontierRow, error) {
	rows, err := q.db.Query(ctx, nextFrontier, arg.CrawlID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NextFrontierRow{}
	for rows.Next() {
		var i NextFrontierRow
		if err := rows.Scan(&i.URL, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingFrontierExists = `-- name: PendingFrontierExists :one
SELECT EXISTS (SELECT 1 FROM web_frontier WHERE crawl_id = $1 AND status = 'pending')
`

func (q *Queries) PendingFrontierExists(ctx context.Context, crawlID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, pendingFrontierExists, crawlID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const pruneFrontiers = `-- name: PruneFrontiers :exec
DELETE FROM web_frontier
WHERE crawl_id IN (SELECT id FROM web_crawls
                   WHERE source_id = $1 AND id <> $2 AND status NOT IN ('queued', 'running'))
`

type PruneFrontiersParams struct {
	SourceID    uuid.UUID
	KeepCrawlID uuid.UUID
}

// Frontiers of finished earlier runs are only diagnostic; the latest is kept.
func (q *Queries) PruneFrontiers(ctx context.Context, arg PruneFrontiersParams) error {
	_, err := q.db.Exec(ctx, pruneFrontiers, arg.SourceID, arg.KeepCrawlID)
	return err
}

const reviewDomainRequest = `-- name: ReviewDomainRequest :one
UPDATE crawl_domain_requests
SET status = $1, reviewed_by = $2, review_note = $3, reviewed_at = now()
WHERE id = $4
RETURNING id, team_id, pattern, reason, status, requested_by, reviewed_by, review_note, reviewed_at, created_at
`

type ReviewDomainRequestParams struct {
	Status     string
	ReviewedBy uuid.NullUUID
	ReviewNote string
	ID         uuid.UUID
}

func (q *Queries) ReviewDomainRequest(ctx context.Context, arg ReviewDomainRequestParams) (CrawlDomainRequest, error) {
	row := q.db.QueryRow(ctx, reviewDomainRequest,
		arg.Status,
		arg.ReviewedBy,
		arg.ReviewNote,
		arg.ID,
	)
	var i CrawlDomainRequest
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Pattern,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.ReviewNote,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const seedAllowlist = `-- name: SeedAllowlist :one
INSERT INTO crawl_allowlist (pattern, note) VALUES ($1, $2)
ON CONFLICT (pattern) DO NOTHING
RETURNING id, pattern, note, created_by, created_at
`

type SeedAllowlistParams struct {
	Pattern string
	Note    string
}

func (q *Queries) SeedAllowlist(ctx context.Context, arg SeedAllowlistParams) (CrawlAllowlist, error) {
	row := q.db.QueryRow(ctx, seedAllowlist, arg.Pattern, arg.Note)
	var i CrawlAllowlist
	err := row.Scan(
		&i.ID,
		&i.Pattern,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const setCrawlWaiting = `-- name: SetCrawlWaiting :exec
UPDATE web_crawls SET waiting_reason = $1, waiting_until = $2
WHERE id = $3 AND status IN ('queued', 'running')
`

type SetCrawlWaitingParams struct {
	WaitingReason string
	WaitingUntil  *time.Time
	ID            uuid.UUID
}

func (q *Queries) SetCrawlWaiting(ctx context.Context, arg SetCrawlWaitingParams) error {
	_, err := q.db.Exec(ctx, setCrawlWaiting, arg.WaitingReason, arg.WaitingUntil, arg.ID)
	return err
}

const setNextSync = `-- name: SetNextSync :exec
UPDATE data_sources SET next_sync_at = $1, last_sync_at = coalesce($2, last_sync_at) WHERE id = $3
`

type SetNextSyncParams struct {
	NextSyncAt *time.Time
	LastSyncAt *time.Time
	ID         uuid.UUID
}

func (q *Queries) SetNextSync(ctx context.Context, arg SetNextSyncParams) error {
	_, err := q.db.Exec(ctx, setNextSync, arg.NextSyncAt, arg.LastSyncAt, arg.ID)
	return err
}

const startCrawl = `-- name: StartCrawl :execrows
UPDATE web_crawls SET status = 'running', started_at = coalesce(started_at, now()) WHERE id = $1 AND status = 'queued'
`

// Only a queued run starts: a run cancelled (or finished) after the worker
// read it must not be revived.
func (q *Queries) StartCrawl(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, startCrawl, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const teamsWithWaitingCrawls = `-- name: TeamsWithWaitingCrawls :many
SELECT DISTINCT team_id FROM web_crawls
WHERE status = 'queued' AND waiting_reason = 'concurrent_crawls' AND team_id IS NOT NULL
LIMIT 1000
`

func (q *Queries) TeamsWithWaitingCrawls(ctx context.Context) ([]uuid.NullUUID, error) {
	rows, err := q.db.Query(ctx, teamsWithWaitingCrawls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.NullUUID{}
	for rows.Next() {
		var team_id uuid.NullUUID
		if err := rows.Scan(&team_id); err != nil {
			return nil, err
		}
		items = append(items, team_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWebDocument = `-- name: UpsertWebDocument :one

INSERT INTO documents (id, source_id, team_id, external_id, url, content_type, size_bytes, sha256, blob_key,
                       http_etag, http_last_modified, last_seen_crawl_id, tags)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9,
        $10, $11, $12, $13)
ON CONFLICT (source_id, external_id) DO UPDATE
SET url = EXCLUDED.url, tags = EXCLUDED.tags, content_type = EXCLUDED.content_type, size_bytes = EXCLUDED.size_bytes,
    sha256 = EXCLUDED.sha256, blob_key = EXCLUDED.blob_key, http_etag = EXCLUDED.http_etag,
    http_last_modified = EXCLUDED.http_last_modified, last_seen_crawl_id = EXCLUDED.last_seen_crawl_id,
    version = documents.version + 1, status = 'pending', error_code = '', error_message = '',
    attempts = 0, waiting_until = NULL, updated_at = now()
RETURNING id, source_id, team_id, external_id, title, filename, url, kind, content_type, size_bytes, sha256, version, blob_key, status, error_code, error_message, parser, pages, warnings, chunk_count, token_count, metadata, tags, acl, attempts, uploaded_by, created_at, updated_at, processed_at, http_etag, http_last_modified, last_seen_crawl_id, waiting_until
`

type UpsertWebDocumentParams struct {
	ID               uuid.UUID
	SourceID         uuid.UUID
	TeamID           uuid.NullUUID
	ExternalID       string
	URL              string
	ContentType      string
	SizeBytes        int64
	Sha256           string
	BlobKey          string
	HttpEtag         string
	HttpLastModified string
	CrawlID          uuid.NullUUID
	Tags             []string
}

// ---- web documents ---------------------------------------------------------------
func (q *Queries) UpsertWebDocument(ctx context.Context, arg UpsertWebDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, upsertWebDocument,
		arg.ID,
		arg.SourceID,
		arg.TeamID,
		arg.ExternalID,
		arg.URL,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.BlobKey,
		arg.HttpEtag,
		arg.HttpLastModified,
		arg.CrawlID,
		arg.Tags,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TeamID,
		&i.ExternalID,
		&i.Title,
		&i.Filename,
		&i.URL,
		&i.Kind,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Version,
		&i.BlobKey,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Parser,
		&i.Pages,
		&i.Warnings,
		&i.ChunkCount,
		&i.TokenCount,
		&i.Metadata,
		&i.Tags,
		&i.Acl,
		&i.Attempts,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProcessedAt,
		&i.HttpEtag,
		&i.HttpLastModified,
		&i.LastSeenCrawlID,
		&i.WaitingUntil,
	)
	return i, err
}

const waitingCrawls = `-- name: WaitingCrawls :many
SELECT id, source_id, team_id, status, trigger, config, pages_discovered, pages_fetched, pages_changed, pages_unchanged, pages_skipped, pages_failed, documents_deleted, truncated, error, created_by, created_at, started_at, finished_at, truncated_reason, waiting_reason, waiting_until FROM web_crawls
WHERE team_id = $1 AND status = 'queued' AND waiting_reason = 'concurrent_crawls'
ORDER BY created_at, id
LIMIT $2
`

type WaitingCrawlsParams struct {
	TeamID   uuid.NullUUID
	PageSize int32
}

// Runs waiting for a crawl slot, oldest first.
func (q *Queries) WaitingCrawls(ctx context.Context, arg WaitingCrawlsParams) ([]WebCrawl, error) {
	rows, err := q.db.Query(ctx, waitingCrawls, arg.TeamID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebCrawl{}
	for rows.Next() {
		var i WebCrawl
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TeamID,
			&i.Status,
			&i.Trigger,
			&i.Config,
			&i.PagesDiscovered,
			&i.PagesFetched,
			&i.PagesChanged,
			&i.PagesUnchanged,
			&i.PagesSkipped,
			&i.PagesFailed,
			&i.DocumentsDeleted,
			&i.Truncated,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TruncatedReason,
			&i.WaitingReason,
			&i.WaitingUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
